import { LIMITS } from "./contracts";
import { methodDetails, referenceSchemas, tableMethods, handleMethods, chartExamples, referenceNotes, handleExamples } from "./sdk-details";
import { sdkGerman } from "./sdk-locales";
/** Canonical method signatures for cld sdk and generated in-app Help. */
export const sdkReference = {
  version: 2,
  details: methodDetails,
  schemas: referenceSchemas,
  tableMethods,
  chartExamples,
  notes: referenceNotes,
  handleMethods,
  handleExamples,
  descriptions: { de: sdkGerman },
  entrypoints: "*.script.js: export default kit.script({ name, icon?, order?, run() {} })",
  storage: "Browser-local kit/{appShortId}/{userId}/; shared across app pages, not users or devices.",
  limits: {
    sourceMiB: LIMITS.sourceBytes / (1024 * 1024),
    files: LIMITS.files,
    visibleRows: LIMITS.rows,
    uiNodes: LIMITS.nodes,
    localItemMiB: LIMITS.rpcBytes / (1024 * 1024),
  },
  methods: [
    [
      "db.tables.list",
      "db.tables.list()",
      "List tables and row counts in the shared server database. Requires globally enabled rsql and app database activation.",
    ],
    [
      "db.tables.create",
      "db.tables.create({ name, columns })",
      "Create a table. Requires App Admin. Columns have name, type and optional not_null, unique, index.",
    ],
    ["db.tables.delete", "db.tables.delete(name)", "Delete a table and its rows. Requires App Admin."],
    [
      "db.table",
      "db.table(name)",
      "Return bound schema.get(), schema.update(changes), and rows.list(query), rows.get(id), rows.insert(rowOrRows), rows.update(id,row), rows.delete(id). Schema writes need Admin; row access needs Use. Lists return rsql data/meta; limit up to 1000.",
    ],
    [
      "db.query",
      "db.query(sql, params?)",
      "Run a SELECT subset with bound parameters and a 1000-row result budget. No CTEs, comments, internal objects or arbitrary functions. Use row APIs for writes.",
    ],
    [
      "db.importData",
      "db.importData(table, rows, { createTable?, columns?, notify?, onProgress? })",
      "Append validated JSON rows in sequential bounded batches. Missing tables require createTable and Admin. Returns { confirmedRows, totalRows, status, error? }; status is complete, cancelled, failed or unknown. No automatic write retries. Cancellation preserves confirmed batches. onProgress receives { confirmedRows, totalRows, phase }. Default progress toast; notify:false hides it. New manual imports can insert duplicates.",
    ],
    [
      "pdf.text",
      "pdf.text(file, { onProgress? })",
      "Extract local PDF text with PDF.js as [{ page, text }]. No OCR, rendering or uploads. Up to 16 MiB input/text and 1000 pages. onProgress(page, total); Stop terminates the worker.",
    ],
    ["money.fromMinor", "money.fromMinor(amount, currency)", "Create money from safe integer minor units."],
    [
      "money.fromDecimal",
      "money.fromDecimal(decimal, { currency, rounding? })",
      "Parse a decimal string; excess precision requires rounding.",
    ],
    ["money.toDecimal", "money.toDecimal(value)", "Return fixed-decimal major units as a string."],
    ["money.currencyDigits", "money.currencyDigits(currency)", "Return the currency precision."],
    ["money.parse", "money.parse(text, { locale, currency, rounding? })", "Parse numeric text with explicit locale and currency."],
    ["money.format", "money.format(value, { locale })", "Format money with an explicit locale."],
    ["money.add", "money.add(a, b)", "Add values of the same currency."],
    ["money.subtract", "money.subtract(a, b)", "Subtract values of the same currency."],
    ["money.sum", "money.sum(values, { currency }?)", "Sum values; an empty array requires currency."],
    ["money.compare", "money.compare(a, b)", "Compare values of the same currency: -1, 0 or 1."],
    ["money.multiply", "money.multiply(value, factor, { rounding })", "Multiply by a decimal string."],
    ["money.divide", "money.divide(value, divisor, { rounding })", "Divide by a decimal string."],
    ["money.taxFromNet", "money.taxFromNet(value, { percent, rounding })", "Return { net, tax, gross } from net money."],
    ["money.taxFromGross", "money.taxFromGross(value, { percent, rounding })", "Return { net, tax, gross } from gross money."],
    ["money.allocate", "money.allocate(value, weights)", "Distribute minor units exactly using largest remainders."],
    ["script", "script({ name, icon?, order?, run })", "Define a tool page using literal metadata."],
    ["ui.text", "ui.text(text)", "Returns a handle with set(text)."],
    [
      "ui.button",
      "ui.button(label, callback, { id?, variant?, icon?, disabled?, loading? })",
      "Worker callback. Secondary by default; handles expose setDisabled and setLoading.",
    ],
    [
      "ui.input",
      "ui.input(label, { value?, id?, description?, placeholder?, disabled?, loading?, icon?, onChange? })",
      "getValue() reads the text; set(text) changes it without invoking onChange.",
    ],
    [
      "ui.select",
      "ui.select(label, options, initial?, id?)",
      "Options require { value, label }; optional icon and description. getValue() returns the value; set(value) selects a declared option.",
    ],
    [
      "ui.table",
      "ui.table({ columns: [{ key, label, align? }], rowKey?, id?, label?, empty? })",
      "set(rows) replaces rows; upsert(rows) replaces matching keys in place and appends new rows. remove(ids) removes matching keys; remove() clears displayed rows; remove([]) does nothing. upsert and keyed removal require rowKey and unique string/number keys. setColumns and setState remain available. At most 1000 rows.",
    ],
    [
      "ui.workbench",
      "ui.workbench({ controls, content, footer?: { status?, actions? } })",
      "One root workbench: input rail, flexible results, full-width status/actions footer; stacks on narrow screens.",
    ],
    ["ui.section", "ui.section({ title, description? }, children)", "Group handles with a shared section heading."],
    [
      "ui.filePicker",
      "ui.filePicker(label, { accept?, multiple?, description?, icon?, id?, disabled?, loading?, onChange(files) })",
      "Local picker with selected filenames; callback receives File[]. Cancellation keeps current selection.",
    ],
    ["ui.status", "ui.status(text)", "Accessible status. set(text), setState(state), setDescription(text)."],
    [
      "ui.list",
      "ui.list({ title, description?, empty?: { title, description? }, id? }, items)",
      "Items: { id, title, description?, icon?, action?: UIHandle }. set(items) replaces visible rows; upsert(items) replaces matching ids in place and appends new items; remove(ids) removes matching items, remove() clears the list, remove([]) does nothing. Use stable unique ids. Reuse action handles (a row may group buttons); removed rows keep their handles owned by the list. At most 1000 items; allocated UI nodes remain subject to the app node limit.",
    ],
    [
      "ui.link",
      "ui.link(label, { href, newTab?, icon? })",
      "Text navigation link. Relative URLs, HTTP(S), mailto; no worker network access.",
    ],
    [
      "ui.linkButton",
      "ui.linkButton(label, { href, newTab?, icon?, variant?, disabled?, loading?, id?, description? })",
      "Navigation with button appearance; secondary by default.",
    ],
    [
      "ui.markdown",
      "ui.markdown(source, { headingScale?, id? })",
      "Shared Cloud Markdown renderer; set(source). Raw HTML escaped; images shown as alt text without requests.",
    ],
    [
      "ui.modal.confirm",
      "ui.modal.confirm({ title, message, confirmText?, cancelText?, variant? })",
      "Promise<boolean>; false on cancellation. Required visible title. Uses the host Cloud confirmation dialog.",
    ],
    [
      "ui.modal.text",
      "ui.modal.text({ title, label, value?, required?, minLength?, maxLength?, multiline?, confirmText?, cancelText?, variant? })",
      "Promise<string|null>; null on cancellation. Text validation runs in the host.",
    ],
    [
      "ui.modal.number",
      "ui.modal.number({ title, label, value?, required?, min?, max?, confirmText?, cancelText?, variant? })",
      "Promise<number|null>; finite number with optional bounds. null on cancellation.",
    ],
    [
      "ui.modal.dialog",
      "ui.modal.dialog({ title, fields, confirmText?, cancelText?, variant? })",
      "Promise<object|null>. fields maps 1–64 names to { type: text|number|select|boolean, label, required?, default?, description?, placeholder? }. Text supports minLength/maxLength/multiline; number min/max/step; select options require {value,label} with optional icon/description. No callbacks in the schema. Standard buttons and validation inherit Cloud locale; author text is unchanged. Modals close on Stop/navigation and are serialized with other host calls.",
    ],
    [
      "ui.chart",
      "ui.chart({ kind, ...options })",
      "Responsive stdlib chart rendered by the shared UI. Kinds: line/scatter (series:[{label?,data:[{x,y}]}]), bar/pie/donut (data:[{label,value}]), sparkline/histogram (data:number[]), boxplot (groups:[{label,values:number[]}]), gauge (value), barGauge (data:[{label,value}]), stat (label,value), heatmap (data:[{x,y,value}]), map (series:[{data:[{latitude,longitude}]}]), stateTimeline (rows:[{label,intervals:[{from,to,state}]}]). Use set({kind,...options}) to replace the configuration. JSON stdlib option names; no formatter functions, HTML, links, CSS classes or external resources. Shared UI owns size/theme/empty state. At most 1000 array entries total across the configuration. upsert/remove apply only to lists and tables.",
    ],
    ["ui.progress", "ui.progress()", "Use set(fraction) from zero to one."],
    ["ui.row", 'ui.row({ gap: "sm" | "md" | "lg" }, children)', "Compose UI handles horizontally with wrapping."],
    ["ui.column", 'ui.column({ gap: "sm" | "md" | "lg" }, children)', "Compose UI handles vertically."],
    ["file.open", "file.open({ accept? })", "Promise<File|null>; Local file picker; accept uses HTML file types, e.g. .csv,text/csv."],
    ["file.openMultiple", "file.openMultiple({ accept? })", "Promise<File[]>; local files only."],
    ["file.openFolder", "file.openFolder()", "Promise<File[]>; relative paths on webkitRelativePath."],
    ["file.save", "file.save(blobOrText, filename)", "Immediately request a local download; browser download settings apply."],
    ["sheet.fromCsv", "sheet.fromCsv(fileOrText, { delimiter? })", "Parse header-based CSV; preserve strings and identifiers."],
    ["sheet.toCsv", "sheet.toCsv(rows, { delimiter?, bom? })", "Excel-compatible CSV; semicolon/BOM defaults and formula escaping."],
    ["store.get", "store.get(key)", "Read JSON from app-local KV; missing key returns null."],
    ["store.set", "store.set(key, value)", "Persist JSON; requires local storage enabled."],
    ["store.delete", "store.delete(key)", "Delete one local key."],
    ["store.keys", "store.keys()", "List keys of this app/user."],
    ["opfs.read", "opfs.read(path)", "Read local File or null."],
    ["opfs.write", "opfs.write(path, blobOrText)", "Write to this app/user directory; originals are never written."],
    ["opfs.delete", "opfs.delete(path)", "Delete one relative file."],
    ["opfs.list", "opfs.list()", "List relative paths in this app/user directory."],
  ] as const,
};
