/** Canonical method signatures for cld sdk and generated in-app Help. */
export const sdkReference = {
  version: 1,
  entrypoints: "*.script.js: export default kit.script({ name, icon?, order?, run() {} })",
  storage: "Browser-local kit/{appShortId}/{userId}/; shared across app pages, not users or devices.",
  limits: {
    sourceMiB: 2,
    files: 64,
    visibleRows: 1000,
    uiNodes: 300,
    localItemMiB: 16,
  },
  methods: [
    ["pdf.text", "pdf.text(file, { onProgress? })", "Extract local PDF text with PDF.js as [{ page, text }]. No OCR, rendering or uploads. Up to 16 MiB input/text and 1000 pages. onProgress(page, total); Stop terminates the worker."],
    ["money.fromMinor", "money.fromMinor(amount, currency)", "Create money from safe integer minor units."],
    [
      "money.fromDecimal",
      "money.fromDecimal(decimal, { currency, rounding? })",
      "Parse a decimal string; excess precision requires rounding.",
    ],
    ["money.toDecimal", "money.toDecimal(value)", "Return fixed-decimal major units as a string."],
    ["money.currencyDigits", "money.currencyDigits(currency)", "Return the currency precision."],
    ["money.parse", "money.parse(text, { locale, currency, rounding? })", "Parse numeric text with explicit locale and currency."],
    ["money.format", "money.format(value, { locale })", "Format money with an explicit locale."],
    ["money.add", "money.add(a, b)", "Add values of the same currency."],
    ["money.subtract", "money.subtract(a, b)", "Subtract values of the same currency."],
    ["money.sum", "money.sum(values, { currency }?)", "Sum values; an empty array requires currency."],
    ["money.compare", "money.compare(a, b)", "Compare values of the same currency: -1, 0 or 1."],
    ["money.multiply", "money.multiply(value, factor, { rounding })", "Multiply by a decimal string."],
    ["money.divide", "money.divide(value, divisor, { rounding })", "Divide by a decimal string."],
    ["money.taxFromNet", "money.taxFromNet(value, { percent, rounding })", "Return { net, tax, gross } from net money."],
    ["money.taxFromGross", "money.taxFromGross(value, { percent, rounding })", "Return { net, tax, gross } from gross money."],
    ["money.allocate", "money.allocate(value, weights)", "Distribute minor units exactly using largest remainders."],
    ["script", "script({ name, icon?, order?, run })", "Define a tool page using literal metadata."],
    ["ui.text", "ui.text(text)", "Returns a handle with setText(text)."],
    [
      "ui.button",
      "ui.button(label, callback, { id?, variant?, icon?, disabled?, loading? })",
      "Worker callback. Secondary by default; handles expose setDisabled and setLoading.",
    ],
    ["ui.input", "ui.input(label, { value?, id?, description?, placeholder?, onChange? })", "Returns a handle with getValue()."],
    [
      "ui.select",
      "ui.select(label, options, initial?, id?)",
      "Options require { value, label }; optional icon and description. getValue() returns the value.",
    ],
    [
      "ui.table",
      "ui.table({ columns: [{ key, label, align? }], id?, label?, empty? })",
      "setRows(rows), setColumns(columns), setState(ready|empty|loading|error, description?). At most 1000 visible rows.",
    ],
    [
      "ui.workbench",
      "ui.workbench({ controls, content, footer?: { status?, actions? } })",
      "One root workbench: input rail, flexible results, full-width status/actions footer; stacks on narrow screens.",
    ],
    ["ui.section", "ui.section({ title, description? }, children)", "Group handles with a shared section heading."],
    [
      "ui.filePicker",
      "ui.filePicker(label, { accept?, multiple?, description?, icon?, id?, onChange(files) })",
      "Local picker with selected filenames; callback receives File[]. Cancellation keeps current selection.",
    ],
    ["ui.status", "ui.status(text)", "Accessible status. setText(text), setState(state), setDescription(text)."],
    [
      "ui.list",
      "ui.list({ title, description?, empty?: { title, description? }, id? }, items)",
      "Items: { id, title, description?, icon?, action?: UIHandle }. Stable ids, one action handle per row.",
    ],
    [
      "ui.link",
      "ui.link(label, { href, newTab?, icon? })",
      "Text navigation link. Relative URLs, HTTP(S), mailto; no worker network access.",
    ],
    [
      "ui.linkButton",
      "ui.linkButton(label, { href, newTab?, icon?, variant?, disabled? })",
      "Navigation with button appearance; secondary by default.",
    ],
    [
      "ui.markdown",
      "ui.markdown(source, { headingScale?, id? })",
      "Shared Cloud Markdown renderer; setMarkdown(source). Raw HTML escaped; images shown as alt text without requests.",
    ],
    ["ui.progress", "ui.progress()", "Use set(fraction) from zero to one."],
    ["ui.row", 'ui.row({ gap: "sm" | "md" | "lg" }, children)', "Compose UI handles horizontally with wrapping."],
    ["ui.column", 'ui.column({ gap: "sm" | "md" | "lg" }, children)', "Compose UI handles vertically."],
    ["file.open", "file.open({ accept? })", "Promise<File|null>; Local file picker; accept uses HTML file types, e.g. .csv,text/csv."],
    ["file.openMultiple", "file.openMultiple({ accept? })", "Promise<File[]>; local files only."],
    ["file.openFolder", "file.openFolder()", "Promise<File[]>; relative paths on webkitRelativePath."],
    ["file.save", "file.save(blobOrText, filename)", "Immediately request a local download; browser download settings apply."],
    ["sheet.fromCsv", "sheet.fromCsv(fileOrText, { delimiter? })", "Parse header-based CSV; preserve strings and identifiers."],
    ["sheet.toCsv", "sheet.toCsv(rows, { delimiter?, bom? })", "Excel-compatible CSV; semicolon/BOM defaults and formula escaping."],
    ["store.get", "store.get(key)", "Read JSON from app-local KV; missing key returns null."],
    ["store.set", "store.set(key, value)", "Persist JSON; requires local storage enabled."],
    ["store.delete", "store.delete(key)", "Delete one local key."],
    ["store.keys", "store.keys()", "List keys of this app/user."],
    ["opfs.read", "opfs.read(path)", "Read local File or null."],
    ["opfs.write", "opfs.write(path, blobOrText)", "Write to this app/user directory; originals are never written."],
    ["opfs.delete", "opfs.delete(path)", "Delete one relative file."],
    ["opfs.list", "opfs.list()", "List relative paths in this app/user directory."],
  ] as const,
};
