import { i18n } from "@k2b/stdlib";

/**
 * People-facing names of Cloud's built-in Assistant tools, keyed by tool name. Step rows, receipts, and approvals show
 * these; a capability tool brings its own translated title instead. A tool test fails when a built-in tool has no entry.
 */
const toolNames = i18n.define({
  baseLocale: "en",
  messages: {
    en: {
      calculate: "Calculate",
      card: "Card",
      survey: "Survey",
      text_editor: "Text editor",
      local_bash: "Local Bash",
      todo_write: "Working plan",
      memory: "Memory",
      list_files: "List files",
      read_file: "Read file",
      write_file: "Write file",
      fetch_file: "Download file",
      present: "Deliver file",
      markdown_to_pdf: "Markdown to PDF",
      html_to_pdf: "HTML to PDF",
      view_image: "View image",
      transcribe_audio: "Transcribe audio",
      web_search: "Web search",
      web_extract: "Read web page",
      search_tools: "Search tools",
      load_tools: "Load tools",
      list_apps: "List apps",
      search_help: "Search help",
      read_help: "Read help",
      search_project: "Search project",
      read_project_knowledge: "Read project knowledge",
      read_cloud_resource: "Read Cloud item",
      load_skill: "Load skill",
      search_skills: "Search skills",
      code_run: "Run code",
      code_action: "Run app action",
      code_inspect: "Inspect run",
      code_stop: "Stop run",
      code_open: "Open app",
      code_export: "Save run output",
      code_present: "Show app in chat",
      code_check: "App check",
      code_secret: "Enter secret",
      code_database: "App tables",
      code_files: "List stored files",
      code_file_stat: "File details",
      code_file_copy: "Copy file",
      code_database_export: "Export app database",
      code_manage_read: "Read app details",
      code_delete: "Delete app",
      code_database_read: "Read app database",
      code_database_clear: "Clear app data",
      code_database_reset: "Reset app database",
      code_storage_list: "List app storage",
      code_storage_delete: "Delete from app storage",
      code_access_read: "Read app access",
      code_access_change: "Change app access",
      code_actions: "List app actions",
      code_sql: "Query app database",
      code_versions: "List app versions",
      code_list: "Find apps",
      code_read: "Read app source",
      code_history: "App history",
      code_fork: "Copy app",
      code_publish: "Publish app",
      code_unpublish: "Withdraw app",
      code_restore: "Restore app version",
      code_update: "Update app details",
      code_create: "Create app",
      code_write: "Save app files",
      code_remove: "Remove app file",
    },
    de: {
      calculate: "Rechnen",
      card: "Karte",
      survey: "Umfrage",
      text_editor: "Texteditor",
      local_bash: "Lokale Bash",
      todo_write: "Arbeitsplan",
      memory: "Gedächtnis",
      list_files: "Dateien auflisten",
      read_file: "Datei lesen",
      write_file: "Datei schreiben",
      fetch_file: "Datei herunterladen",
      present: "Datei bereitstellen",
      markdown_to_pdf: "Markdown als PDF",
      html_to_pdf: "HTML als PDF",
      view_image: "Bild ansehen",
      transcribe_audio: "Audio transkribieren",
      web_search: "Websuche",
      web_extract: "Webseite lesen",
      search_tools: "Werkzeuge suchen",
      load_tools: "Werkzeuge laden",
      list_apps: "Apps auflisten",
      search_help: "Hilfe durchsuchen",
      read_help: "Hilfe lesen",
      search_project: "Projekt durchsuchen",
      read_project_knowledge: "Projektwissen lesen",
      read_cloud_resource: "Cloud-Eintrag lesen",
      load_skill: "Skill laden",
      search_skills: "Skills suchen",
      code_run: "Code ausführen",
      code_action: "App-Aktion ausführen",
      code_inspect: "Lauf prüfen",
      code_stop: "Lauf beenden",
      code_open: "App öffnen",
      code_export: "Laufergebnis speichern",
      code_present: "App im Chat zeigen",
      code_check: "App-Prüfung",
      code_secret: "Geheimnis eingeben",
      code_database: "App-Tabellen",
      code_files: "Gespeicherte Dateien auflisten",
      code_file_stat: "Dateidetails",
      code_file_copy: "Datei kopieren",
      code_database_export: "App-Datenbank exportieren",
      code_manage_read: "App-Details lesen",
      code_delete: "App löschen",
      code_database_read: "App-Datenbank lesen",
      code_database_clear: "App-Daten leeren",
      code_database_reset: "App-Datenbank zurücksetzen",
      code_storage_list: "App-Speicher auflisten",
      code_storage_delete: "Aus App-Speicher löschen",
      code_access_read: "App-Zugriff lesen",
      code_access_change: "App-Zugriff ändern",
      code_actions: "App-Aktionen auflisten",
      code_sql: "App-Datenbank abfragen",
      code_versions: "App-Versionen auflisten",
      code_list: "Apps suchen",
      code_read: "App-Quelltext lesen",
      code_history: "App-Verlauf",
      code_fork: "App kopieren",
      code_publish: "App veröffentlichen",
      code_unpublish: "App zurückziehen",
      code_restore: "App-Version wiederherstellen",
      code_update: "App-Details ändern",
      code_create: "App erstellen",
      code_write: "App-Dateien speichern",
      code_remove: "App-Datei entfernen",
    },
  },
});

/** Older chats call the visual tools by their `cloud_` names. */
const ALIASES: Record<string, string> = { cloud_card: "card", cloud_survey: "survey", cloud_text_editor: "text_editor" };

/** The localized name of a built-in tool, or undefined for a tool Cloud does not ship. */
export const aiBuiltinToolName = (name: string, locale: string): string | undefined => {
  const t: Record<string, string> = toolNames.resolve([locale]).t;
  const key = ALIASES[name] ?? name;
  return Object.hasOwn(t, key) ? t[key] : undefined;
};

export const checkAiToolNames = () => toolNames.check();
