version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels: [dependencies]
    groups:
      actions:
        patterns: ["*"]
  - package-ecosystem: bun
    directory: /
    schedule:
      interval: weekly
    labels: [dependencies]
    groups:
      workspace:
        patterns: ["*"]
