import { expect, test } from "bun:test";
import { chromium } from "playwright";

test("context overviews use workspace cards and one tab per item without launching apps", async () => {
  const build = Bun.spawn(["bun", new URL("./workspace-browser-build.ts", import.meta.url).pathname, "./context-browser-harness.tsx"], { stdout: "pipe", stderr: "pipe" });
  const code = await new Response(build.stdout).text();
  if (await build.exited) throw new Error(await new Response(build.stderr).text());
  const requests: string[] = [];
  let failAppLoad = true;
  const server = Bun.serve({ hostname: "127.0.0.1", port: 0, fetch(request) {
    const path = new URL(request.url).pathname;
    requests.push(path);
    if (path === "/bundle.js") return new Response(code, { headers: { "content-type": "text/javascript" } });
    if (path === "/ui.css") return new Response(Bun.file(new URL("../../../ui/dist/styles.css", import.meta.url)));
    if (path === "/app.css") return new Response(Bun.file(new URL("../styles/app.css", import.meta.url)));
    if (path.endsWith("/context")) return Response.json({ chatId: "chat-one", files: [], tasks: [], sources: Array.from({ length: 5 }, (_,i) => ({ kind: "resource", key: `app-${i}`, title: `App ${i}`, preview: `Description ${i}`, ref: { type: "assistant.artifact", id: `app-${i}` }, icon: "ti ti-app-window" })) });
    if (path === "/api/assistant/artifacts/app-4" && failAppLoad) {
      failAppLoad = false;
      return Response.json({ message: "HTTP 502" }, { status: 502 });
    }
    if (path.startsWith("/api/assistant/artifacts/")) return Response.json({ id: path.split("/").pop(), title: "Resolved app", revision: 1, permission: "admin", source: { entry: "main.js", files: [{ path: "main.js", content: "console.log(42);" }] } });
    return new Response('<!doctype html><meta charset="utf-8"><link rel="stylesheet" href="/ui.css"><link rel="stylesheet" href="/app.css"><body class="k2b-ui" style="margin:0"><div id="root"></div><script src="/bundle.js"></script>', { headers: { "content-type": "text/html" } });
  } });
  const browser = await chromium.launch({ channel: "chrome", headless: true });
  try {
    const page = await browser.newPage({ viewport: { width: 1500, height: 760 } });
    const errors: string[] = [];
    page.on("pageerror", error => errors.push(error.message));
    await page.goto(server.url.href);
    await page.getByRole("complementary", { name: "Chat context" }).waitFor();
    await page.getByRole("textbox", { name: "Message" }).fill("Keep this draft");
    // No workspace tab exists: narrowing just the pane must expose its opener.
    await page.locator('[data-workspace-main-region="chat"]').evaluate(element => { element.style.maxWidth = "700px"; });
    await page.locator('[data-assistant-context="compact"]').waitFor({ state: "hidden" });
    expect(await page.locator('.assistant-chat-layout').evaluate(element => getComputedStyle(element).getPropertyValue('--assistant-chat-context-width').trim())).toBe("0px");
    await page.locator(".assistant-context-open").getByRole("button", { name: "Open", exact: true }).click();
    await page.getByRole("menuitem", { name: "Apps", exact: true }).click();
    await page.locator('[data-workspace-main-region="chat"]').evaluate(element => { element.style.maxWidth = ""; });
    expect(await page.getByRole("textbox", { name: "Message" }).inputValue()).toBe("Keep this draft");
    await page.setViewportSize({ width: 1900, height: 760 });
    await page.getByRole("complementary", { name: "Chat context" }).waitFor();
    expect(await page.locator(".assistant-context-open").isVisible()).toBe(false);
    await page.setViewportSize({ width: 1500, height: 760 });
    await page.locator('[data-assistant-context="compact"]').waitFor({ state: "hidden" });
    expect(requests.filter(path => path.endsWith("/context")).length).toBe(2);
    await page.locator(".assistant-app-grid").waitFor();
    expect(await page.locator(".assistant-app-grid .k2b-detail-panel__action").count()).toBe(5);
    expect(await page.getByRole("dialog").count()).toBe(0);
    await page.getByRole("textbox", { name: "Search" }).fill("App 4");
    expect(await page.locator(".assistant-app-grid .k2b-detail-panel__action").count()).toBe(1);
    await page.locator(".assistant-app-grid").getByRole("button").click();
    await page.getByText("Could not load this content", { exact: true }).waitFor();
    expect(await page.getByText("HTTP 502", { exact: true }).count()).toBe(0);
    await page.getByRole("button", { name: "Try again", exact: true }).click();
    await page.getByRole("button", { name: "Start", exact: true }).waitFor();
    const consoleToggle = page.getByRole("button", { name: "Console", exact: true });
    expect(await consoleToggle.getAttribute("aria-expanded")).toBe("false");
    expect(await page.locator(".artifact-console").isVisible()).toBe(false);
    await consoleToggle.click();
    expect(await page.locator(".artifact-console").isVisible()).toBe(true);
    await consoleToggle.click();
    await page.getByRole("button", { name: "Source", exact: true }).click();
    await page.getByRole("treeitem", { name: /main.js/ }).waitFor();
    await page.getByRole("tab", { name: /^(Resolved app|App 4)$/ }).click();
    await page.getByRole("button", { name: "Start", exact: true }).waitFor();
    expect(requests.filter(path => path === "/api/assistant/artifacts/app-4").length).toBe(3);
    await page.getByRole("tab", { name: "Apps", exact: true }).click();
    await page.locator(".assistant-app-grid").getByRole("button").click();
    expect(await page.getByRole("tab").count()).toBe(3);
    await page.locator(".artifact-workspace__tabs").getByRole("button", { name: "Open", exact: true }).click();
    await page.getByRole("menuitem", { name: "Files", exact: true }).click();
    await page.getByText("No items yet.").waitFor();
    // Reopening after a tab change must use the same live dropdown instance.
    await page.locator(".artifact-workspace__tabs").getByRole("button", { name: "Open", exact: true }).click();
    await page.getByRole("menuitem", { name: "Apps", exact: true }).waitFor();
    await page.keyboard.press("Escape");
    expect(await page.getByRole("menu").count()).toBe(0);
    await page.locator(".artifact-workspace__tabs").getByRole("button", { name: "Open", exact: true }).click();
    await page.getByRole("menuitem", { name: "Apps", exact: true }).click();
    expect(requests.some(path => path.endsWith("/compiled"))).toBe(false);
    expect(errors).toEqual([]);
    await page.getByRole("tab", { name: "Apps", exact: true }).click();
    await page.getByRole("textbox", { name: "Search" }).fill("");
    await page.screenshot({ path: "/tmp/assistant-context-workspace.png" });
    await page.getByRole("tab", { name: /^(Resolved app|App 4)$/ }).click();
    let release!: () => void;
    const gate = new Promise<void>(resolve => { release = resolve; });
    await page.route("**/api/assistant/artifacts/app-4", async route => {
      await gate;
      await route.fulfill({ status: 500, contentType: "application/json", body: JSON.stringify({ error: "Test failure" }) });
    });
    const restart = page.getByRole("button", { name: "Restart", exact: true });
    const pending = page.waitForRequest(request => request.url().endsWith("/api/assistant/artifacts/app-4"));
    await restart.click();
    await pending;
    expect(await restart.isDisabled()).toBe(true);
    expect(await restart.getAttribute("aria-busy")).toBe("true");
    expect(await restart.locator(".ti-refresh.k2b-spin").count()).toBe(1);
    expect(await restart.locator(".ti-loader-2").count()).toBe(0);
    expect(await page.getByRole("button", { name: "Start", exact: true }).locator(".ti-player-play").count()).toBe(0);
    release();
    await page.locator(".artifact-console [role=alert]").waitFor();
    expect(await consoleToggle.getAttribute("aria-expanded")).toBe("true");
    await page.unroute("**/api/assistant/artifacts/app-4");
    let releaseCancelled!: () => void;
    const cancelledGate = new Promise<void>(resolve => { releaseCancelled = resolve; });
    await page.route("**/api/assistant/artifacts/app-4", async route => { await cancelledGate; await route.continue(); });
    const cancelling = page.waitForRequest(request => request.url().endsWith("/api/assistant/artifacts/app-4"));
    await restart.click();
    await cancelling;
    await page.getByRole("button", { name: "Stop", exact: true }).click();
    const cancelledResponse = page.waitForResponse(response => response.url().endsWith("/api/assistant/artifacts/app-4"));
    releaseCancelled();
    await cancelledResponse;
    expect(await restart.isEnabled()).toBe(true);
    expect(await restart.locator(".k2b-spin").count()).toBe(0);
    expect(requests.some(path => path.endsWith("/compiled"))).toBe(false);
  } finally { await browser.close(); server.stop(true); }
}, 30000);
