import type { MermaidConfig } from "mermaid";

/** Series colors shared by pie slices and mindmap branches. */
const lightSeries = [
  "#dbeafe",
  "#d1fae5",
  "#fef3c7",
  "#ede9fe",
  "#ffe4e6",
  "#cffafe",
  "#ecfccb",
  "#ffedd4",
  "#e0f2fe",
  "#ccfbf1",
  "#fae8ff",
  "#fef9c3",
];
const darkSeries = [
  "#1e3a8a",
  "#065f46",
  "#78350f",
  "#4c1d95",
  "#881337",
  "#155e75",
  "#3f6212",
  "#7c2d12",
  "#075985",
  "#115e59",
  "#86198f",
  "#713f12",
];

// Mermaid derives colors from hex values, so these mirror the Cloud tokens
// (zinc ink, --ui-surface*, --ui-border*) instead of reading CSS variables.
const light = {
  darkMode: false,
  background: "#ffffff",
  textColor: "#27272a",
  titleColor: "#18181b",
  lineColor: "#71717a",
  primaryColor: "#f4f4f5",
  primaryTextColor: "#18181b",
  primaryBorderColor: "#a1a1aa",
  secondaryColor: "#eff6ff",
  secondaryTextColor: "#18181b",
  secondaryBorderColor: "#93c5fd",
  tertiaryColor: "#fafafa",
  tertiaryTextColor: "#18181b",
  tertiaryBorderColor: "#d4d4d8",
  mainBkg: "#f4f4f5",
  nodeBorder: "#a1a1aa",
  clusterBkg: "#fafafa",
  clusterBorder: "#d4d4d8",
  edgeLabelBackground: "#ffffff",
  noteBkgColor: "#fefce8",
  noteBorderColor: "#eab308",
  noteTextColor: "#27272a",
  actorBkg: "#f4f4f5",
  actorBorder: "#a1a1aa",
  actorTextColor: "#18181b",
  signalColor: "#52525b",
  signalTextColor: "#27272a",
  labelBoxBkgColor: "#f4f4f5",
  labelBoxBorderColor: "#a1a1aa",
  activationBkgColor: "#e4e4e7",
  activationBorderColor: "#a1a1aa",
  attributeBackgroundColorOdd: "#ffffff",
  attributeBackgroundColorEven: "#fafafa",
  sectionBkgColor: "#f4f4f5",
  altSectionBkgColor: "#ffffff",
  sectionBkgColor2: "#fafafa",
  gridColor: "#e4e4e7",
  taskBkgColor: "#dbeafe",
  taskBorderColor: "#3b82f6",
  taskTextColor: "#18181b",
  taskTextLightColor: "#18181b",
  taskTextDarkColor: "#18181b",
  taskTextOutsideColor: "#27272a",
  activeTaskBkgColor: "#bfdbfe",
  activeTaskBorderColor: "#2563eb",
  doneTaskBkgColor: "#e4e4e7",
  doneTaskBorderColor: "#a1a1aa",
  critBkgColor: "#ffe4e6",
  critBorderColor: "#e11d48",
  todayLineColor: "#e11d48",
  pieStrokeColor: "#ffffff",
  pieOuterStrokeColor: "#d4d4d8",
  pieSectionTextColor: "#18181b",
  pieTitleTextColor: "#18181b",
  pieLegendTextColor: "#27272a",
  series: lightSeries,
  seriesText: "#18181b",
};

const dark: typeof light = {
  darkMode: true,
  background: "#11151b",
  textColor: "#e4e4e7",
  titleColor: "#f4f4f5",
  lineColor: "#a1a1aa",
  primaryColor: "#20242a",
  primaryTextColor: "#f4f4f5",
  primaryBorderColor: "#5b6573",
  secondaryColor: "#172554",
  secondaryTextColor: "#f4f4f5",
  secondaryBorderColor: "#3b82f6",
  tertiaryColor: "#181d24",
  tertiaryTextColor: "#f4f4f5",
  tertiaryBorderColor: "#3a4552",
  mainBkg: "#20242a",
  nodeBorder: "#5b6573",
  clusterBkg: "#181d24",
  clusterBorder: "#3a4552",
  edgeLabelBackground: "#11151b",
  noteBkgColor: "#422006",
  noteBorderColor: "#a16207",
  noteTextColor: "#fef9c3",
  actorBkg: "#20242a",
  actorBorder: "#5b6573",
  actorTextColor: "#f4f4f5",
  signalColor: "#a1a1aa",
  signalTextColor: "#e4e4e7",
  labelBoxBkgColor: "#20242a",
  labelBoxBorderColor: "#5b6573",
  activationBkgColor: "#29313a",
  activationBorderColor: "#5b6573",
  attributeBackgroundColorOdd: "#181d24",
  attributeBackgroundColorEven: "#20242a",
  sectionBkgColor: "#181d24",
  altSectionBkgColor: "#11151b",
  sectionBkgColor2: "#1c2129",
  gridColor: "#29313a",
  taskBkgColor: "#1e3a8a",
  taskBorderColor: "#60a5fa",
  taskTextColor: "#f4f4f5",
  taskTextLightColor: "#f4f4f5",
  taskTextDarkColor: "#f4f4f5",
  taskTextOutsideColor: "#e4e4e7",
  activeTaskBkgColor: "#1e40af",
  activeTaskBorderColor: "#93c5fd",
  doneTaskBkgColor: "#3f3f46",
  doneTaskBorderColor: "#71717a",
  critBkgColor: "#881337",
  critBorderColor: "#fb7185",
  todayLineColor: "#fb7185",
  pieStrokeColor: "#11151b",
  pieOuterStrokeColor: "#3a4552",
  pieSectionTextColor: "#f4f4f5",
  pieTitleTextColor: "#f4f4f5",
  pieLegendTextColor: "#e4e4e7",
  series: darkSeries,
  seriesText: "#f4f4f5",
};

/**
 * Mermaid configuration that follows Cloud's light or dark tokens.
 *
 * Diagrams keep Mermaid 11's flat look and layouts; an author may still
 * choose `layout: elk` in front matter, which loads ELK on demand. Author
 * directives cannot change security, theme, or CSS.
 */
export function mermaidConfig(options: { dark: boolean }): MermaidConfig {
  const { series, seriesText, ...palette } = options.dark ? dark : light;
  const themeVariables: Record<string, string | boolean> = {
    ...palette,
    fontFamily: '"IBM Plex Sans", ui-sans-serif, system-ui, sans-serif',
  };
  series.forEach((color, index) => {
    themeVariables[`pie${index + 1}`] = color;
    themeVariables[`cScale${index}`] = color;
    themeVariables[`cScaleLabel${index}`] = seriesText;
  });
  return {
    startOnLoad: false,
    securityLevel: "strict",
    suppressErrorRendering: true,
    theme: "base",
    look: "classic",
    // Mermaid 12 lays these types out with ELK by default. Keep dagre so ELK
    // loads only for diagrams whose front matter asks for `layout: elk`.
    flowchart: { layout: "dagre" },
    class: { layout: "dagre" },
    state: { layout: "dagre" },
    er: { layout: "dagre" },
    requirement: { layout: "dagre" },
    themeVariables,
    secure: [
      "secure",
      "securityLevel",
      "startOnLoad",
      "maxTextSize",
      "maxEdges",
      "suppressErrorRendering",
      "htmlLabels",
      "themeCSS",
      "themeVariables",
      "theme",
      "fontFamily",
      "altFontFamily",
    ],
  };
}
