import type { Adjustments, Preset } from "./types";

export const PREVIEW_MAX = 800;

export const DEFAULT_ADJ: Adjustments = {
  brightness: 1,
  contrast: 1,
  saturation: 1,
  hueRotate: 0,
  blur: 0,
  sepia: 0,
  vignette: 0,
  grain: 0,
  freeRotation: 0,
  flipH: false,
  flipV: false,
};

export const PRESETS: Record<string, Preset> = {
  none: {
    brightness: 1,
    contrast: 1,
    saturation: 1,
    hueRotate: 0,
    blur: 0,
    sepia: 0,
    vignette: 0,
    grain: 0,
  },
  vintage: {
    brightness: 1.1,
    contrast: 1.1,
    saturation: 1.3,
    hueRotate: 0,
    blur: 0,
    sepia: 0.3,
    vignette: 0.3,
    grain: 0.1,
  },
  grayscale: {
    brightness: 1,
    contrast: 1.1,
    saturation: 0,
    hueRotate: 0,
    blur: 0,
    sepia: 0,
    vignette: 0,
    grain: 0,
  },
  dramatic: {
    brightness: 0.9,
    contrast: 1.4,
    saturation: 1.2,
    hueRotate: 0,
    blur: 0,
    sepia: 0,
    vignette: 0.2,
    grain: 0,
  },
  soft: {
    brightness: 1.05,
    contrast: 0.95,
    saturation: 0.9,
    hueRotate: 0,
    blur: 0.5,
    sepia: 0,
    vignette: 0,
    grain: 0,
  },
  warm: {
    brightness: 1.05,
    contrast: 1.05,
    saturation: 1.1,
    hueRotate: 15,
    blur: 0,
    sepia: 0.15,
    vignette: 0,
    grain: 0,
  },
  cool: {
    brightness: 1,
    contrast: 1.05,
    saturation: 0.9,
    hueRotate: 200,
    blur: 0,
    sepia: 0,
    vignette: 0,
    grain: 0,
  },
  faded: {
    brightness: 1.1,
    contrast: 0.85,
    saturation: 0.7,
    hueRotate: 0,
    blur: 0,
    sepia: 0.1,
    vignette: 0.15,
    grain: 0.05,
  },
};
