import { i18n } from "@k2b/stdlib";
import { createMockCover } from "@valentinkolb/cloud/shared";
import {
  currentMonthDate,
  documentTemplate,
  field,
  form,
  formula,
  type GridTemplate,
  launcher,
  record,
  table,
  view,
  viewColumns,
} from "./types";

const bookshopMessages = i18n.define({
  baseLocale: "en",
  messages: {
    en: {
      templateName: "Bookshop",
      orderJourney:
        "Add order lines from the overview and select this order. Review the customer email and line amounts before marking the order ready to invoice. Replace example.test addresses in Customers before sending. Generated invoices appear below; later edits do not change an existing document.",
      templateDescription: "Manage a book catalog, customers, orders, fulfillment, and invoice delivery.",
      highlightCatalog: "Relational catalog and order tracking",
      highlightSales: "Sales and fulfillment overview",
      highlightInvoices: "Guided invoice generation and email delivery",
      baseDescription: "Inventory and order tracking for a small bookshop.",
      authors: "Authors",
      authorsDescription: "People who wrote the books.",
      name: "Name",
      authorNameDescription: "The author's display name.",
      birthYear: "Birth year",
      birthYearDescription: "The year the author was born.",
      country: "Country",
      countryDescription: "The country most associated with this author.",
      germany: "Germany",
      unitedKingdom: "United Kingdom",
      unitedStates: "United States",
      japan: "Japan",
      bio: "Bio",
      bioDescription: "Short internal notes about the author.",
      genres: "Genres",
      genresDescription: "Reusable genre catalog.",
      genreNameDescription: "The genre name shown on books and filters.",
      description: "Description",
      genreDescriptionDescription: "Optional notes that explain what belongs in this genre.",
      books: "Books",
      booksDescription: "Catalog and inventory.",
      cover: "Cover",
      coverDescription: "Cover image used in card views.",
      title: "Title",
      titleDescription: "The book title shown in catalog and order forms.",
      bookDescriptionDescription: "Catalog notes or a short summary.",
      author: "Author",
      authorDescription: "The author of this book.",
      genre: "Genre",
      genreDescription: "The primary genre for this book.",
      isbnDescription: "International identifier used for book orders and barcode scans.",
      pages: "Pages",
      pagesDescription: "Number of pages in the book.",
      price: "Price",
      priceDescription: "Selling price for one copy.",
      published: "Published",
      publishedDescription: "Original publication date.",
      inStock: "In stock",
      inStockDescription: "Whether the book is currently available for sale.",
      tags: "Tags",
      tagsDescription: "Optional catalog labels for merchandising and filtering.",
      classic: "Classic",
      recommended: "Recommended",
      onSale: "On sale",
      score: "Score",
      scoreDescription: "Internal recommendation score from 0 to 5.",
      skuDescription: "Automatically assigned stock keeping number.",
      authorCountry: "Author country",
      authorCountryDescription: "Lookup from the linked author.",
      customers: "Customers",
      customersDescription: "Bookshop customers.",
      customerNameDescription: "The customer's display name.",
      email: "Email",
      emailDescription: "Contact address used for order invoices.",
      phone: "Phone",
      phoneDescription: "Optional phone number.",
      joined: "Joined",
      joinedDescription: "Date the customer was first added.",
      notes: "Notes",
      notesDescription: "Private customer notes and reading interests.",
      source: "Source",
      sourceDescription: "How this customer first reached the bookshop.",
      website: "Website",
      inStore: "In-store",
      referral: "Referral",
      orders: "Orders",
      ordersDescription: "Customer orders and their fulfillment state.",
      orderNumber: "Order number",
      orderNumberDescription: "Automatically assigned order number.",
      customer: "Customer",
      customerDescription: "Customer who placed the order.",
      orderedAt: "Ordered at",
      orderedAtDescription: "Date the order was placed.",
      status: "Status",
      statusDescription: "Current fulfillment status.",
      statusNew: "New",
      statusShipped: "Shipped",
      statusDelivered: "Delivered",
      readyToInvoice: "Ready to invoice",
      readyToInvoiceDescription: "Confirm that all order lines are complete before the invoice workflow can run.",
      invoiceSent: "Invoice delivery",
      invoiceSentDescription:
        "Ready, in progress, or sent. Inspect the original run before resetting an interrupted delivery; it may already have sent email.",
      deliveryReady: "Ready",
      deliveryProcessing: "In progress",
      deliverySent: "Sent",
      customerName: "Customer name",
      customerNameLookupDescription: "Lookup from the linked customer.",
      customerEmail: "Customer email",
      customerEmailDescription: "Email address from the linked customer.",
      orderLines: "Order lines",
      orderLinesDescription: "Itemized books and immutable sale prices for each order.",
      lineNumber: "Line number",
      lineNumberDescription: "Generated identifier for this order line.",
      order: "Order",
      orderDescription: "Order this line belongs to.",
      book: "Book",
      bookDescription: "Book sold on this line.",
      quantity: "Quantity",
      quantityDescription: "Number of copies sold.",
      unitPrice: "Unit price",
      unitPriceDescription: "Price captured when the order is placed; later catalog price changes do not alter the invoice.",
      lineTotal: "Line total",
      lineTotalDescription: "Quantity multiplied by the captured unit price.",
      bookTitle: "Book title",
      bookTitleDescription: "Lookup from the linked book.",
      tolkienBio: "Philologist; coined Middle-earth.",
      leGuinBio: "SF/F that takes anthropology seriously.",
      christieBio: "Best-selling mystery novelist.",
      fantasy: "Fantasy",
      fantasyDescription: "Worlds, magic, dragons.",
      sciFi: "Sci-Fi",
      sciFiDescription: "Speculative futures, hard tech.",
      mystery: "Mystery",
      mysteryDescription: "Whodunits and noir.",
      hobbitDescription: "A compact fantasy classic.",
      aliceNotes: "Loves fantasy.",
      recentBooks: "Recent books",
      orderCalendar: "Order calendar",
      addBook: "Add book",
      bookAdded: "Book added.",
      titleHelp: "Book title shown in catalog and order forms.",
      authorHelp: "Pick an existing author or create one inline.",
      authorName: "Author name",
      authorNameHelp: "Full author name.",
      countryHelp: "Optional author country.",
      birthYearHelp: "Optional year of birth.",
      isbnHelp: "Optional ISBN used for ordering and scans.",
      genreHelp: "Pick an existing genre or create one inline.",
      genreName: "Genre name",
      genreNameHelp: "Short catalog genre, for example Fantasy.",
      genreDescriptionHelp: "Optional notes about this genre.",
      pagesHelp: "Number of pages.",
      tagsHelp: "Optional catalog labels.",
      newOrder: "New order",
      createOrder: "Create order",
      orderCreated: "Order created.",
      customerHelp: "Buyer for this order.",
      customerNameHelp: "Full customer name.",
      emailHelp: "Order contact address.",
      orderedAtHelp: "Date the order was placed.",
      addOrderLine: "Add order line",
      addOrderLineDescription: "Add a book and capture the sale price used on the invoice.",
      addLine: "Add line",
      orderLineAdded: "Order line added.",
      orderHelp: "Order this item belongs to.",
      bookHelp: "Book sold on this line.",
      quantityHelp: "Number of copies.",
      unitPriceHelp: "Capture the agreed sale price; the line total is calculated automatically.",
      orderInvoice: "Order invoice",
      orderInvoiceDescription: "Customer invoice with every line belonging to one order.",
      orderInvoiceReady: "Order invoice ready",
      orderInvoiceReadyDescription: "Sends a private invoice link to the customer.",
      invoiceSubject: "Invoice for order {{ data.orderNumber }}",
      invoiceEmailHtml: `<main style="font-family:Arial,sans-serif;color:#111827;line-height:1.5;max-width:640px;margin:0 auto;padding:32px;">
  <h1 style="font-size:24px;margin:0 0 16px;">Your invoice is ready</h1>
  <p>Hello {{ data.customerName | default: "there" }},</p>
  <p>We prepared the invoice for order <strong>{{ data.orderNumber }}</strong>.</p>
  <p style="margin:24px 0;"><a href="{{ data.invoice.url }}" style="display:inline-block;background:#2563eb;color:#fff;text-decoration:none;padding:12px 18px;border-radius:6px;">Download invoice</a></p>
  <p style="color:#6b7280;font-size:14px;">This private link expires automatically.</p>
</main>`,
      sendOrderInvoice: "Send order invoice",
      sendOrderInvoiceDescription: "Generates an invoice, creates a private link, and emails it to the customer.",
      invoiceAlreadySent: "Invoice delivery is not ready. Inspect the original workflow run and existing documents before retrying.",
      addCustomerEmail: "Add a customer email address before sending the invoice.",
      replaceSampleEmail: "Replace the sample customer email before sending a real invoice.",
      completeOrderLines: "Add every order line, then mark the order as ready to invoice.",
      invoiceSentMessage: ({ orderNumber, customerEmail }: { orderNumber: string; customerEmail: string }) =>
        `Invoice ${orderNumber} sent to ${customerEmail}.`,
      chooseOrderToSendInvoice: "Choose order to send invoice",
      bookshopOverview: "Bookshop overview",
      totalRevenue: "Total revenue",
      monthlyRevenue: "Monthly revenue",
      revenueByCustomer: "Revenue by customer",
      revenueByCustomerSubtitle: "Joined directly from orders and customers",
      ordersReadyToInvoice: "Orders ready to invoice",
      sendInvoice: "Send invoice",
    },
    de: {
      templateName: "Buchhandlung",
      orderJourney:
        "Füge Positionen über die Übersicht hinzu und wähle diese Bestellung. Prüfe die Kundenadresse und Positionsbeträge, bevor du die Bestellung zur Rechnungsstellung freigibst. Ersetze example.test-Adressen in Kunden vor dem Versand. Erzeugte Rechnungen erscheinen unten; spätere Änderungen verändern bestehende Dokumente nicht.",
      templateDescription: "Verwalte Buchkatalog, Kundschaft, Bestellungen, Versand und Rechnungszustellung.",
      highlightCatalog: "Verknüpfter Katalog und Bestellverfolgung",
      highlightSales: "Übersicht über Umsatz und Versand",
      highlightInvoices: "Geführte Rechnungserstellung und Versand per E-Mail",
      baseDescription: "Bestands- und Bestellverwaltung für eine kleine Buchhandlung.",
      authors: "Autoren",
      authorsDescription: "Personen, die die Bücher geschrieben haben.",
      name: "Name",
      authorNameDescription: "Anzeigename des Autors.",
      birthYear: "Geburtsjahr",
      birthYearDescription: "Geburtsjahr des Autors.",
      country: "Land",
      countryDescription: "Land, mit dem der Autor hauptsächlich verbunden ist.",
      germany: "Deutschland",
      unitedKingdom: "Vereinigtes Königreich",
      unitedStates: "Vereinigte Staaten",
      japan: "Japan",
      bio: "Biografie",
      bioDescription: "Kurze interne Notizen über den Autor.",
      genres: "Genres",
      genresDescription: "Wiederverwendbarer Genrekatalog.",
      genreNameDescription: "Name des Genres für Bücher und Filter.",
      description: "Beschreibung",
      genreDescriptionDescription: "Optionale Hinweise dazu, was zu diesem Genre gehört.",
      books: "Bücher",
      booksDescription: "Katalog und Bestand.",
      cover: "Cover",
      coverDescription: "Coverbild für Kartenansichten.",
      title: "Titel",
      titleDescription: "Buchtitel im Katalog und in Bestellformularen.",
      bookDescriptionDescription: "Katalognotizen oder eine kurze Zusammenfassung.",
      author: "Autor",
      authorDescription: "Autor dieses Buches.",
      genre: "Genre",
      genreDescription: "Hauptgenre dieses Buches.",
      isbnDescription: "Internationale Kennung für Buchbestellungen und Barcodescans.",
      pages: "Seiten",
      pagesDescription: "Seitenzahl des Buches.",
      price: "Preis",
      priceDescription: "Verkaufspreis eines Exemplars.",
      published: "Veröffentlichungsdatum",
      publishedDescription: "Datum der Erstveröffentlichung.",
      inStock: "Auf Lager",
      inStockDescription: "Gibt an, ob das Buch derzeit verkauft werden kann.",
      tags: "Schlagwörter",
      tagsDescription: "Optionale Katalogkennzeichnungen für Präsentation und Filter.",
      classic: "Klassiker",
      recommended: "Empfohlen",
      onSale: "Im Angebot",
      score: "Bewertung",
      scoreDescription: "Interne Empfehlung von 0 bis 5.",
      skuDescription: "Automatisch vergebene Artikelnummer.",
      authorCountry: "Land des Autors",
      authorCountryDescription: "Aus dem verknüpften Autor übernommen.",
      customers: "Kunden",
      customersDescription: "Kunden der Buchhandlung.",
      customerNameDescription: "Anzeigename des Kunden.",
      email: "E-Mail-Adresse",
      emailDescription: "Kontaktadresse für Bestellrechnungen.",
      phone: "Telefon",
      phoneDescription: "Optionale Telefonnummer.",
      joined: "Hinzugefügt am",
      joinedDescription: "Datum, an dem der Kunde erstmals hinzugefügt wurde.",
      notes: "Notizen",
      notesDescription: "Private Kundennotizen und Leseinteressen.",
      source: "Quelle",
      sourceDescription: "Wie der Kunde erstmals auf die Buchhandlung aufmerksam wurde.",
      website: "Website",
      inStore: "Im Laden",
      referral: "Empfehlung",
      orders: "Bestellungen",
      ordersDescription: "Bestellungen und ihr Versandstatus.",
      orderNumber: "Bestellnummer",
      orderNumberDescription: "Automatisch vergebene Bestellnummer.",
      customer: "Kunde",
      customerDescription: "Kunde, der die Bestellung aufgegeben hat.",
      orderedAt: "Bestelldatum",
      orderedAtDescription: "Datum der Bestellung.",
      status: "Status",
      statusDescription: "Aktueller Versandstatus.",
      statusNew: "Neu",
      statusShipped: "Versendet",
      statusDelivered: "Zugestellt",
      readyToInvoice: "Bereit zur Rechnungsstellung",
      readyToInvoiceDescription:
        "Bestätigt, dass alle Bestellpositionen vollständig sind und der Rechnungsworkflow ausgeführt werden kann.",
      invoiceSent: "Rechnungsversand",
      invoiceSentDescription:
        "Bereit, in Bearbeitung oder gesendet. Prüfe vor dem Zurücksetzen eines unterbrochenen Versands den ursprünglichen Lauf; die E-Mail könnte bereits gesendet worden sein.",
      deliveryReady: "Bereit",
      deliveryProcessing: "In Bearbeitung",
      deliverySent: "Gesendet",
      customerName: "Kundenname",
      customerNameLookupDescription: "Aus dem verknüpften Kunden übernommen.",
      customerEmail: "E-Mail-Adresse des Kunden",
      customerEmailDescription: "E-Mail-Adresse des verknüpften Kunden.",
      orderLines: "Bestellpositionen",
      orderLinesDescription: "Aufgeschlüsselte Bücher und unveränderliche Verkaufspreise jeder Bestellung.",
      lineNumber: "Positionsnummer",
      lineNumberDescription: "Erzeugte Kennung für diese Bestellposition.",
      order: "Bestellung",
      orderDescription: "Bestellung, zu der diese Position gehört.",
      book: "Buch",
      bookDescription: "In dieser Position verkauftes Buch.",
      quantity: "Menge",
      quantityDescription: "Anzahl der verkauften Exemplare.",
      unitPrice: "Stückpreis",
      unitPriceDescription: "Beim Bestellen erfasster Preis; spätere Änderungen am Katalogpreis ändern die Rechnung nicht.",
      lineTotal: "Positionssumme",
      lineTotalDescription: "Menge multipliziert mit dem erfassten Stückpreis.",
      bookTitle: "Buchtitel",
      bookTitleDescription: "Aus dem verknüpften Buch übernommen.",
      tolkienBio: "Philologe; prägte den Begriff Mittelerde.",
      leGuinBio: "Science-Fiction und Fantasy mit ernsthaftem anthropologischem Blick.",
      christieBio: "Erfolgreiche Krimiautorin.",
      fantasy: "Fantasy",
      fantasyDescription: "Welten, Magie und Drachen.",
      sciFi: "Science-Fiction",
      sciFiDescription: "Spekulative Zukunft und anspruchsvolle Technik.",
      mystery: "Krimi",
      mysteryDescription: "Detektivgeschichten und Noir.",
      hobbitDescription: "Ein kompakter Fantasyklassiker.",
      aliceNotes: "Liebt Fantasy.",
      recentBooks: "Zuletzt veröffentlichte Bücher",
      orderCalendar: "Bestellkalender",
      addBook: "Buch hinzufügen",
      bookAdded: "Buch hinzugefügt.",
      titleHelp: "Buchtitel im Katalog und in Bestellformularen.",
      authorHelp: "Wähle einen vorhandenen Autor oder erstelle direkt einen neuen.",
      authorName: "Name des Autors",
      authorNameHelp: "Vollständiger Name des Autors.",
      countryHelp: "Optionales Land des Autors.",
      birthYearHelp: "Optionales Geburtsjahr.",
      isbnHelp: "Optionale ISBN für Bestellungen und Scans.",
      genreHelp: "Wähle ein vorhandenes Genre oder erstelle direkt ein neues.",
      genreName: "Name des Genres",
      genreNameHelp: "Kurzes Kataloggenre, zum Beispiel Fantasy.",
      genreDescriptionHelp: "Optionale Hinweise zu diesem Genre.",
      pagesHelp: "Anzahl der Seiten.",
      tagsHelp: "Optionale Katalogkennzeichnungen.",
      newOrder: "Neue Bestellung",
      createOrder: "Bestellung erstellen",
      orderCreated: "Bestellung erstellt.",
      customerHelp: "Kunde für diese Bestellung.",
      customerNameHelp: "Vollständiger Name des Kunden.",
      emailHelp: "Kontaktadresse für die Bestellung.",
      orderedAtHelp: "Datum der Bestellung.",
      addOrderLine: "Bestellposition hinzufügen",
      addOrderLineDescription: "Füge ein Buch hinzu und erfasse den Verkaufspreis für die Rechnung.",
      addLine: "Position hinzufügen",
      orderLineAdded: "Bestellposition hinzugefügt.",
      orderHelp: "Bestellung, zu der diese Position gehört.",
      bookHelp: "In dieser Position verkauftes Buch.",
      quantityHelp: "Anzahl der Exemplare.",
      unitPriceHelp: "Erfasse den vereinbarten Verkaufspreis; die Positionssumme wird automatisch berechnet.",
      orderInvoice: "Bestellrechnung",
      orderInvoiceDescription: "Kundenrechnung mit allen Positionen einer Bestellung.",
      orderInvoiceReady: "Bestellrechnung verfügbar",
      orderInvoiceReadyDescription: "Sendet dem Kunden einen privaten Link zur Rechnung.",
      invoiceSubject: "Rechnung für Bestellung {{ data.orderNumber }}",
      invoiceEmailHtml: `<main style="font-family:Arial,sans-serif;color:#111827;line-height:1.5;max-width:640px;margin:0 auto;padding:32px;">
  <h1 style="font-size:24px;margin:0 0 16px;">Deine Rechnung ist verfügbar</h1>
  <p>Hallo {{ data.customerName | default: "zusammen" }},</p>
  <p>Wir haben die Rechnung für die Bestellung <strong>{{ data.orderNumber }}</strong> erstellt.</p>
  <p style="margin:24px 0;"><a href="{{ data.invoice.url }}" style="display:inline-block;background:#2563eb;color:#fff;text-decoration:none;padding:12px 18px;border-radius:6px;">Rechnung herunterladen</a></p>
  <p style="color:#6b7280;font-size:14px;">Dieser private Link läuft automatisch ab.</p>
</main>`,
      sendOrderInvoice: "Bestellrechnung senden",
      sendOrderInvoiceDescription: "Erstellt eine Rechnung und einen privaten Link und sendet beides per E-Mail an den Kunden.",
      invoiceAlreadySent:
        "Der Rechnungsversand ist nicht bereit. Prüfe vor einem erneuten Versuch den ursprünglichen Workflow-Lauf und vorhandene Dokumente.",
      addCustomerEmail: "Füge vor dem Senden der Rechnung eine E-Mail-Adresse des Kunden hinzu.",
      replaceSampleEmail: "Ersetze die Beispieladresse des Kunden, bevor du eine echte Rechnung sendest.",
      completeOrderLines: "Füge alle Bestellpositionen hinzu und markiere die Bestellung anschließend als rechnungsbereit.",
      invoiceSentMessage: ({ orderNumber, customerEmail }) => `Rechnung ${orderNumber} an ${customerEmail} gesendet.`,
      chooseOrderToSendInvoice: "Bestellung für Rechnungsversand wählen",
      bookshopOverview: "Buchhandlungsübersicht",
      totalRevenue: "Gesamtumsatz",
      monthlyRevenue: "Monatlicher Umsatz",
      revenueByCustomer: "Umsatz nach Kunde",
      revenueByCustomerSubtitle: "Direkt aus Bestellungen und Kunden verknüpft",
      ordersReadyToInvoice: "Rechnungsbereite Bestellungen",
      sendInvoice: "Rechnung senden",
    },
  },
});

export const createBookshopTemplate = (locale?: string): GridTemplate => {
  const { t } = bookshopMessages.resolve(locale ? [locale] : []);

  return {
    id: "bookshop",
    name: t.templateName,
    description: t.templateDescription,
    highlights: [t.highlightCatalog, t.highlightSales, t.highlightInvoices],
    icon: "ti ti-books",
    baseName: t.templateName,
    baseDescription: t.baseDescription,
    navigationGroups: [
      {
        name: t.orders,
        entries: [
          { type: "customApp", key: "sales" },
          { type: "table", key: "orders" },
          { type: "form", key: "new_order" },
          { type: "form", key: "add_order_line" },
          { type: "workflow", key: "send_order_invoice" },
          { type: "documentTemplate", key: "order_invoice" },
        ],
      },
      {
        name: t.books,
        entries: [
          { type: "view", key: "recent_books" },
          { type: "form", key: "add_book" },
          { type: "table", key: "authors" },
        ],
      },
    ],
    tables: [
      {
        key: "authors",
        name: t.authors,
        description: t.authorsDescription,
        fields: [
          {
            key: "name",
            name: t.name,
            description: t.authorNameDescription,
            type: "text",
            config: { maxLength: 200 },
            required: true,
            presentable: true,
            icon: "ti ti-user",
          },
          {
            key: "birth_year",
            name: t.birthYear,
            description: t.birthYearDescription,
            type: "number",
            config: { min: 1000, max: 3000, integerOnly: true },
            icon: "ti ti-calendar",
          },
          {
            key: "country",
            name: t.country,
            description: t.countryDescription,
            type: "select",
            icon: "ti ti-map-pin",
            config: {
              options: [
                { id: "de", label: t.germany, color: "#ef4444" },
                { id: "uk", label: t.unitedKingdom, color: "#3b82f6" },
                { id: "us", label: t.unitedStates, color: "#10b981" },
                { id: "jp", label: t.japan, color: "#f59e0b" },
              ],
            },
          },
          {
            key: "bio",
            name: t.bio,
            description: t.bioDescription,
            type: "longtext",
            icon: "ti ti-notes",
          },
        ],
      },
      {
        key: "genres",
        name: t.genres,
        description: t.genresDescription,
        fields: [
          {
            key: "name",
            name: t.name,
            description: t.genreNameDescription,
            type: "text",
            config: { maxLength: 80 },
            required: true,
            presentable: true,
            icon: "ti ti-tag",
          },
          {
            key: "description",
            name: t.description,
            description: t.genreDescriptionDescription,
            type: "longtext",
            icon: "ti ti-align-left",
          },
        ],
      },
      {
        key: "books",
        name: t.books,
        description: t.booksDescription,
        displayConfig: {
          mode: "cards",
          cards: {
            imageFieldId: field("books.cover"),
            fieldIds: [field("books.title"), field("books.author"), field("books.genre"), field("books.price"), field("books.in_stock")],
          },
        },
        fields: [
          {
            key: "cover",
            name: t.cover,
            description: t.coverDescription,
            type: "file",
            config: { maxFiles: 1, accept: ["image/*"] },
            hideInTable: true,
            icon: "ti ti-photo",
          },
          {
            key: "title",
            name: t.title,
            description: t.titleDescription,
            type: "text",
            config: { maxLength: 200 },
            required: true,
            presentable: true,
            icon: "ti ti-book",
          },
          {
            key: "description",
            name: t.description,
            description: t.bookDescriptionDescription,
            type: "longtext",
            icon: "ti ti-align-left",
          },
          {
            key: "author",
            name: t.author,
            description: t.authorDescription,
            type: "relation",
            required: true,
            icon: "ti ti-user",
            config: { targetTableId: table("authors"), cardinality: "single" },
          },
          {
            key: "genre",
            name: t.genre,
            description: t.genreDescription,
            type: "relation",
            required: true,
            icon: "ti ti-tags",
            config: { targetTableId: table("genres"), cardinality: "single" },
          },
          {
            key: "isbn",
            name: "ISBN",
            description: t.isbnDescription,
            type: "text",
            config: { regex: "^97[89]-[0-9]-[0-9]{2,5}-[0-9]{3,7}-[0-9X]$" },
            icon: "ti ti-barcode",
          },
          {
            key: "pages",
            name: t.pages,
            description: t.pagesDescription,
            type: "number",
            config: { min: 1, integerOnly: true },
            icon: "ti ti-file-text",
          },
          {
            key: "price",
            name: t.price,
            description: t.priceDescription,
            type: "number",
            required: true,
            icon: "ti ti-currency-euro",
            config: {
              precision: 16,
              decimalPlaces: 2,
              unit: "EUR",
              unitPosition: "suffix",
            },
          },
          {
            key: "published",
            name: t.published,
            description: t.publishedDescription,
            type: "date",
            icon: "ti ti-calendar",
          },
          {
            key: "in_stock",
            name: t.inStock,
            description: t.inStockDescription,
            type: "boolean",
            defaultValue: true,
            icon: "ti ti-package",
          },
          {
            key: "tags",
            name: t.tags,
            description: t.tagsDescription,
            type: "select",
            icon: "ti ti-tags",
            config: {
              multiple: true,
              options: [
                { id: "classic", label: t.classic, color: "#f59e0b" },
                { id: "recommended", label: t.recommended, color: "#22c55e" },
                { id: "sale", label: t.onSale, color: "#ef4444" },
              ],
            },
          },
          {
            key: "score",
            name: t.score,
            description: t.scoreDescription,
            type: "number",
            config: { min: 0, max: 5, integerOnly: true },
            icon: "ti ti-star",
          },
          {
            key: "sku",
            name: "SKU",
            description: t.skuDescription,
            type: "id",
            config: { strategy: "sequence", prefix: "SKU-", padding: 5 },
            icon: "ti ti-barcode",
          },
          {
            key: "author_country",
            name: t.authorCountry,
            description: t.authorCountryDescription,
            type: "lookup",
            config: {
              relationFieldId: field("books.author"),
              targetFieldId: field("authors.country"),
            },
            icon: "ti ti-hierarchy",
          },
        ],
      },
      {
        key: "customers",
        name: t.customers,
        description: t.customersDescription,
        fields: [
          {
            key: "name",
            name: t.name,
            description: t.customerNameDescription,
            type: "text",
            config: { maxLength: 200 },
            required: true,
            presentable: true,
            icon: "ti ti-user",
          },
          {
            key: "email",
            name: t.email,
            description: t.emailDescription,
            type: "text",
            config: { regex: "^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$" },
            required: true,
            icon: "ti ti-mail",
          },
          {
            key: "phone",
            name: t.phone,
            description: t.phoneDescription,
            type: "text",
            config: { maxLength: 40 },
            icon: "ti ti-phone",
          },
          {
            key: "joined",
            name: t.joined,
            description: t.joinedDescription,
            type: "date",
            icon: "ti ti-calendar-plus",
          },
          {
            key: "notes",
            name: t.notes,
            description: t.notesDescription,
            type: "longtext",
            icon: "ti ti-notes",
          },
          {
            key: "source",
            name: t.source,
            description: t.sourceDescription,
            type: "select",
            icon: "ti ti-route",
            config: {
              options: [
                { id: "website", label: t.website, color: "#3b82f6" },
                { id: "store", label: t.inStore, color: "#22c55e" },
                { id: "referral", label: t.referral, color: "#a855f7" },
              ],
            },
          },
        ],
      },
      {
        key: "orders",
        name: t.orders,
        description: t.ordersDescription,
        fields: [
          {
            key: "order_no",
            name: t.orderNumber,
            description: t.orderNumberDescription,
            type: "id",
            config: {
              strategy: "date_sequence",
              prefix: "ORD-",
              period: "year",
              padding: 4,
            },
            presentable: true,
            icon: "ti ti-hash",
          },
          {
            key: "customer",
            name: t.customer,
            description: t.customerDescription,
            type: "relation",
            required: true,
            icon: "ti ti-user",
            config: { targetTableId: table("customers"), cardinality: "single" },
          },
          {
            key: "ordered_at",
            name: t.orderedAt,
            description: t.orderedAtDescription,
            type: "date",
            required: true,
            icon: "ti ti-calendar",
          },
          {
            key: "status",
            name: t.status,
            description: t.statusDescription,
            type: "select",
            icon: "ti ti-truck-delivery",
            config: {
              options: [
                { id: "new", label: t.statusNew, color: "#3b82f6" },
                { id: "shipped", label: t.statusShipped, color: "#f59e0b" },
                { id: "delivered", label: t.statusDelivered, color: "#22c55e" },
              ],
            },
            required: true,
            defaultValue: ["new"],
          },
          {
            key: "invoice_ready",
            name: t.readyToInvoice,
            description: t.readyToInvoiceDescription,
            type: "boolean",
            defaultValue: false,
            icon: "ti ti-file-check",
          },
          {
            key: "invoice_sent",
            name: t.invoiceSent,
            description: t.invoiceSentDescription,
            type: "select",
            required: true,
            config: {
              options: [
                { id: "ready", label: t.deliveryReady },
                { id: "processing", label: t.deliveryProcessing },
                { id: "sent", label: t.deliverySent },
              ],
            },
            defaultValue: ["ready"],
            icon: "ti ti-mail-check",
          },
          {
            key: "customer_name",
            name: t.customerName,
            description: t.customerNameLookupDescription,
            type: "lookup",
            config: {
              relationFieldId: field("orders.customer"),
              targetFieldId: field("customers.name"),
            },
            icon: "ti ti-hierarchy",
          },
          {
            key: "customer_email",
            name: t.customerEmail,
            description: t.customerEmailDescription,
            type: "lookup",
            config: {
              relationFieldId: field("orders.customer"),
              targetFieldId: field("customers.email"),
            },
            icon: "ti ti-mail",
          },
        ],
      },
      {
        key: "order_lines",
        name: t.orderLines,
        description: t.orderLinesDescription,
        fields: [
          {
            key: "line_no",
            name: t.lineNumber,
            description: t.lineNumberDescription,
            type: "id",
            config: { strategy: "sequence", prefix: "LINE-", padding: 5 },
            presentable: true,
            icon: "ti ti-list-numbers",
          },
          {
            key: "order",
            name: t.order,
            description: t.orderDescription,
            type: "relation",
            required: true,
            icon: "ti ti-shopping-cart",
            config: { targetTableId: table("orders"), cardinality: "single" },
          },
          {
            key: "book",
            name: t.book,
            description: t.bookDescription,
            type: "relation",
            required: true,
            icon: "ti ti-book",
            config: { targetTableId: table("books"), cardinality: "single" },
          },
          {
            key: "quantity",
            name: t.quantity,
            description: t.quantityDescription,
            type: "number",
            required: true,
            defaultValue: "1",
            config: { min: 1, integerOnly: true },
            icon: "ti ti-calculator",
          },
          {
            key: "unit_price",
            name: t.unitPrice,
            description: t.unitPriceDescription,
            type: "number",
            required: true,
            icon: "ti ti-currency-euro",
            config: {
              precision: 16,
              decimalPlaces: 2,
              min: "0",
              unit: "EUR",
              unitPosition: "suffix",
            },
          },
          {
            key: "line_total",
            name: t.lineTotal,
            description: t.lineTotalDescription,
            type: "formula",
            config: {
              expression: formula(field("order_lines.quantity"), " * ", field("order_lines.unit_price")),
              format: { kind: "decimal", precision: 2, thousandsSeparator: true },
            },
            icon: "ti ti-calculator",
          },
          {
            key: "book_title",
            name: t.bookTitle,
            description: t.bookTitleDescription,
            type: "lookup",
            config: {
              relationFieldId: field("order_lines.book"),
              targetFieldId: field("books.title"),
            },
            icon: "ti ti-hierarchy",
          },
        ],
      },
    ],
    records: [
      {
        key: "authors.tolkien",
        table: "authors",
        values: {
          name: "J.R.R. Tolkien",
          birth_year: 1892,
          country: ["uk"],
          bio: t.tolkienBio,
        },
      },
      {
        key: "authors.le_guin",
        table: "authors",
        values: {
          name: "Ursula K. Le Guin",
          birth_year: 1929,
          country: ["us"],
          bio: t.leGuinBio,
        },
      },
      {
        key: "authors.christie",
        table: "authors",
        values: {
          name: "Agatha Christie",
          birth_year: 1890,
          country: ["uk"],
          bio: t.christieBio,
        },
      },
      {
        key: "genres.fantasy",
        table: "genres",
        values: { name: t.fantasy, description: t.fantasyDescription },
      },
      {
        key: "genres.scifi",
        table: "genres",
        values: {
          name: t.sciFi,
          description: t.sciFiDescription,
        },
      },
      {
        key: "genres.mystery",
        table: "genres",
        values: { name: t.mystery, description: t.mysteryDescription },
      },
      {
        key: "books.hobbit",
        table: "books",
        values: {
          title: "The Hobbit",
          description: t.hobbitDescription,
          author: [record("authors.tolkien")],
          genre: [record("genres.fantasy")],
          isbn: "978-0-547-92822-7",
          pages: 310,
          price: "9.99",
          published: "1937-09-21",
          in_stock: true,
          tags: ["classic", "recommended"],
          score: 5,
        },
        files: [
          {
            field: "cover",
            filename: "the-hobbit-cover.svg",
            dataUrl: createMockCover({
              icon: "book",
              theme: "emerald",
              seed: "bookshop:the-hobbit",
              label: "The Hobbit",
            }).dataUrl,
          },
        ],
      },
      {
        key: "books.left_hand",
        table: "books",
        values: {
          title: "The Left Hand of Darkness",
          author: [record("authors.le_guin")],
          genre: [record("genres.scifi")],
          isbn: "978-0-441-47812-5",
          pages: 304,
          price: "11.99",
          published: "1969-03-01",
          in_stock: true,
          tags: ["recommended"],
          score: 5,
        },
        files: [
          {
            field: "cover",
            filename: "left-hand-of-darkness-cover.svg",
            dataUrl: createMockCover({
              icon: "book",
              theme: "violet",
              seed: "bookshop:left-hand",
              label: "The Left Hand of Darkness",
            }).dataUrl,
          },
        ],
      },
      {
        key: "books.abc",
        table: "books",
        values: {
          title: "The ABC Murders",
          author: [record("authors.christie")],
          genre: [record("genres.mystery")],
          isbn: "978-0-00-752752-6",
          pages: 220,
          price: "8.50",
          published: "1936-01-06",
          in_stock: false,
          tags: [],
          score: 4,
        },
        files: [
          {
            field: "cover",
            filename: "abc-murders-cover.svg",
            dataUrl: createMockCover({
              icon: "book",
              theme: "amber",
              seed: "bookshop:abc",
              label: "The ABC Murders",
            }).dataUrl,
          },
        ],
      },
      {
        key: "customers.alice",
        table: "customers",
        values: {
          name: "Alice Becker",
          email: "alice@example.test",
          phone: "+49 731 1234567",
          joined: "2025-03-12",
          notes: t.aliceNotes,
          source: ["website"],
        },
      },
      {
        key: "customers.bob",
        table: "customers",
        values: {
          name: "Bob Schmidt",
          email: "bob@example.test",
          phone: "+49 731 7654321",
          joined: "2025-06-04",
          source: ["store"],
        },
      },
      {
        key: "orders.1",
        table: "orders",
        values: {
          customer: [record("customers.alice")],
          ordered_at: currentMonthDate(3),
          status: ["delivered"],
          invoice_ready: false,
          invoice_sent: ["sent"],
        },
      },
      {
        key: "orders.2",
        table: "orders",
        values: {
          customer: [record("customers.bob")],
          ordered_at: currentMonthDate(8),
          status: ["shipped"],
          invoice_ready: false,
          invoice_sent: ["sent"],
        },
      },
      {
        key: "orders.3",
        table: "orders",
        values: {
          customer: [record("customers.alice")],
          ordered_at: currentMonthDate(13),
          status: ["new"],
          invoice_ready: true,
          invoice_sent: ["ready"],
        },
      },
      {
        key: "order_lines.1_hobbit",
        table: "order_lines",
        values: {
          order: [record("orders.1")],
          book: [record("books.hobbit")],
          quantity: "2",
          unit_price: "9.99",
        },
      },
      {
        key: "order_lines.1_left_hand",
        table: "order_lines",
        values: {
          order: [record("orders.1")],
          book: [record("books.left_hand")],
          quantity: "1",
          unit_price: "11.99",
        },
      },
      {
        key: "order_lines.2_abc",
        table: "order_lines",
        values: {
          order: [record("orders.2")],
          book: [record("books.abc")],
          quantity: "1",
          unit_price: "8.50",
        },
      },
      {
        key: "order_lines.3_hobbit",
        table: "order_lines",
        values: {
          order: [record("orders.3")],
          book: [record("books.hobbit")],
          quantity: "1",
          unit_price: "9.99",
        },
      },
      {
        key: "order_lines.3_left_hand",
        table: "order_lines",
        values: {
          order: [record("orders.3")],
          book: [record("books.left_hand")],
          quantity: "3",
          unit_price: "11.99",
        },
      },
    ],
    views: [
      {
        key: "recent_books",
        table: "books",
        name: t.recentBooks,
        shared: true,
        source: formula(
          "from table ",
          table("books"),
          "\nselect ",
          field("books.title"),
          ", ",
          field("books.isbn"),
          ", ",
          field("books.author"),
          ", ",
          field("books.price"),
          ", ",
          field("books.published"),
          "\nsort ",
          field("books.published"),
          " desc\nlimit 20",
        ),
        ui: {
          columns: [
            { fieldId: field("books.title") },
            {
              fieldId: field("books.isbn"),
              format: { kind: "barcode", bcid: "isbn", showText: true },
            },
            { fieldId: field("books.author") },
            { fieldId: field("books.price") },
            { fieldId: field("books.published") },
          ],
          displayConfig: {
            mode: "cards",
            cards: {
              imageFieldId: field("books.cover"),
              fieldIds: [field("books.title"), field("books.author"), field("books.genre"), field("books.price"), field("books.published")],
            },
          },
        },
      },
      {
        key: "order_calendar",
        table: "orders",
        name: t.orderCalendar,
        shared: true,
        source: formula(
          "from table ",
          table("orders"),
          "\nselect ",
          field("orders.order_no"),
          ", ",
          field("orders.ordered_at"),
          ", ",
          field("orders.customer"),
          ", ",
          field("orders.status"),
          ", ",
          field("orders.invoice_ready"),
          ", ",
          field("orders.invoice_sent"),
          "\nsort ",
          field("orders.ordered_at"),
          " asc\nlimit 100",
        ),
        ui: {
          columns: [
            { fieldId: field("orders.order_no") },
            { fieldId: field("orders.ordered_at") },
            { fieldId: field("orders.customer") },
            { fieldId: field("orders.status") },
            { fieldId: field("orders.invoice_ready") },
            { fieldId: field("orders.invoice_sent") },
          ],
          displayConfig: {
            mode: "calendar",
            calendar: { dateFieldId: field("orders.ordered_at") },
          },
        },
      },
    ],
    forms: [
      {
        key: "add_book",
        table: "books",
        name: t.addBook,
        config: {
          title: t.addBook,
          submitLabel: t.addBook,
          successMessage: t.bookAdded,
          fields: [
            {
              kind: "user_input",
              fieldId: field("books.title"),
              label: t.title,
              helpText: t.titleHelp,
              required: true,
            },
            {
              kind: "user_input",
              fieldId: field("books.author"),
              label: t.author,
              helpText: t.authorHelp,
              required: true,
              inlineCreate: {
                enabled: true,
                fields: [
                  {
                    fieldId: field("authors.name"),
                    label: t.authorName,
                    helpText: t.authorNameHelp,
                    required: true,
                  },
                  {
                    fieldId: field("authors.country"),
                    label: t.country,
                    helpText: t.countryHelp,
                  },
                  {
                    fieldId: field("authors.birth_year"),
                    label: t.birthYear,
                    helpText: t.birthYearHelp,
                  },
                ],
              },
            },
            {
              kind: "user_input",
              fieldId: field("books.isbn"),
              label: "ISBN",
              helpText: t.isbnHelp,
            },
            {
              kind: "user_input",
              fieldId: field("books.genre"),
              label: t.genre,
              helpText: t.genreHelp,
              required: true,
              inlineCreate: {
                enabled: true,
                fields: [
                  {
                    fieldId: field("genres.name"),
                    label: t.genreName,
                    helpText: t.genreNameHelp,
                    required: true,
                  },
                  {
                    fieldId: field("genres.description"),
                    label: t.description,
                    helpText: t.genreDescriptionHelp,
                  },
                ],
              },
            },
            {
              kind: "user_input",
              fieldId: field("books.price"),
              label: t.price,
              helpText: t.priceDescription,
              required: true,
            },
            {
              kind: "user_input",
              fieldId: field("books.pages"),
              label: t.pages,
              helpText: t.pagesHelp,
            },
            {
              kind: "user_input",
              fieldId: field("books.published"),
              label: t.published,
              helpText: t.publishedDescription,
            },
            {
              kind: "user_input",
              fieldId: field("books.tags"),
              label: t.tags,
              helpText: t.tagsHelp,
            },
            {
              kind: "user_input",
              fieldId: field("books.score"),
              label: t.score,
              helpText: t.scoreDescription,
            },
            {
              kind: "user_input",
              fieldId: field("books.description"),
              label: t.description,
              helpText: t.bookDescriptionDescription,
            },
            { kind: "form_value", fieldId: field("books.in_stock"), value: true },
          ],
        },
      },
      {
        key: "new_order",
        table: "orders",
        name: t.newOrder,
        config: {
          title: t.newOrder,
          submitLabel: t.createOrder,
          successMessage: t.orderCreated,
          fields: [
            {
              kind: "user_input",
              fieldId: field("orders.customer"),
              label: t.customer,
              helpText: t.customerHelp,
              required: true,
              inlineCreate: {
                enabled: true,
                fields: [
                  {
                    fieldId: field("customers.name"),
                    label: t.customerName,
                    helpText: t.customerNameHelp,
                    required: true,
                  },
                  {
                    fieldId: field("customers.email"),
                    label: t.email,
                    helpText: t.emailHelp,
                    required: true,
                  },
                  {
                    fieldId: field("customers.phone"),
                    label: t.phone,
                    helpText: t.phoneDescription,
                  },
                ],
              },
            },
            {
              kind: "user_input",
              fieldId: field("orders.ordered_at"),
              label: t.orderedAt,
              helpText: t.orderedAtHelp,
              required: true,
            },
            {
              kind: "form_value",
              fieldId: field("orders.status"),
              value: ["new"],
            },
            {
              kind: "form_value",
              fieldId: field("orders.invoice_ready"),
              value: false,
            },
            {
              kind: "form_value",
              fieldId: field("orders.invoice_sent"),
              value: ["ready"],
            },
          ],
        },
      },
      {
        key: "add_order_line",
        table: "order_lines",
        name: t.addOrderLine,
        config: {
          title: t.addOrderLine,
          description: t.addOrderLineDescription,
          submitLabel: t.addLine,
          successMessage: t.orderLineAdded,
          fields: [
            {
              kind: "user_input",
              fieldId: field("order_lines.order"),
              label: t.order,
              helpText: t.orderHelp,
              required: true,
            },
            {
              kind: "user_input",
              fieldId: field("order_lines.book"),
              label: t.book,
              helpText: t.bookHelp,
              required: true,
            },
            {
              kind: "user_input",
              fieldId: field("order_lines.quantity"),
              label: t.quantity,
              helpText: t.quantityHelp,
              required: true,
              defaultValue: "1",
            },
            {
              kind: "user_input",
              fieldId: field("order_lines.unit_price"),
              label: t.unitPrice,
              helpText: t.unitPriceHelp,
              required: true,
            },
          ],
        },
      },
    ],
    documentTemplates: [
      {
        key: "order_invoice",
        table: "orders",
        starterId: "invoice",
        name: t.orderInvoice,
        description: t.orderInvoiceDescription,
        source: formula(
          "from table ",
          table("order_lines"),
          " as line\njoin table ",
          table("orders"),
          " as order on line.",
          field("order_lines.order"),
          " = order.id",
          "\nselect ",
          "order.",
          field("orders.order_no"),
          " as invoice_number, ",
          "order.",
          field("orders.customer_name"),
          " as recipient_name, ",
          "order.",
          field("orders.customer_email"),
          " as recipient_email, ",
          "line.",
          field("order_lines.book_title"),
          " as invoice_item, ",
          "line.",
          field("order_lines.quantity"),
          " as invoice_quantity, ",
          "line.",
          field("order_lines.unit_price"),
          " as invoice_unit_price, ",
          "line.",
          field("order_lines.line_total"),
          " as invoice_line_total, ",
          "order.",
          field("orders.ordered_at"),
          " as invoice_date, ",
          "order.",
          field("orders.status"),
          "\nwhere ",
          field("order_lines.order"),
          " = '{{ record.id }}'\nsort line.",
          field("order_lines.line_no"),
          " asc",
        ),
        enabled: true,
      },
    ],
    emailTemplates: [
      {
        key: "order_invoice_ready",
        name: t.orderInvoiceReady,
        description: t.orderInvoiceReadyDescription,
        subject: t.invoiceSubject,
        html: t.invoiceEmailHtml,
        sampleData: {
          customerName: "Ada Lovelace",
          orderNumber: "ORD-2026-0042",
          invoice: {
            url: "https://cloud.example.org/share/grids/documents/example",
          },
        },
        enabled: true,
      },
    ],
    workflows: [
      {
        key: "send_order_invoice",
        name: t.sendOrderInvoice,
        description: t.sendOrderInvoiceDescription,
        source: `inputs:
  order:
    type: record
    table: ${t.orders}
    label: ${t.order}
    required: true
steps:
  - if:
      notEquals:
        - \${{ inputs.order.${t.invoiceSent} }}
        - [ready]
    then:
      - fail:
          message: ${t.invoiceAlreadySent}
  - if:
      not:
        exists: inputs.order.${t.customerEmail}
    then:
      - fail:
          message: ${t.addCustomerEmail}
  - if:
      endsWith:
        - \${{ inputs.order.${t.customerEmail} }}
        - .test
    then:
      - fail:
          message: ${t.replaceSampleEmail}
  - if:
      notEquals:
        - \${{ inputs.order.${t.readyToInvoice} }}
        - true
    then:
      - fail:
          message: ${t.completeOrderLines}
  - atomicRecords:
      locks: [inputs.order]
      checks:
        - table: ${t.orders}
          where:
            - field: ${t.orderNumber}
              op: equals
              value: \${{ inputs.order.${t.orderNumber} }}
            - field: ${t.invoiceSent}
              op: is
              value: ready
            - field: ${t.readyToInvoice}
              op: '='
              value: true
          assert: notEmpty
          message: ${t.invoiceAlreadySent}
      changes:
        - updateRecord:
            record: inputs.order
            set:
              ${t.invoiceSent}: [processing]
  - generateDocument:
      template: ${t.orderInvoice}
      record: inputs.order
      saveAs: invoicePdf
  - createDocumentLink:
      document: invoicePdf
      expiresIn: 30d
      saveAs: invoiceLink
  - sendEmail:
      template: ${t.orderInvoiceReady}
      to:
        - email: \${{ inputs.order.${t.customerEmail} }}
      data:
        invoice: \${{ invoiceLink }}
        orderNumber: \${{ inputs.order.${t.orderNumber} }}
        customerName: \${{ inputs.order.${t.customerName} }}
  - updateRecord:
      record: inputs.order
      set:
        ${t.readyToInvoice}: false
        ${t.invoiceSent}: [sent]
  - succeed:
      message: "${t.invoiceSentMessage({
        orderNumber: `\${{ inputs.order.${t.orderNumber} }}`,
        customerEmail: `\${{ inputs.order.${t.customerEmail} }}`,
      })}"`,
        enabled: true,
      },
    ],
    workflowLaunchers: [
      {
        key: "send_order_invoice_custom_app",
        workflow: "send_order_invoice",
        name: t.chooseOrderToSendInvoice,
        config: { kind: "customApp", inputMode: "prompt" },
        enabled: true,
      },
    ],
    customApps: [
      {
        key: "sales",
        definition: {
          schemaVersion: 5,
          kind: "grids.custom-app",
          name: t.bookshopOverview,
          startPageId: "overview",
          pages: [
            {
              id: "overview",
              title: t.bookshopOverview,
              navigation: {
                visible: true,
              },
              parameters: {},
              rows: [
                {
                  id: "r-stats",
                  columns: [
                    {
                      id: "w-orders-column",
                      span: 4,
                      blocks: [
                        {
                          id: "w-orders",
                          type: "metrics",
                          title: t.orders,
                          source: {
                            kind: "gql",
                            query: formula("from table ", table("orders"), "\naggregate count(*) as order_count"),
                          },
                        },
                      ],
                    },
                    {
                      id: "w-revenue-column",
                      span: 4,
                      blocks: [
                        {
                          id: "w-revenue",
                          type: "metrics",
                          title: t.totalRevenue,
                          source: {
                            kind: "gql",
                            query: formula(
                              "from table ",
                              table("order_lines"),
                              "\naggregate sum(formula(",
                              field("order_lines.quantity"),
                              " * ",
                              field("order_lines.unit_price"),
                              ")) as total_revenue",
                            ),
                          },
                        },
                      ],
                    },
                    {
                      id: "w-books-column",
                      span: 4,
                      blocks: [
                        {
                          id: "w-books",
                          type: "metrics",
                          title: t.books,
                          source: {
                            kind: "gql",
                            query: formula("from table ", table("books"), "\naggregate count(*) as book_count"),
                          },
                        },
                      ],
                    },
                  ],
                },
                {
                  id: "r-main",
                  columns: [
                    {
                      id: "w-chart-column",
                      span: 6,
                      blocks: [
                        {
                          id: "w-chart",
                          type: "chart",
                          title: t.monthlyRevenue,
                          chartType: "line",
                          source: {
                            kind: "gql",
                            query: formula(
                              "from table ",
                              table("order_lines"),
                              " as line\njoin table ",
                              table("orders"),
                              " as order on line.",
                              field("order_lines.order"),
                              " = order.id\ngroup by order.",
                              field("orders.ordered_at"),
                              " by month\naggregate sum(formula(",
                              "line.",
                              field("order_lines.quantity"),
                              " * line.",
                              field("order_lines.unit_price"),
                              ")) as monthly_revenue, count(*) as order_line_count\nsort ",
                              "order.",
                              field("orders.ordered_at"),
                              " asc",
                            ),
                          },
                          valueFormat: {
                            style: "number",
                            decimalPlaces: 2,
                            unit: "EUR",
                            unitPosition: "suffix",
                          },
                          limit: 100,
                        },
                      ],
                    },
                    {
                      id: "w-new-order-column",
                      span: 3,
                      blocks: [
                        {
                          id: "w-new-order",
                          type: "form",
                          title: t.newOrder,
                          formId: form("new_order"),
                          fixedValues: {},
                          onSuccessNavigate: {
                            kind: "navigate",
                            pageId: "order",
                            params: { order_id: { source: "RESULT", path: "recordId" } },
                          },
                        },
                      ],
                    },
                    {
                      id: "w-add-order-line-column",
                      span: 3,
                      blocks: [
                        {
                          id: "w-add-order-line",
                          type: "form",
                          title: t.addOrderLine,
                          formId: form("add_order_line"),
                          fixedValues: {},
                        },
                      ],
                    },
                  ],
                },
                {
                  id: "r-views",
                  columns: [
                    {
                      id: "w-add-book-column",
                      span: 6,
                      blocks: [
                        {
                          id: "w-add-book",
                          type: "form",
                          title: t.addBook,
                          formId: form("add_book"),
                          fixedValues: {},
                        },
                      ],
                    },
                    {
                      id: "w-recent-column",
                      span: 6,
                      blocks: [
                        {
                          id: "w-recent",
                          type: "records",
                          searchable: true,
                          pageSize: 25,
                          title: t.recentBooks,
                          source: { kind: "view", viewId: view("recent_books") },
                          display: {
                            kind: "table",
                            columnIds: viewColumns("recent_books"),
                          },
                        },
                      ],
                    },
                  ],
                },
                {
                  id: "r-fulfillment",
                  columns: [
                    {
                      id: "w-revenue-by-customer-column",
                      span: 7,
                      blocks: [
                        {
                          id: "w-revenue-by-customer",
                          type: "chart",
                          title: t.revenueByCustomer,
                          subtitle: t.revenueByCustomerSubtitle,
                          chartType: "bar",
                          source: {
                            kind: "gql",
                            query: formula(
                              "from table ",
                              table("order_lines"),
                              " as line\njoin table ",
                              table("orders"),
                              " as order on line.",
                              field("order_lines.order"),
                              " = order.id\njoin table ",
                              table("customers"),
                              " as customer on order.",
                              field("orders.customer"),
                              " = customer.id\ngroup by customer.",
                              field("customers.name"),
                              "\naggregate sum(formula(",
                              "line.",
                              field("order_lines.quantity"),
                              " * line.",
                              field("order_lines.unit_price"),
                              ")) as customer_revenue\nhaving customer_revenue > 0\nsort customer_revenue desc nulls last\nlimit 8",
                            ),
                          },
                          valueFormat: {
                            style: "number",
                            decimalPlaces: 2,
                            unit: "EUR",
                            unitPosition: "suffix",
                          },
                          limit: 100,
                        },
                      ],
                    },
                    {
                      id: "w-send-invoice-column",
                      span: 5,
                      blocks: [
                        {
                          id: "w-invoice-orders",
                          type: "records",
                          title: t.orders,
                          source: { kind: "view", viewId: view("order_calendar") },
                          display: {
                            kind: "table",
                            columnIds: viewColumns("order_calendar"),
                          },
                          searchable: true,
                          pageSize: 25,
                          rowActions: [
                            {
                              id: "send-invoice",
                              label: t.sendInvoice,
                              showLabel: true,
                              kind: "workflow",
                              launcherId: launcher("send_order_invoice_custom_app"),
                              inputs: { order: { source: "ROW", path: "id" } },
                            },
                          ],
                          rowNavigate: {
                            history: "push",
                            kind: "navigate",
                            pageId: "order",
                            params: { order_id: { source: "ROW", path: "id" } },
                          },
                        },
                      ],
                    },
                  ],
                },
              ],
            },
            {
              id: "order",
              title: t.order,
              navigation: { visible: false },
              parameters: { order_id: { type: "record", tableId: table("orders"), required: true } },
              record: { tableId: table("orders"), id: { source: "PARAMS", path: "order_id" } },
              rows: [
                {
                  id: "detail",
                  columns: [
                    {
                      id: "content",
                      span: 12,
                      blocks: [
                        { id: "instructions", type: "markdown", markdown: t.orderJourney },
                        {
                          id: "order",
                          type: "record",
                          title: t.order,
                          fieldIds: [
                            field("orders.order_no"),
                            field("orders.customer"),
                            field("orders.customer_email"),
                            field("orders.ordered_at"),
                            field("orders.status"),
                            field("orders.invoice_ready"),
                            field("orders.invoice_sent"),
                          ],
                          editableFieldIds: [field("orders.status"), field("orders.invoice_ready")],
                          documents: { templateIds: [documentTemplate("order_invoice")] },
                        },
                        {
                          id: "lines",
                          type: "referenced_records",
                          title: t.orderLines,
                          sourceTableId: table("order_lines"),
                          relationFieldId: field("order_lines.order"),
                          fieldIds: [
                            field("order_lines.line_no"),
                            field("order_lines.book"),
                            field("order_lines.quantity"),
                            field("order_lines.unit_price"),
                            field("order_lines.line_total"),
                          ],
                          display: { kind: "table" },
                          searchable: true,
                          pageSize: 25,
                          rowActions: [],
                        },
                        {
                          id: "actions",
                          type: "actions",
                          actions: [
                            {
                              id: "send-invoice",
                              kind: "workflow",
                              label: t.sendInvoice,
                              launcherId: launcher("send_order_invoice_custom_app"),
                              inputs: { order: { source: "RECORD", path: "id" } },
                              availableWhen: {
                                query: formula(
                                  "from table ",
                                  table("orders"),
                                  "\nwhere record.id = @params.order_id and ",
                                  field("orders.invoice_ready"),
                                  " = true and ",
                                  field("orders.invoice_sent"),
                                  " = 'ready'\nlimit 1",
                                ),
                              },
                            },
                          ],
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
      },
    ],
  };
};

export const bookshopTemplate: GridTemplate = createBookshopTemplate("en");
