/**
 * Core platform API surface — owned by cloud-lib, mounted by the core-app.
 *
 * Lives here (not in an app) because every container shares the same auth
 * model, self-service shape, lifecycle controls and entity search; redefining
 * any of these per-app would break the platform invariant.
 *
 * Apps that need a typed client to these routes import from
 * `@k2b/cloud/clients/core`. The client and the routes share their
 * type via `CoreApiType` below.
 *
 * The OpenAPI spec for these routes is generated by `defineApp` (driven by
 * core's `openapi: "/api/openapi.json"` opt-in) — this file no longer mounts
 * any docs UI; the api-docs aggregator at `/app/api-docs` is the only consumer.
 */
import { Hono } from "hono";
import { prettyJSON } from "hono/pretty-json";
import { createAiApprovalPreferenceRoutes } from "../ai/approval-routes";
import { aiProjectsRoutes } from "../ai/projects-routes";
import { aiRoutes } from "../ai/routes";
import { aiSkillsRoutes } from "../ai/skills-routes";
import accountsEntitiesRoutes from "./accounts-entities";
import adminAiUsageRoutes from "./admin-ai-usage";
import adminAiProjectsRoutes from "./admin-ai-projects";
import adminAiSkillsRoutes from "./admin-ai-skills";
import adminCoreSettingsRoutes from "./admin-core-settings";
import adminIdentityRoutes from "./admin-identity";
import adminLifecycleRoutes from "./admin-lifecycle";
import adminLinuxIdentityRoutes from "./admin-linux-identities";
import { adminAnnouncementRoutes, announcementRoutes } from "./announcements";
import { appDiscoveryRoutes } from "./apps";
import { createAuthRoutes } from "./auth";
import { createAppApprovalRoutes } from "./app-approval";
import { createCapabilityRoutes } from "./capabilities";
import { createHelpRoutes } from "./help";
import { createMcpRoutes } from "./mcp";
import meRoutes from "./me";
import { createSearchRoutes } from "./search";
import { createSyncOpsProxyRoutes } from "./sync-ops";
import { createWidgetRoutes } from "./widgets";

export { type CapabilityDispatchDependencies, dispatchCapability } from "./capabilities";

/**
 * Single-expression chain so `typeof buildCoreApi()` captures every route's
 * input/output. Splitting into `new Hono()` + `.route(...)` calls would erase
 * the typed shape for the client.
 */
export type CoreApiOptions = {
  notifications: import("../services/auth-flows/notification-sender").AuthNotificationSender;
};

const buildCoreApi = (options: CoreApiOptions) => {
  const searchRoutes = createSearchRoutes();
  const capabilityRoutes = createCapabilityRoutes();
  const mcpRoutes = createMcpRoutes();
  const helpRoutes = createHelpRoutes();
  const approvalPreferenceRoutes = createAiApprovalPreferenceRoutes();
  const widgetRoutes = createWidgetRoutes();
  return new Hono()
    .use(prettyJSON())
    .route("/auth/app-approval/v1", createAppApprovalRoutes())
    .route("/auth", createAuthRoutes(options.notifications))
    .route("/me", meRoutes)
    .route("/accounts", accountsEntitiesRoutes)
    .route("/apps", appDiscoveryRoutes)
    .route("/announcements", announcementRoutes)
    .route("/admin/core/ai-usage", adminAiUsageRoutes)
    .route("/admin/core/ai-projects", adminAiProjectsRoutes)
    .route("/admin/core/ai-skills", adminAiSkillsRoutes)
    .route("/admin/core/announcements", adminAnnouncementRoutes)
    .route("/admin/core/settings", adminCoreSettingsRoutes)
    .route("/admin/core/linux-identities", adminLinuxIdentityRoutes)
    .route("/admin/identity", adminIdentityRoutes)
    .route("/admin/sync", createSyncOpsProxyRoutes())
    .route("/admin/lifecycle", adminLifecycleRoutes)
    .route("/ai/approval-preferences", approvalPreferenceRoutes)
    .route("/ai/projects", aiProjectsRoutes)
    .route("/ai/skills", aiSkillsRoutes)
    .route("/ai", aiRoutes)
    .route("/", helpRoutes)
    .route("/", capabilityRoutes)
    .route("/", mcpRoutes)
    .route("/", widgetRoutes)
    .route("/", searchRoutes);
};

/** Type of the entire core HTTP surface — consumed by the client builder. */
export type CoreApiType = ReturnType<typeof buildCoreApi>;

/**
 * Build the core router. The core-app calls this and mounts the returned
 * router under `/api`.
 */
export const createCoreApiRouter = (options: CoreApiOptions) => {
  const api = buildCoreApi(options);
  api.all("/*", (c) => c.json({ message: "API route not found" }, 404));
  return { api };
};

export {
  CLOUD_MCP_PATH,
  CLOUD_MCP_PROTECTED_RESOURCE_PATH,
  cloudMcpResourceUri,
  createMcpProtectedResourceRoutes,
  createMcpRoutes,
  publicCloudOrigin,
} from "./mcp";
