import { chmod, mkdir, readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { nkeys } from "@nats-io/transport-node";

/** Prepare local system-account credentials without moving existing $G data. */
export async function prepareDevNats(directory = fileURLToPath(new URL("../../../.local/nats/", import.meta.url))) {
  await mkdir(directory, { recursive: true, mode: 0o700 });
  const seedPath = `${directory}/admin.seed`;
  let seed: Uint8Array;
  try {
    seed = await readFile(seedPath);
  } catch (error) {
    if (!(error instanceof Error) || !("code" in error) || error.code !== "ENOENT") throw error;
    const key = nkeys.createUser();
    try {
      seed = new Uint8Array(key.getSeed());
      await writeFile(seedPath, seed, { mode: 0o600, flag: "wx" });
    } finally {
      key.clear();
    }
  }
  await chmod(seedPath, 0o600);
  const key = nkeys.fromSeed(seed);
  try {
    const publicKey = key.getPublicKey();
    if (!publicKey.startsWith("U")) throw new Error("Local NATS admin.seed must contain a user NKey.");
    await writeFile(
      `${directory}/system.conf`,
      [
        "# Generated by bun run dev:infra. Application data stays in the global $G account.",
        "no_auth_user: dev",
        "authorization { users: [{ user: dev }] }",
        'system_account: "$SYS"',
        `accounts { "$SYS" { users: [{ nkey: "${publicKey}" }] } }`,
        "",
      ].join("\n"),
    );
  } finally {
    key.clear();
    seed.fill(0);
  }
}

if (import.meta.main) {
  await prepareDevNats();
  console.log("Local NATS system-account configuration prepared.");
}
