import { chmod, mkdir, readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { nkeys } from "@nats-io/transport-node";

/**
 * JetStream limits of the TEST account. JetStream reserves the full
 * `max_bytes` of a stream against its account, 1 GiB per Sync topic, queue,
 * job, and dead-letter stream, so the file limit bounds reservations, not
 * data: a full integration run stores under 3 MiB but reserves up to 10 GiB
 * at once (the Pulse runtime Sync test). 20 GiB holds one run plus the
 * streams a killed test process leaves behind until the one-hour sweep in
 * `scripts/fixtures/test-sync.ts` deletes them. Tests keep a few KiB in
 * memory streams; 16 MiB admits one message of the server's `max_payload`.
 */
const testJetStream = "{ max_file: 20GB, max_mem: 16MB }";

/** Reads a persistent user NKey seed, creating it once; an existing seed is never rotated. */
const userSeed = async (path: string): Promise<Uint8Array> => {
  let seed: Uint8Array;
  try {
    seed = await readFile(path);
  } catch (error) {
    if (!(error instanceof Error) || !("code" in error) || error.code !== "ENOENT") throw error;
    const key = nkeys.createUser();
    try {
      seed = new Uint8Array(key.getSeed());
      await writeFile(path, seed, { mode: 0o600, flag: "wx" });
    } finally {
      key.clear();
    }
  }
  await chmod(path, 0o600);
  return seed;
};

const publicUserKey = (seed: Uint8Array, name: string): string => {
  const key = nkeys.fromSeed(seed);
  try {
    const publicKey = key.getPublicKey();
    if (!publicKey.startsWith("U")) throw new Error(`Local NATS ${name} must contain a user NKey.`);
    return publicKey;
  } finally {
    key.clear();
  }
};

const encoder = new TextEncoder();

/**
 * A `.creds` file for a configured NKey user. The server runs without an
 * operator, so it discards the JWT block and authenticates the seed.
 */
const credsFile = (seed: Uint8Array): Uint8Array => {
  const head = encoder.encode(
    [
      "# Local NATS test identity, generated by bun run dev from test.seed.",
      "-----BEGIN NATS USER JWT-----",
      "unused-without-operator",
      "------END NATS USER JWT------",
      "",
      "-----BEGIN USER NKEY SEED-----",
      "",
    ].join("\n"),
  );
  const tail = encoder.encode("\n------END USER NKEY SEED------\n");
  const creds = new Uint8Array(head.length + seed.length + tail.length);
  creds.set(head);
  creds.set(seed, head.length);
  creds.set(tail, head.length + seed.length);
  return creds;
};

/**
 * Prepare the local NATS accounts. Applications connect without credentials
 * and use DEV; integration tests authenticate with `test.creds` and use the
 * bounded TEST account; diagnostics use `$SYS`. Tests reach TEST through
 * `NATS_CREDS_FILE`, the mechanism a deployment uses.
 */
export async function prepareDevNats(directory = fileURLToPath(new URL("../../../.local/nats/", import.meta.url))) {
  await mkdir(directory, { recursive: true, mode: 0o700 });
  const adminSeed = await userSeed(`${directory}/admin.seed`);
  const testSeed = await userSeed(`${directory}/test.seed`);
  const creds = credsFile(testSeed);
  try {
    const adminKey = publicUserKey(adminSeed, "admin.seed");
    const testKey = publicUserKey(testSeed, "test.seed");
    await writeFile(`${directory}/test.creds`, creds, { mode: 0o600 });
    await chmod(`${directory}/test.creds`, 0o600);
    await writeFile(
      `${directory}/system.conf`,
      [
        "# Generated by bun run dev. Applications connect without credentials and use DEV;",
        "# integration tests authenticate with test.creds and use the bounded TEST account.",
        "no_auth_user: dev",
        'system_account: "$SYS"',
        "accounts {",
        `  "$SYS" { users: [{ nkey: "${adminKey}" }] }`,
        "  DEV { users: [{ user: dev }], jetstream: enabled }",
        `  TEST { users: [{ nkey: "${testKey}" }], jetstream: ${testJetStream} }`,
        "}",
        "",
      ].join("\n"),
    );
  } finally {
    adminSeed.fill(0);
    testSeed.fill(0);
    creds.fill(0);
  }
}

if (import.meta.main) {
  await prepareDevNats();
  console.log("Local NATS accounts prepared.");
}
