import { describe, expect, test } from "bun:test";
import type { PublicDocument } from "../documents/public-document-types";
import { mergeRefreshedWorkflowRunDocuments } from "./workflow-run-documents";

const document = (id: string): PublicDocument => ({
  id,
  baseId: "base001",
  tableId: "table01",
  recordId: "record1",
  templateId: "templ001",
  number: `DOC-${id}`,
  filename: `${id}.pdf`,
  createdAt: "2026-08-23T00:00:00.000Z",
  tags: [],
  createdBy: null,
  renderer: { kind: "html" },
  validationStatus: null,
  artifacts: [
    {
      key: "pdf",
      filename: `${id}.pdf`,
      mimeType: "application/pdf",
      sizeBytes: 1,
      sha256: "a".repeat(64),
    },
  ],
});

describe("mergeRefreshedWorkflowRunDocuments", () => {
  test("preserves loaded pages while prepending documents generated by an active run", () => {
    expect(
      mergeRefreshedWorkflowRunDocuments(
        {
          items: [document("old-1"), document("old-2"), document("old-3")],
          total: 4,
          hasMore: true,
          nextOffset: 3,
        },
        {
          items: [document("new"), document("old-1"), document("old-2")],
          total: 5,
          hasMore: true,
          nextOffset: 3,
        },
      ),
    ).toEqual({
      items: [document("new"), document("old-1"), document("old-2"), document("old-3")],
      total: 5,
      hasMore: true,
      nextOffset: 4,
    });
  });

  test("uses the refreshed first page when no additional page is loaded", () => {
    const refreshed = { items: [document("new")], total: 1, hasMore: false, nextOffset: null };
    expect(mergeRefreshedWorkflowRunDocuments({ items: [], total: 0, hasMore: false, nextOffset: null }, refreshed)).toBe(refreshed);
  });
});
