import type { SelectGroup } from "./Select";
import type { IconOption } from "./SpecialInputs";

export const DEFAULT_ICON_GROUPS = [
  { value: "recommended", label: "Recommended" },
  { value: "people", label: "People" },
  { value: "work", label: "Work" },
  { value: "communication", label: "Communication" },
  { value: "files", label: "Files" },
  { value: "data", label: "Data & tech" },
  { value: "commerce", label: "Commerce" },
  { value: "places", label: "Places" },
  { value: "food", label: "Food" },
  { value: "media", label: "Media" },
  { value: "devices", label: "Devices" },
] as const satisfies readonly SelectGroup[];

type DefaultIconGroup = (typeof DEFAULT_ICON_GROUPS)[number]["value"];

const icon = (
  name: string,
  label: string,
  description: string,
  groups: readonly DefaultIconGroup[],
  keywords: readonly string[] = [],
): IconOption => ({
  value: `ti ti-${name}`,
  label,
  description,
  icon: `ti ti-${name}`,
  groups,
  keywords: [name, ...keywords],
});

/** A curated, application-neutral Tabler catalogue for IconInput. */
export const DEFAULT_ICON_OPTIONS: readonly IconOption[] = [
  icon("activity", "Activity", "Live activity or health signals", ["recommended", "data"], ["pulse", "monitor"]),
  icon("adjustments", "Adjustments", "Tune settings or controls", ["recommended", "work"], ["settings", "controls"]),
  icon("alert-circle", "Alert", "Important warning or problem", ["recommended", "work"], ["warning", "error"]),
  icon("archive", "Archive", "Stored or inactive material", ["recommended", "files", "work"], ["box", "storage"]),
  icon("bell", "Bell", "Notifications and reminders", ["recommended", "communication"], ["notification", "reminder"]),
  icon("book", "Book", "Reading, knowledge, or a library", ["recommended", "files"], ["docs", "read", "library"]),
  icon("bookmark", "Bookmark", "Saved content for later", ["recommended", "files"], ["save", "favorite"]),
  icon("box", "Box", "A product, package, or container", ["recommended", "commerce", "work"], ["package", "inventory"]),
  icon("briefcase", "Briefcase", "Business, a job, or a project", ["recommended", "work"], ["business", "job"]),
  icon("building", "Building", "An organization or office", ["recommended", "work", "places"], ["company", "office"]),
  icon("calendar", "Calendar", "Dates, plans, and schedules", ["recommended", "work"], ["date", "schedule"]),
  icon("camera", "Camera", "Photography or image capture", ["recommended", "media", "devices"], ["photo", "image"]),
  icon("chart-bar", "Bar chart", "Compare values across categories", ["recommended", "data", "work"], ["analytics", "stats"]),
  icon("chart-line", "Line chart", "Show a trend over time", ["recommended", "data", "work"], ["analytics", "trend"]),
  icon("check", "Check", "A completed or confirmed action", ["recommended", "work"], ["done", "success"]),
  icon("circle-check", "Check circle", "Successful or approved status", ["recommended", "work"], ["done", "success", "approved"]),
  icon("clock", "Clock", "Time, duration, or a deadline", ["recommended", "work"], ["time", "schedule"]),
  icon("cloud", "Cloud", "Hosted or synchronized services", ["recommended", "data"], ["hosting", "online", "sync"]),
  icon("heart", "Heart", "A favorite, like, or health topic", ["recommended", "people"], ["favorite", "health", "love"]),
  icon("home", "Home", "A home page or physical home", ["recommended", "places"], ["start", "house"]),
  icon("layout-dashboard", "Dashboard", "An overview or control center", ["recommended", "data", "work"], ["layout", "overview"]),
  icon("search", "Search", "Find content or records", ["recommended", "work", "data"], ["find", "lookup"]),
  icon("settings", "Settings", "Configuration and preferences", ["recommended", "work"], ["configure", "preferences"]),
  icon("sparkles", "Sparkles", "AI, magic, or something new", ["recommended", "data", "media"], ["ai", "magic", "new"]),
  icon("star", "Star", "A favorite, rating, or highlight", ["recommended", "work"], ["favorite", "rating"]),
  icon("tag", "Tag", "A label or category", ["recommended", "files", "work"], ["label", "category"]),
  icon("cube", "Cube", "A module, object, or component", ["recommended", "data", "work"], ["package", "component"]),
  icon("download", "Download", "Save or export a file", ["recommended", "files", "data"], ["save", "export"]),
  icon("external-link", "External link", "Open a different page or website", ["recommended", "communication", "data"], ["open", "new tab"]),
  icon("eye", "Eye", "View, preview, or visibility", ["recommended", "work", "media"], ["view", "preview"]),
  icon("help-circle", "Help", "Help, support, or a question", ["recommended", "communication"], ["question", "support"]),
  icon("info-circle", "Info", "Additional information or guidance", ["recommended", "communication"], ["information", "help"]),
  icon("key", "Key", "Access, credentials, or security", ["recommended", "work", "data"], ["access", "security"]),
  icon("link", "Link", "A URL or connection", ["recommended", "communication", "data"], ["url", "connection"]),
  icon("list", "List", "A sequence of items or rows", ["recommended", "work", "files"], ["items", "rows"]),
  icon("lock", "Lock", "Private or protected content", ["recommended", "work", "data"], ["security", "private"]),
  icon("package", "Package", "A shipped item or software module", ["recommended", "commerce", "data"], ["box", "module"]),
  icon("plus", "Plus", "Add or create something", ["recommended", "work"], ["add", "create"]),
  icon("shield", "Shield", "Security or protection", ["recommended", "work", "data"], ["security", "protection"]),
  icon("trash", "Trash", "Delete or remove something", ["recommended", "work", "files"], ["delete", "remove"]),
  icon("upload", "Upload", "Import or send a file", ["recommended", "files", "data"], ["import", "file"]),
  icon("x", "Close", "Close, cancel, or remove", ["recommended", "work"], ["cancel", "remove"]),

  icon("address-book", "Address book", "Saved people and contact details", ["people", "communication"], ["contacts", "directory"]),
  icon("friends", "Friends", "Friends or a social circle", ["people", "communication"], ["social", "group"]),
  icon("id", "ID card", "Identity or account details", ["people", "work"], ["identity", "badge"]),
  icon("mood-smile", "Smile", "Positive mood or feedback", ["people", "communication"], ["happy", "emoji"]),
  icon("user", "User", "One person or account", ["recommended", "people", "work"], ["person", "account"]),
  icon("user-check", "Verified user", "An approved or verified person", ["people", "work"], ["approved", "verified"]),
  icon("user-circle", "User profile", "A personal profile or avatar", ["people"], ["profile", "avatar"]),
  icon("user-plus", "Add user", "Invite or add a person", ["people", "work"], ["invite", "join"]),
  icon("users", "Users", "A group, team, or audience", ["recommended", "people", "work"], ["people", "team"]),

  icon("award", "Award", "An achievement or recognition", ["work", "people"], ["medal", "achievement"]),
  icon("building-store", "Store", "A shop or retail location", ["work", "commerce", "places"], ["shop", "retail"]),
  icon("clipboard", "Clipboard", "Copied content or a work item", ["work", "files"], ["copy", "paste"]),
  icon("clipboard-list", "Task list", "A checklist or set of tasks", ["work", "files"], ["todo", "checklist"]),
  icon("edit", "Edit", "Change existing content", ["recommended", "work", "files"], ["pencil", "change"]),
  icon("filter", "Filter", "Narrow a set of results", ["work", "data"], ["refine", "search"]),
  icon("flag", "Flag", "A marker, milestone, or report", ["work", "places"], ["marker", "milestone"]),
  icon("presentation", "Presentation", "Slides or a talk", ["work", "files", "media"], ["slides", "deck"]),
  icon("printer", "Printer", "Print a physical copy", ["work", "files", "devices"], ["print", "paper"]),
  icon("school", "School", "Education, training, or a campus", ["work", "people", "places"], ["education", "learning"]),
  icon("target", "Target", "A goal or objective", ["work", "data"], ["goal", "aim"]),
  icon("tool", "Tool", "Maintenance or practical work", ["recommended", "work"], ["build", "maintenance", "wrench"]),
  icon("trophy", "Trophy", "A win or major achievement", ["work", "people"], ["winner", "champion"]),

  icon("file", "File", "A generic file or document", ["recommended", "files"], ["document"]),
  icon("file-code", "Code file", "Source code or a script", ["files", "data"], ["source", "developer"]),
  icon("file-spreadsheet", "Spreadsheet", "Tabular data or a workbook", ["files", "data", "work"], ["excel", "sheet", "csv"]),
  icon("file-text", "Document", "Written text or documentation", ["recommended", "files", "work"], ["text", "docs"]),
  icon("files", "Files", "A collection of documents", ["files", "work"], ["documents", "multiple"]),
  icon("folder", "Folder", "A directory of files", ["recommended", "files", "work"], ["directory"]),
  icon("folder-open", "Open folder", "A currently open directory", ["files", "work"], ["directory", "browse"]),
  icon("note", "Note", "A short memo or annotation", ["recommended", "files", "work"], ["memo", "writing"]),
  icon("notebook", "Notebook", "Notes, a journal, or research", ["files", "work"], ["journal", "writing"]),
  icon("paperclip", "Attachment", "An attached file", ["files", "communication", "work"], ["attach", "paperclip"]),
  icon("pencil", "Pencil", "Writing or composing content", ["files", "work"], ["write", "compose"]),

  icon("api", "API", "An application programming interface", ["data"], ["endpoint", "service"]),
  icon("brand-github", "GitHub", "A GitHub repository or project", ["data", "work"], ["git", "repository", "code"]),
  icon("browser", "Browser", "A website or web browser", ["data", "devices"], ["web", "internet"]),
  icon("bug", "Bug", "A software issue or defect", ["data", "work"], ["error", "issue"]),
  icon("code", "Code", "Programming or source code", ["recommended", "data", "work"], ["source", "developer"]),
  icon("database", "Database", "Structured data storage", ["recommended", "data"], ["db", "storage"]),
  icon("git-branch", "Git branch", "A branch of source changes", ["data", "work"], ["repository", "fork"]),
  icon("network", "Network", "Connected systems or nodes", ["data", "devices"], ["connection", "graph"]),
  icon("robot", "Robot", "Automation, a bot, or AI", ["data", "work"], ["bot", "ai", "automation"]),
  icon("server", "Server", "A host or infrastructure service", ["recommended", "data", "devices"], ["host", "infrastructure"]),
  icon("table", "Table", "Rows and columns of data", ["data", "files", "work"], ["grid", "spreadsheet"]),
  icon("terminal", "Terminal", "A command line or shell", ["data", "devices"], ["console", "cli", "shell"]),
  icon("wifi", "Wi-Fi", "Wireless network access", ["data", "devices"], ["wireless", "internet"]),

  icon("at", "At sign", "A mention or email address", ["communication"], ["mention", "email"]),
  icon("mail", "Mail", "Email or written correspondence", ["recommended", "communication", "work"], ["email", "message"]),
  icon("mail-opened", "Opened mail", "A read or opened message", ["communication", "work"], ["email", "read"]),
  icon("message", "Message", "Chat or a conversation", ["recommended", "communication", "people"], ["chat", "comment"]),
  icon("messages", "Messages", "A conversation with several messages", ["communication", "people"], ["chat", "conversation"]),
  icon("microphone", "Microphone", "Voice input or audio recording", ["communication", "media", "devices"], ["audio", "voice", "record"]),
  icon("phone", "Phone", "A telephone call or contact number", ["communication", "people", "devices"], ["call", "telephone"]),
  icon("send", "Send", "Deliver a message or submission", ["recommended", "communication", "work"], ["submit", "deliver"]),
  icon("share", "Share", "Distribute content to others", ["communication", "people", "files"], ["send", "social"]),

  icon("building-bank", "Bank", "Banking or a financial institution", ["commerce", "work", "places"], ["finance", "money"]),
  icon("calculator", "Calculator", "Calculation or accounting", ["commerce", "data", "devices"], ["math", "compute"]),
  icon("cash", "Cash", "Physical money or a cash payment", ["commerce"], ["money", "banknote"]),
  icon("coin", "Coin", "Money, currency, or credits", ["recommended", "commerce"], ["money", "finance"]),
  icon("credit-card", "Credit card", "Card payments and billing", ["recommended", "commerce"], ["payment", "money"]),
  icon("currency-dollar", "Dollar", "Prices or amounts in dollars", ["commerce", "data"], ["currency", "money", "usd", "$"]),
  icon("currency-euro", "Euro", "Prices or amounts in euros", ["commerce", "data"], ["currency", "money", "eur", "€"]),
  icon("percentage", "Percentage", "A rate, share, or discount", ["commerce", "data"], ["percent", "discount", "%"]),
  icon("receipt", "Receipt", "A purchase, bill, or invoice", ["commerce", "files"], ["bill", "invoice"]),
  icon("shopping-bag", "Shopping bag", "Retail shopping or an order", ["commerce"], ["shop", "buy"]),
  icon("shopping-cart", "Shopping cart", "A basket of items to purchase", ["commerce"], ["shop", "purchase"]),
  icon("wallet", "Wallet", "Money, cards, or an account balance", ["commerce"], ["cash", "finance"]),

  icon("bike", "Bike", "Cycling or bicycle transport", ["places"], ["bicycle", "transport"]),
  icon("bus", "Bus", "Public road transport", ["places"], ["transport", "public"]),
  icon("car", "Car", "Driving or a road vehicle", ["places"], ["auto", "vehicle"]),
  icon("compass", "Compass", "Direction or navigation", ["places"], ["navigation", "direction"]),
  icon("map", "Map", "Geography or an area overview", ["places", "data"], ["location", "geography"]),
  icon("map-pin", "Map pin", "A specific place or address", ["recommended", "places"], ["location", "place"]),
  icon("mountain", "Mountain", "Nature, outdoors, or a peak", ["places"], ["outdoors", "nature"]),
  icon("plane", "Plane", "Air travel or a flight", ["places"], ["flight", "airplane"]),
  icon("rocket", "Rocket", "A launch, growth, or fast start", ["places", "work", "data"], ["launch", "space", "boost"]),
  icon("route", "Route", "A path, journey, or itinerary", ["places"], ["path", "travel"]),
  icon("ship", "Ship", "Sea transport or shipping", ["places", "commerce"], ["boat", "vessel"]),
  icon("tent", "Tent", "Camping or an outdoor location", ["places"], ["camping", "outdoors"]),
  icon("train", "Train", "Rail travel or public transport", ["places"], ["rail", "transport"]),
  icon("truck", "Truck", "Freight, logistics, or delivery", ["places", "commerce"], ["shipping", "delivery"]),
  icon("world", "World", "Global, international, or web content", ["recommended", "places", "data"], ["globe", "web"]),

  icon("apple", "Apple", "Fruit, food, or healthy eating", ["food"], ["fruit", "healthy"]),
  icon("cake", "Cake", "Dessert or a celebration", ["food"], ["dessert", "birthday"]),
  icon("chef-hat", "Chef hat", "Cooking, recipes, or a restaurant", ["food", "work"], ["cook", "recipe", "restaurant"]),
  icon("coffee", "Coffee", "Coffee, a café, or a break", ["recommended", "food", "work"], ["drink", "cafe", "caffeine"]),
  icon("cookie", "Cookie", "A snack, dessert, or browser cookie", ["food", "data"], ["dessert", "snack"]),
  icon("glass", "Glass", "A drink or beverage", ["food"], ["drink", "wine"]),
  icon("ice-cream", "Ice cream", "A frozen dessert or treat", ["food"], ["dessert", "frozen"]),
  icon("lemon", "Lemon", "Citrus fruit or a fresh flavor", ["food"], ["fruit", "citrus"]),
  icon("mug", "Mug", "A hot drink or cup", ["food", "work"], ["cup", "beverage"]),
  icon("pizza", "Pizza", "Food, delivery, or a restaurant", ["recommended", "food", "commerce"], ["restaurant", "delivery"]),

  icon("headphones", "Headphones", "Listening to music or audio", ["media", "devices"], ["audio", "listen"]),
  icon("music", "Music", "Songs, sound, or audio", ["media"], ["song", "audio"]),
  icon("palette", "Palette", "Color, art, or visual design", ["media", "work"], ["color", "design", "art"]),
  icon("photo", "Photo", "An image or picture", ["recommended", "media", "files"], ["image", "picture"]),
  icon("player-pause", "Pause", "Pause audio or video playback", ["media"], ["stop", "playback"]),
  icon("player-play", "Play", "Start audio or video playback", ["recommended", "media"], ["start", "playback"]),
  icon("player-stop", "Stop", "Stop audio or video playback", ["media"], ["halt", "playback"]),
  icon("video", "Video", "Moving images or a recording", ["recommended", "media", "communication"], ["camera", "movie"]),
  icon("volume", "Volume", "Sound or audio level", ["media", "devices"], ["sound", "audio"]),

  icon("device-desktop", "Desktop", "A desktop computer or monitor", ["recommended", "devices", "data"], ["computer", "screen"]),
  icon("device-laptop", "Laptop", "A portable computer", ["devices", "data"], ["computer"]),
  icon("device-mobile", "Mobile phone", "A smartphone or mobile view", ["devices", "communication"], ["phone", "smartphone"]),
  icon("device-tablet", "Tablet", "A tablet computer or tablet view", ["devices", "data"], ["ipad", "computer"]),
  icon("plug", "Plug", "Power or a system connection", ["devices", "data"], ["connect", "power"]),
] as const;
