import { i18n } from "@k2b/stdlib";

export const assistantMessages = i18n.define({ baseLocale: "en", messages: {
  en: {
    start: "Start", assistant: "Assistant", workOn: "What should we work on?", chooseProject: "Choose a Project for this chat", noProject: "No Project", starters: "Conversation starters",
    followMail: "Follow up on mail", followMailPrompt: "Help me follow up on the mail about ", dailySchedule: "Set a daily schedule", dailySchedulePrompt: "Set up a daily schedule that ", findCloud: "Find something in Cloud", findCloudPrompt: "Find information in Cloud about ", notesNext: "Turn notes into next steps", notesNextPrompt: "Turn these notes into clear next steps:\n\n",
    searchChats: "Search chats", searchChatsPlaceholder: "Search chats…", noChatsFound: "No chats found.", editConversation: ({ title }: { title: string }) => `Edit ${title}`, projects: "Projects", createProject: "Create Project", noProjects: "No Projects yet", noRecentChats: "No recent chats", pinned: "Pinned", chats: "Chats", allChats: "All chats", noChats: "No chats yet", seeAllChats: "See all chats", seeAll: "See all", newChat: "New chat", newProject: "New Project", personalize: "Personalize", recentAllChats: "Recent and all chats", stopBeforeArchive: "Stop the current response before archiving this chat.",
    liveRetry: "Live updates could not be refreshed. Retrying…", loadMessageFailed: "Could not load this message.", messageMissing: "Could not find this message in the timeline.", openConversationFailed: "Failed to open conversation", projectNotFound: "Project not found", replaceDraft: "Replace the current draft with this queued message?", editQueued: "Edit queued message",
    chooseProjectTitle: "Choose a Project", searchProjects: "Search Projects…", noMatchingProjects: "No matching Projects.", separateChat: "Keep this chat separate", sharedProjectContext: "Use shared Project context", chooseProjectFailed: "Failed to choose Project.", attachmentsAfterResponse: "Attachments can be added after the current response finishes.", resourceAlreadyAttached: "This Cloud resource is already attached.", openChatBeforeAttachment: "Open the chat before showing this text attachment.", loadTextAttachmentFailed: "The text attachment could not be loaded.", textTooLong: "The text is too long to show in the message field.", attachResourceFailed: "The Cloud resource could not be attached.", clipboardNoResource: "The clipboard does not contain a resource from this Cloud installation.", attachResource: "Attach Cloud resource", attachFiles: "Attach files", stopping: "Stopping response", queueMessage: "Queue another message", askAnything: "Ask Assistant anything", aiNotConfigured: "AI is not configured", noModelsAvailable: "No model available. Contact an administrator.", chatActionFailed: "Chat action failed.", pasteResource: "Paste Cloud resource", searchThisChat: "Search this chat", compactContext: "Compact context", reconnecting: "Reconnecting…", startConversation: "Start a conversation", aiDisabled: "AI is disabled", submitApprovalFailed: "Could not submit approval.", submitToolFailed: "Could not submit tool response.", forkFailed: "Could not fork conversation.", retryMessageFailed: "Could not retry message.", saveFeedbackFailed: "Could not save message feedback.", retrySteerFailed: "Could not retry steer message.",
    startProjectChat: ({ project }: { project: string }) => `Start a new chat in ${project}`, thisProject: "this Project", attachmentLimit: ({ count }: { count: number }) => `A message can attach at most ${count} items.`, discardedAttachments: ({ count }: { count: number }) => i18n.plural(count, "en", { one: "1 attachment was discarded because the limit was reached.", other: `${count} attachments were discarded because the limit was reached.` }),
    queuedMessages: "Queued messages", sending: "Sending…", sendNow: "Send now", queuedActions: "Queued message actions", edit: "Edit", delete: "Delete", closeFiles: "Close files", needsAttention: "Needs attention", queued: "Queued", running: "Running", failed: "Failed", newResponse: "New response", pinnedLabel: "Pinned", contextSummary: "Context summary", you: "You", system: "System", message: "message", messageNumber: ({ seq }: { seq: number }) => `Message ${seq}`, searchMessages: "Search messages…", typeToSearchChat: "Type to search this chat.", noMatchingMessages: "No matching messages.",
  },
  de: {
    start: "Start", assistant: "Assistent", workOn: "Woran möchtest du arbeiten?", chooseProject: "Projekt für diesen Chat auswählen", noProject: "Kein Projekt", starters: "Gesprächsvorschläge",
    followMail: "E-Mail nachverfolgen", followMailPrompt: "Hilf mir, die E-Mail zu folgendem Thema nachzuverfolgen: ", dailySchedule: "Täglichen Ablauf planen", dailySchedulePrompt: "Erstelle einen täglichen Ablauf, der ", findCloud: "In Cloud suchen", findCloudPrompt: "Finde in Cloud Informationen zu ", notesNext: "Nächste Schritte ableiten", notesNextPrompt: "Leite aus diesen Notizen klare nächste Schritte ab:\n\n",
    searchChats: "Chats durchsuchen", searchChatsPlaceholder: "Chats durchsuchen…", noChatsFound: "Keine Chats gefunden.", editConversation: ({ title }) => `${title} bearbeiten`, projects: "Projekte", createProject: "Projekt erstellen", noProjects: "Noch keine Projekte", noRecentChats: "Keine aktuellen Chats", pinned: "Angeheftet", chats: "Chats", allChats: "Alle Chats", noChats: "Noch keine Chats", seeAllChats: "Alle Chats anzeigen", seeAll: "Alle anzeigen", newChat: "Neuer Chat", newProject: "Neues Projekt", personalize: "Personalisieren", recentAllChats: "Aktuelle und alle Chats", stopBeforeArchive: "Beende die aktuelle Antwort, bevor du diesen Chat archivierst.",
    liveRetry: "Live-Aktualisierungen konnten nicht geladen werden. Neuer Versuch…", loadMessageFailed: "Diese Nachricht konnte nicht geladen werden.", messageMissing: "Diese Nachricht wurde im Verlauf nicht gefunden.", openConversationFailed: "Der Chat konnte nicht geöffnet werden", projectNotFound: "Projekt nicht gefunden", replaceDraft: "Den aktuellen Entwurf durch diese vorgemerkte Nachricht ersetzen?", editQueued: "Vorgemerkte Nachricht bearbeiten",
    chooseProjectTitle: "Projekt auswählen", searchProjects: "Projekte durchsuchen…", noMatchingProjects: "Keine passenden Projekte.", separateChat: "Diesen Chat keinem Projekt zuordnen", sharedProjectContext: "Gemeinsamen Projektkontext verwenden", chooseProjectFailed: "Das Projekt konnte nicht ausgewählt werden.", attachmentsAfterResponse: "Anhänge können hinzugefügt werden, sobald die aktuelle Antwort abgeschlossen ist.", resourceAlreadyAttached: "Diese Cloud-Ressource ist bereits angehängt.", openChatBeforeAttachment: "Öffne den Chat, bevor du diesen Textanhang anzeigst.", loadTextAttachmentFailed: "Der Textanhang konnte nicht geladen werden.", textTooLong: "Der Text ist zu lang für das Nachrichtenfeld.", attachResourceFailed: "Die Cloud-Ressource konnte nicht angehängt werden.", clipboardNoResource: "Die Zwischenablage enthält keine Ressource aus dieser Cloud-Installation.", attachResource: "Cloud-Ressource anhängen", attachFiles: "Dateien anhängen", stopping: "Antwort wird beendet", queueMessage: "Weitere Nachricht vormerken", askAnything: "Assistent etwas fragen", aiNotConfigured: "KI ist nicht konfiguriert", noModelsAvailable: "Kein Modell verfügbar. Wende dich an einen Administrator.", chatActionFailed: "Chataktion fehlgeschlagen.", pasteResource: "Cloud-Ressource einfügen", searchThisChat: "Diesen Chat durchsuchen", compactContext: "Kontext komprimieren", reconnecting: "Verbindung wird wiederhergestellt…", startConversation: "Chat beginnen", aiDisabled: "KI ist deaktiviert", submitApprovalFailed: "Die Freigabe konnte nicht übermittelt werden.", submitToolFailed: "Die Antwort an das Tool konnte nicht übermittelt werden.", forkFailed: "Der Chat konnte nicht abgezweigt werden.", retryMessageFailed: "Die Nachricht konnte nicht erneut versucht werden.", saveFeedbackFailed: "Das Feedback zur Nachricht konnte nicht gespeichert werden.", retrySteerFailed: "Die Korrektur konnte nicht erneut versucht werden.",
    startProjectChat: ({ project }) => `Neuen Chat in ${project} beginnen`, thisProject: "diesem Projekt", attachmentLimit: ({ count }) => `Eine Nachricht kann höchstens ${count} Elemente enthalten.`, discardedAttachments: ({ count }) => i18n.plural(count, "de", { one: "1 Anhang wurde verworfen, weil die Höchstzahl erreicht ist.", other: `${count} Anhänge wurden verworfen, weil die Höchstzahl erreicht ist.` }),
    queuedMessages: "Vorgemerkte Nachrichten", sending: "Wird gesendet…", sendNow: "Jetzt senden", queuedActions: "Aktionen für vorgemerkte Nachricht", edit: "Bearbeiten", delete: "Löschen", closeFiles: "Dateien schließen", needsAttention: "Eingriff erforderlich", queued: "Vorgemerkt", running: "Läuft", failed: "Fehlgeschlagen", newResponse: "Neue Antwort", pinnedLabel: "Angeheftet", contextSummary: "Kontextzusammenfassung", you: "Du", system: "System", message: "Nachricht", messageNumber: ({ seq }) => `Nachricht ${seq}`, searchMessages: "Nachrichten durchsuchen…", typeToSearchChat: "Tippe, um diesen Chat zu durchsuchen.", noMatchingMessages: "Keine passenden Nachrichten.",
  },
} });
