import { i18n } from "@k2b/stdlib";
import { useLocale } from "@k2b/ui";

const germanText: Record<string, string> = {
  "Scheduled AI task": "Geplante KI-Aufgabe",
  "AI conversation": "KI-Chat",
  "A reference with this name already exists.": "Eine Referenz mit diesem Namen ist bereits vorhanden.",
  "Add a durable fact about you or a preference for future answers. New entries start pinned.": "Füge eine dauerhafte Tatsache über dich oder eine Präferenz für künftige Antworten hinzu. Neue Einträge sind zunächst angeheftet.",
  Access: "Zugriff",
  "Actions listed here can run without asking again. Revoking a decision applies immediately.": "Diese Aktionen können ohne erneute Freigabe ausgeführt werden. Ein Widerruf gilt sofort.",
  Add: "Hinzufügen",
  "Add a fact or preference Assistant can use in future conversations.": "Füge eine Tatsache oder Präferenz hinzu, die der Assistent in künftigen Chats verwenden kann.",
  "Add personalization": "Personalisierung hinzufügen",
  "Add skill": "Skill hinzufügen",
  "Add supporting context.": "Ergänzende Informationen hinzufügen.",
  "Add supporting information Assistant can read when this Skill needs it.": "Füge Informationen hinzu, die der Assistent bei Bedarf für diesen Skill lesen kann.",
  "Add the supporting information Assistant may need for this workflow.": "Ergänze Informationen, die der Assistent für diesen Ablauf benötigen kann.",
  Added: "Hinzugefügt",
  "After a private-chat turn completes, Assistant may save durable facts, preferences, and repeated Cloud workflow defaults.": "Nach einer Anfrage in einem privaten Chat kann der Assistent dauerhafte Tatsachen, Präferenzen und wiederkehrende Cloud-Abläufe speichern.",
  "All chats": "Alle Chats",
  Approvals: "Freigaben",
  "Assistant sees the name and description before deciding to load a Skill. Say what to do and when to use it.": "Der Assistent sieht Name und Beschreibung, bevor er einen Skill lädt. Beschreibe die Aufgabe und wann der Skill verwendet werden soll.",
  "Assistant settings": "Assistent-Einstellungen",
  "Available skills": "Verfügbare Skills",
  Changes: "Änderungen",
  "Chat context": "Chatkontext",
  "Chat history pages": "Seiten des Chatverlaufs",
  "Choose a future date and time.": "Wähle ein Datum und eine Uhrzeit in der Zukunft.",
  "Choose how Assistant uses and learns durable context about you.": "Lege fest, wie der Assistent dauerhafte Informationen über dich verwendet und lernt.",
  Close: "Schließen",
  "Close Assistant settings": "Assistent-Einstellungen schließen",
  "Close Project settings": "Projekt-Einstellungen schließen",
  "Close learning run details": "Details des Lernlaufs schließen",
  "Close personalization learning activity": "Lernaktivität der Personalisierung schließen",
  "Cloud AI tool": "Cloud-KI-Tool",
  "Cloud resolves direct and nested group membership at request time.": "Cloud ermittelt direkte und verschachtelte Gruppenmitgliedschaften bei jeder Anfrage.",
  "Cloud resource": "Cloud-Ressource",
  "Could not create Project": "Projekt konnte nicht erstellt werden",
  "Could not load learning activity": "Lernaktivität konnte nicht geladen werden",
  "Could not load personalization": "Personalisierung konnte nicht geladen werden",
  "Could not load skill": "Skill konnte nicht geladen werden",
  "Could not load skills": "Skills konnten nicht geladen werden",
  "Could not load system prompt": "System-Prompt konnte nicht geladen werden",
  "Could not open reference": "Referenz konnte nicht geöffnet werden",
  "Could not save Project": "Projekt konnte nicht gespeichert werden",
  "Could not save task": "Aufgabe konnte nicht gespeichert werden",
  "Could not update task": "Aufgabe konnte nicht aktualisiert werden",
  "Create Project": "Projekt erstellen",
  "Create weekly status reports from recent work. Use when asked for progress updates.": "Erstelle wöchentliche Statusberichte aus der letzten Arbeit. Verwende diesen Skill bei Fragen nach dem Fortschritt.",
  "Create skill": "Skill erstellen",
  "Create, import, and share reusable Assistant workflows.": "Wiederverwendbare Abläufe für den Assistenten erstellen, importieren und teilen.",
  "Define the expected outcome, important constraints, and workflow. Include only guidance that changes how Assistant should work.": "Beschreibe das erwartete Ergebnis, wichtige Einschränkungen und den Ablauf. Nimm nur Hinweise auf, die die Arbeitsweise des Assistenten verändern.",
  "Description controls when this Skill loads": "Die Beschreibung bestimmt, wann dieser Skill geladen wird",
  Details: "Details",
  Disabled: "Deaktiviert",
  Done: "Fertig",
  "Download SKILL.md": "SKILL.md herunterladen",
  "Each Skill combines reusable instructions with optional extra information. Shared Skills start enabled for you; turn off any you don't want Assistant to use.": "Jeder Skill verbindet wiederverwendbare Anweisungen mit optionalen Zusatzinformationen. Geteilte Skills sind zunächst aktiviert; deaktiviere Skills, die der Assistent nicht verwenden soll.",
  "Edit personalization": "Personalisierung bearbeiten",
  "Edit skill": "Skill bearbeiten",
  "Edit this personalization entry.": "Diesen Personalisierungseintrag bearbeiten.",
  "Effective instructions": "Wirksame Anweisungen",
  "Enter a five-field cron expression.": "Gib einen Cron-Ausdruck mit fünf Feldern ein.",
  "Enter what Assistant should do.": "Beschreibe, was der Assistent erledigen soll.",
  "Evidence chat": "Quellchat",
  "Explain the workflow, constraints, and expected output.": "Beschreibe Ablauf, Einschränkungen und erwartetes Ergebnis.",
  "Export ZIP": "ZIP exportieren",
  "Extra info": "Zusatzinformationen",
  "Facts, preferences, and workflow defaults Assistant may carry into future conversations.": "Tatsachen, Präferenzen und Abläufe, die der Assistent in künftigen Chats berücksichtigen kann.",
  "Failed to add personalization": "Personalisierung konnte nicht hinzugefügt werden",
  "Failed to create Project": "Projekt konnte nicht erstellt werden",
  "Failed to delete personalization": "Personalisierung konnte nicht gelöscht werden",
  "Failed to delete skill": "Skill konnte nicht gelöscht werden",
  "Failed to import skill": "Skill konnte nicht importiert werden",
  "Failed to load AI preferences": "KI-Einstellungen konnten nicht geladen werden",
  "Failed to load Project access": "Projektzugriff konnte nicht geladen werden",
  "Failed to load skill": "Skill konnte nicht geladen werden",
  "Failed to load skill access": "Skill-Zugriff konnte nicht geladen werden",
  "Failed to revoke approval": "Freigabe konnte nicht widerrufen werden",
  "Failed to save Project": "Projekt konnte nicht gespeichert werden",
  "Failed to save personalization settings": "Personalisierungseinstellungen konnten nicht gespeichert werden",
  "Failed to save skill": "Skill konnte nicht gespeichert werden",
  "Failed to update personalization": "Personalisierung konnte nicht aktualisiert werden",
  "Failed to update skill preference": "Skill-Einstellung konnte nicht aktualisiert werden",
  Fact: "Tatsache",
  "File is no longer available.": "Die Datei ist nicht mehr verfügbar.",
  General: "Allgemein",
  "Go to source": "Quelle öffnen",
  "How should Assistant work in this Project?": "Wie soll der Assistent in diesem Projekt arbeiten?",
  "Import skill": "Skill importieren",
  "Inspect the complete instructions and context applied to new chats.": "Vollständige Anweisungen und Kontext für neue Chats prüfen.",
  Instructions: "Anweisungen",
  "Instructions are applied to new turns in every Project chat.": "Die Anweisungen gelten für neue Anfragen in allen Chats dieses Projekts.",
  "Learn personalization from private chats": "Personalisierung aus privaten Chats lernen",
  Learned: "Gelernt",
  "Learning activity": "Lernaktivität",
  "Learning run details": "Details des Lernlaufs",
  "Loading learning activity": "Lernaktivität wird geladen",
  "Loading personalization": "Personalisierung wird geladen",
  "Loading remembered approvals": "Gespeicherte Freigaben werden geladen",
  "Loading skill": "Skill wird geladen",
  "Loading skills": "Skills werden geladen",
  "Loading system prompt": "System-Prompt wird geladen",
  "Manage access": "Zugriff verwalten",
  "Manage actions Assistant may run without asking each time.": "Aktionen verwalten, die der Assistent ohne erneute Nachfrage ausführen darf.",
  "Manage supporting information Assistant can read when this Skill needs it.": "Informationen verwalten, die der Assistent bei Bedarf für diesen Skill lesen kann.",
  "Memories changed by this learning run": "Durch diesen Lernlauf geänderte Personalisierung",
  Merged: "Zusammengeführt",
  "Name is required.": "Ein Name ist erforderlich.",
  "Name, description, and instructions shared by this Project.": "Name, Beschreibung und gemeinsame Anweisungen dieses Projekts.",
  "No additional access": "Kein zusätzlicher Zugriff",
  "No archived chats.": "Keine archivierten Chats.",
  "No changes": "Keine Änderungen",
  "No chats are running.": "Keine laufenden Chats.",
  "No chats found.": "Keine Chats gefunden.",
  "No chats match your search.": "Keine passenden Chats gefunden.",
  "No chats need attention.": "Kein Chat erfordert einen Eingriff.",
  "No chats yet.": "Noch keine Chats.",
  "No extra info yet": "Noch keine Zusatzinformationen",
  "No failed chats.": "Keine fehlgeschlagenen Chats.",
  "No learning runs yet. Activity appears after Assistant checks a completed private-chat turn.": "Noch keine Lernläufe. Aktivität erscheint, nachdem der Assistent eine abgeschlossene Anfrage in einem privaten Chat geprüft hat.",
  "No matching knowledge.": "Kein passendes Wissen gefunden.",
  "No matching personalization. Try a different search.": "Keine passende Personalisierung gefunden. Ändere den Suchbegriff.",
  "No new responses.": "Keine neuen Antworten.",
  "No personalization changed": "Keine Personalisierung geändert",
  "No personalization yet": "Noch keine Personalisierung",
  "No remembered approvals. Actions will ask before they run.": "Keine gespeicherten Freigaben. Vor der Ausführung wird nachgefragt.",
  "Only Project instructions are treated as instructions; files, knowledge, and references remain data.": "Nur Projektanweisungen gelten als Anweisungen; Dateien, Wissen und Referenzen bleiben Daten.",
  "Open in new tab": "In neuem Tab öffnen",
  "Open link": "Link öffnen",
  "People and groups with direct access to this Project.": "Personen und Gruppen mit direktem Zugriff auf dieses Projekt.",
  Personalization: "Personalisierung",
  "Personalization actions": "Aktionen für die Personalisierung",
  "Personalization added": "Personalisierung hinzugefügt",
  "Personalization deleted": "Personalisierung gelöscht",
  "Personalization entries": "Personalisierungseinträge",
  "Personalization learning activity": "Lernaktivität der Personalisierung",
  "Personalization learning runs": "Lernläufe der Personalisierung",
  "Personalization settings saved": "Personalisierungseinstellungen gespeichert",
  "Personalization updated": "Personalisierung aktualisiert",
  "Prefers concise answers in German.": "Bevorzugt kurze Antworten auf Deutsch.",
  Preference: "Präferenz",
  Pinned: "Angeheftet",
  "Project access": "Projektzugriff",
  "Project created": "Projekt erstellt",
  "Project file could not be loaded.": "Die Projektdatei konnte nicht geladen werden.",
  "Project file is no longer available.": "Die Projektdatei ist nicht mehr verfügbar.",
  "Project saved": "Projekt gespeichert",
  "Reference name": "Name der Referenz",
  "Relevant personal facts, preferences, and workflow defaults are added to new turns.": "Relevante persönliche Tatsachen, Präferenzen und Abläufe werden neuen Anfragen hinzugefügt.",
  "Remembered approvals": "Gespeicherte Freigaben",
  "Remove reference": "Referenz entfernen",
  Retired: "Entfernt",
  "Review background runs and the personalization they changed.": "Hintergrundläufe und ihre Änderungen an der Personalisierung prüfen.",
  "Revoke approval": "Freigabe widerrufen",
  Run: "Lauf",
  Save: "Speichern",
  "Save changes": "Änderungen speichern",
  "Save reference": "Referenz speichern",
  "Saved personalization": "Gespeicherte Personalisierung",
  Scheduled: "Geplant",
  "Scheduled task request failed": "Die Anfrage für die geplante Aufgabe ist fehlgeschlagen",
  "Scheduled tasks": "Geplante Aufgaben",
  "Search Project knowledge…": "Projektwissen durchsuchen…",
  "Search chats": "Chats durchsuchen",
  "Search chats…": "Chats durchsuchen…",
  "Search personalization": "Personalisierung durchsuchen",
  "Search skills": "Skills durchsuchen",
  "See when Assistant learned from completed private-chat turns, consolidated workflows, and exactly what changed.": "Zeigt, wann der Assistent aus abgeschlossenen privaten Chats und zusammengeführten Abläufen gelernt hat und was geändert wurde.",
  "Share this skill through Cloud permissions. At least one administrator must remain.": "Teile diesen Skill über Cloud-Berechtigungen. Mindestens eine Person muss Administrator bleiben.",
  Sharing: "Teilen",
  "Skill deleted": "Skill gelöscht",
  "Skill name": "Name des Skills",
  Skills: "Skills",
  "Skills teach Assistant how to handle specific tasks": "Skills erklären dem Assistenten, wie er bestimmte Aufgaben erledigt",
  Sources: "Quellen",
  "Start with an action and say when to use it. Keep it short, direct, and specific.": "Beginne mit einer Handlung und beschreibe, wann der Skill verwendet werden soll. Formuliere kurz, direkt und konkret.",
  "System prompt": "System-Prompt",
  "The Cloud resource could not be resolved.": "Die Cloud-Ressource konnte nicht aufgelöst werden.",
  "The application for this reference is unavailable.": "Die Anwendung für diese Referenz ist nicht verfügbar.",
  "The complete prompt for a new chat with the current model, enabled Skills, personalization, and organization rules.": "Der vollständige Prompt für einen neuen Chat mit aktuellem Modell, aktivierten Skills, Personalisierung und Organisationsregeln.",
  "This Cloud resource has no open link.": "Für diese Cloud-Ressource ist kein Link zum Öffnen verfügbar.",
  "This Cloud resource has no reader.": "Für diese Cloud-Ressource ist keine Lese-Capability verfügbar.",
  "This Skill is read only": "Dieser Skill ist schreibgeschützt",
  "This run found nothing durable to save.": "Dieser Lauf hat keine dauerhaft speicherbaren Informationen gefunden.",
  Tokens: "Tokens",
  Updated: "Aktualisiert",
  "Use a short, action-oriented name with lowercase letters, numbers, and hyphens.": "Verwende einen kurzen, handlungsorientierten Namen aus Kleinbuchstaben, Zahlen und Bindestrichen.",
  "Use a short, recognizable name such as product-rules.": "Verwende einen kurzen, eindeutigen Namen wie product-rules.",
  "Use personalization": "Personalisierung verwenden",
  "Use personalization in Assistant chats": "Personalisierung in Assistent-Chats verwenden",
  "View activity": "Aktivität anzeigen",
  "View details for": "Details anzeigen für",
  "View learning run details": "Details des Lernlaufs anzeigen",
  Type: "Typ",
  "You can view and export it, but you cannot change it.": "Du kannst ihn ansehen und exportieren, aber nicht ändern.",
  failed: "fehlgeschlagen",
  ok: "erfolgreich",
  skipped: "übersprungen",
  All: "Alle",
  Running: "Läuft",
  "Needs attention": "Eingriff erforderlich",
  Failed: "Fehlgeschlagen",
  "New responses": "Neue Antworten",
  Archived: "Archiviert",
  "Search and manage your history": "Chatverlauf durchsuchen und verwalten",
  "Chat filters": "Chatfilter",
  "Loading chats…": "Chats werden geladen…",
  "Could not load chats": "Chats konnten nicht geladen werden",
  Retry: "Erneut versuchen",
  Previous: "Zurück",
  Next: "Weiter",
  "Restore chat": "Chat wiederherstellen",
  "Edit chat": "Chat bearbeiten",
  "No chats left on this page.": "Auf dieser Seite sind keine Chats mehr vorhanden.",
  When: "Zeitpunkt",
  Status: "Status",
  Trigger: "Auslöser",
  Model: "Modell",
  Duration: "Dauer",
  Result: "Ergebnis",
  "Reindex queued — running in the background…": "Neue Indizierung vorgemerkt – sie läuft im Hintergrund…",
  "Index state unavailable.": "Der Indexstatus ist nicht verfügbar.",
  "Not indexed yet — the next background run will pick this chat up.": "Noch nicht indiziert – der nächste Hintergrundlauf verarbeitet diesen Chat.",
  Reindexing: "Wird neu indiziert",
  Reindex: "Neu indizieren",
  "No index runs yet.": "Noch keine Indizierungsläufe.",
  "Chat saved": "Chat gespeichert",
  "Archive chat": "Chat archivieren",
  Archive: "Archivieren",
  Cancel: "Abbrechen",
  "Chat archived": "Chat archiviert",
  "Chat Settings": "Chat-Einstellungen",
  "Close chat settings": "Chat-Einstellungen schließen",
  Chat: "Chat",
  "Name, description, and list placement.": "Name, Beschreibung und Position in der Liste.",
  Identity: "Darstellung",
  "Choose how this chat appears in navigation and search results.": "Lege fest, wie dieser Chat in der Navigation und in Suchergebnissen erscheint.",
  Name: "Name",
  "Shown in the chat list and header.": "Wird in der Chatliste und in der Kopfzeile angezeigt.",
  "Name is required": "Ein Name ist erforderlich",
  Description: "Beschreibung",
  "Optional context shown with this chat.": "Optionaler Kontext, der bei diesem Chat angezeigt wird.",
  "Optional context for this chat...": "Optionaler Kontext für diesen Chat…",
  "Pin this chat": "Diesen Chat anheften",
  "Keep this chat at the top of your chat list.": "Zeigt diesen Chat oben in deiner Chatliste an.",
  Search: "Suche",
  "Review and refresh the generated summary and keywords used to find this chat.": "Prüfe und aktualisiere die Zusammenfassung und Schlagwörter für die Suche nach diesem Chat.",
  "Search index": "Suchindex",
  "Index status and recent enrichment runs for this chat.": "Indexstatus und letzte Aufbereitungsläufe für diesen Chat.",
  Lifecycle: "Lebenszyklus",
  "Remove this chat from active lists. You can restore it later from All Chats.": "Entfernt diesen Chat aus aktiven Listen. Unter Alle Chats kannst du ihn wiederherstellen.",
  "Move this chat out of your active lists.": "Entfernt diesen Chat aus deinen aktiven Listen.",
  "Archiving chat": "Chat wird archiviert",
  Active: "Aktiv",
  Paused: "Pausiert",
  Completed: "Abgeschlossen",
  Queued: "Vorgemerkt",
  "Edit task": "Aufgabe bearbeiten",
  "Schedule a task": "Aufgabe planen",
  "Tasks stay attached to this chat and use its current Project context when they run.": "Aufgaben bleiben diesem Chat zugeordnet und verwenden bei der Ausführung seinen aktuellen Projektkontext.",
  Prompt: "Auftrag",
  "What should Assistant do?": "Was soll der Assistent erledigen?",
  Schedule: "Zeitplan",
  Once: "Einmalig",
  Recurring: "Wiederkehrend",
  "Cron expression": "Cron-Ausdruck",
  "Run at": "Ausführen am",
  "Save task": "Aufgabe speichern",
  "Schedule task": "Aufgabe planen",
  "Task action failed": "Aktion für die Aufgabe fehlgeschlagen",
  "Could not load tasks": "Aufgaben konnten nicht geladen werden",
  "Loading tasks": "Aufgaben werden geladen",
  "No scheduled tasks": "Keine geplanten Aufgaben",
  "Create a one-time or recurring task for this chat.": "Erstelle für diesen Chat eine einmalige oder wiederkehrende Aufgabe.",
  Edit: "Bearbeiten",
  Pause: "Pausieren",
  Resume: "Fortsetzen",
  "Run now": "Jetzt ausführen",
  History: "Verlauf",
  Delete: "Löschen",
  "Occurrence history": "Ausführungsverlauf",
  "Could not load occurrence history": "Der Ausführungsverlauf konnte nicht geladen werden",
  "Loading occurrence history": "Ausführungsverlauf wird geladen",
  "No occurrences yet": "Noch keine Ausführungen",
  Project: "Projekt",
  "Recent chats": "Aktuelle Chats",
  "No Project chats yet.": "Noch keine Chats in diesem Projekt.",
  "Project context": "Projektkontext",
  "Project settings": "Projekt-Einstellungen",
  "View project": "Projekt anzeigen",
  "Project instructions": "Projektanweisungen",
  "No Project instructions yet.": "Noch keine Projektanweisungen.",
  "Could not load Project context": "Der Projektkontext konnte nicht geladen werden",
  "Loading Project context": "Projektkontext wird geladen",
  "Project knowledge": "Projektwissen",
  "Add Project knowledge": "Projektwissen hinzufügen",
  "No Project knowledge yet.": "Noch kein Projektwissen.",
  Image: "Bild",
  Images: "Bilder",
  "Add images": "Bilder hinzufügen",
  "No Project images yet.": "Noch keine Bilder im Projekt.",
  File: "Datei",
  Files: "Dateien",
  "Add files": "Dateien hinzufügen",
  "No Project files yet.": "Noch keine Dateien im Projekt.",
  Reference: "Referenz",
  References: "Referenzen",
  "Add reference": "Referenz hinzufügen",
  "No Project references yet.": "Noch keine Referenzen im Projekt.",
  "View all": "Alle anzeigen",
  Download: "Herunterladen",
  "Remove from Project": "Aus Projekt entfernen",
  "Could not download file": "Datei konnte nicht heruntergeladen werden",
  "Could not open images": "Bilder konnten nicht geöffnet werden",
  "Images could not be loaded.": "Bilder konnten nicht geladen werden.",
  "Project context could not be updated.": "Der Projektkontext konnte nicht aktualisiert werden.",
  "Could not update Project context": "Projektkontext konnte nicht aktualisiert werden",
  "Edit knowledge": "Wissen bearbeiten",
  "Add knowledge": "Wissen hinzufügen",
  "Save knowledge": "Wissen speichern",
  Title: "Titel",
  Content: "Inhalt",
  "Reference material for future turns in this Project.": "Referenzmaterial für künftige Anfragen in diesem Projekt.",
  "Knowledge updated": "Wissen aktualisiert",
  "Knowledge added": "Wissen hinzugefügt",
  "Delete knowledge": "Wissen löschen",
  "Knowledge deleted": "Wissen gelöscht",
  "File could not be read.": "Die Datei konnte nicht gelesen werden.",
  "Drop files here or choose them from this device": "Dateien hier ablegen oder auf diesem Gerät auswählen",
  "Add Project images": "Bilder zum Projekt hinzufügen",
  "Add Project files": "Dateien zum Projekt hinzufügen",
  "Delete file": "Datei löschen",
  "File deleted": "Datei gelöscht",
  "Add Cloud reference": "Cloud-Referenz hinzufügen",
  "Cloud reference added": "Cloud-Referenz hinzugefügt",
  "Remove Cloud reference": "Cloud-Referenz entfernen",
  "Cloud reference removed": "Cloud-Referenz entfernt",
  "File could not be downloaded.": "Die Datei konnte nicht heruntergeladen werden.",
  "Search references…": "Referenzen durchsuchen…",
  Page: "Seite",
  of: "von",
  chat: "Chat",
  chats: "Chats",
  "Delete skill": "Skill löschen",
  View: "Anzeigen",
  "View reference": "Referenz anzeigen",
  "Edit reference": "Referenz bearbeiten",
  "Actions for": "Aktionen für",
  "Skill ZIP must contain exactly one SKILL.md.": "Das Skill-ZIP muss genau eine SKILL.md enthalten.",
  "This Cloud version supports SKILL.md and Markdown references, but not scripts or assets.": "Diese Cloud-Version unterstützt SKILL.md und Markdown-Referenzen, aber keine Skripte oder Assets.",
  "Skill import is too large.": "Der Skill-Import ist zu groß.",
  "Choose a SKILL.md or a skill ZIP.": "Wähle eine SKILL.md oder ein Skill-ZIP.",
  "Delete personalization": "Personalisierung löschen",
  "Personalization unpinned": "Personalisierung nicht mehr angeheftet",
  "Personalization pinned": "Personalisierung angeheftet",
  Workflow: "Ablauf",
  "Repeated workflow": "Wiederkehrender Ablauf",
  "Chat turn": "Chat-Anfrage",
  added: "hinzugefügt",
  updated: "aktualisiert",
  merged: "zusammengeführt",
  retired: "entfernt",
  Change: "Änderung",
  Memory: "Personalisierung",
  "Previous value": "Vorheriger Wert",
  tokens: "Tokens",
};

export const missingAssistantGermanText = (values: Iterable<string>): string[] =>
  [...values].filter((value) => germanText[value] === undefined).sort();

const copy = i18n.define({
  baseLocale: "en",
  messages: {
    en: {
      text: ({ value }: { value: string }) => value,
      archiveChat: ({ title }: { title: string }) => `Archive "${title}"?`,
      deleteNamed: ({ name }: { name: string }) => `Delete "${name}"?`,
      removeFromProject: ({ name }: { name: string }) => `Remove “${name}” from this Project?`,
      removeFromSkill: ({ name }: { name: string }) => `Remove "${name}" from this Skill?`,
      openExternalLink: ({ title, host }: { title: string; host: string }) => `Open “${title}” from ${host} in a new tab?`,
      approvalAgain: ({ title }: { title: string }) => `${title} will ask for approval again`,
      chatsCount: ({ count }: { count: number }) => `${count} ${count === 1 ? "chat" : "chats"}`,
      referenceAction: ({ name, readOnly }: { name: string; readOnly: boolean }) => `${readOnly ? "View" : "Edit"} reference ${name}`,
      referenceCount: ({ count }: { count: number }) => `${count} reference${count === 1 ? "" : "s"}`,
     searchNamed: ({ name }: { name: string }) => `Search ${name}…`,
      invalidMarkdown: ({ path }: { path: string }) => `${path} is not valid UTF-8 Markdown.`,
      unsafeArchivePath: ({ path }: { path: string }) => `Skill archive contains an unsafe path: ${path}`,
      outsideSkillFolder: ({ path }: { path: string }) => `Skill ZIP contains a file outside its skill folder: ${path}`,
     unsupportedSkillFile: ({ path }: { path: string }) => `Unsupported skill file: ${path}`,
     deleteScheduledTask: ({ prompt }: { prompt: string }) => `Delete scheduled task “${prompt}”?`,
      editNamed: ({ name }: { name: string }) => `Edit ${name}`,
      restoreNamed: ({ name }: { name: string }) => `Restore ${name}`,
      restoringNamed: ({ name }: { name: string }) => `Restoring ${name}`,
      updatedAt: ({ value }: { value: string }) => `Updated ${value}`,
      searchChatsIn: ({ project }: { project: string }) => `Search chats in ${project}`,
    },
    de: {
      text: ({ value }: { value: string }) => germanText[value] ?? value,
      archiveChat: ({ title }: { title: string }) => `„${title}“ archivieren?`,
      deleteNamed: ({ name }: { name: string }) => `„${name}“ löschen?`,
      removeFromProject: ({ name }: { name: string }) => `„${name}“ aus diesem Projekt entfernen?`,
      removeFromSkill: ({ name }: { name: string }) => `„${name}“ aus diesem Skill entfernen?`,
      openExternalLink: ({ title, host }: { title: string; host: string }) => `„${title}“ von ${host} in einem neuen Tab öffnen?`,
      approvalAgain: ({ title }: { title: string }) => `Für ${title} wird wieder eine Freigabe angefordert`,
      chatsCount: ({ count }: { count: number }) => `${count} ${count === 1 ? "Chat" : "Chats"}`,
      referenceAction: ({ name, readOnly }: { name: string; readOnly: boolean }) => `Referenz ${name} ${readOnly ? "anzeigen" : "bearbeiten"}`,
      referenceCount: ({ count }: { count: number }) => `${count} ${count === 1 ? "Referenz" : "Referenzen"}`,
     searchNamed: ({ name }: { name: string }) => `${name} durchsuchen…`,
      invalidMarkdown: ({ path }: { path: string }) => `${path} ist kein gültiges UTF-8-Markdown.`,
      unsafeArchivePath: ({ path }: { path: string }) => `Das Skill-Archiv enthält einen unsicheren Pfad: ${path}`,
      outsideSkillFolder: ({ path }: { path: string }) => `Das Skill-ZIP enthält eine Datei außerhalb des Skill-Ordners: ${path}`,
     unsupportedSkillFile: ({ path }: { path: string }) => `Nicht unterstützte Skill-Datei: ${path}`,
     deleteScheduledTask: ({ prompt }: { prompt: string }) => `Geplante Aufgabe „${prompt}“ löschen?`,
      editNamed: ({ name }: { name: string }) => `${name} bearbeiten`,
      restoreNamed: ({ name }: { name: string }) => `${name} wiederherstellen`,
      restoringNamed: ({ name }: { name: string }) => `${name} wird wiederhergestellt`,
      updatedAt: ({ value }: { value: string }) => `Aktualisiert ${value}`,
      searchChatsIn: ({ project }: { project: string }) => `Chats in ${project} durchsuchen`,
    },
  },
});

export const useAssistantText = () => {
  const locale = useLocale();
  return (value: string): string => copy.resolve([locale()]).t.text({ value });
};

export const useAssistantCopy = () => {
  const locale = useLocale();
  return () => copy.resolve([locale()]).t;
};

export const assistantBrowserText = (value: string): string =>
  assistantBrowserCopy().text({ value });

export const assistantBrowserCopy = () =>
  copy.resolve([typeof document === "undefined" ? copy.baseLocale : document.documentElement.lang || copy.baseLocale]).t;
