/** German help text for `cld grids`, keyed by the English text. `cli.test.ts` requires an entry for every help string. */
export const GRIDS_CLI_HELP_DE: Readonly<Record<string, string>> = {
  "A request, not a write: a queued run is canceled at once, while a running or waiting one stops when the worker holding it next checks in. It never undoes an effect that already happened.":
    "Eine Anfrage, kein Schreibvorgang: Ein eingereihter Lauf wird sofort abgebrochen, ein laufender oder wartender stoppt, sobald sich der Worker, der ihn hält, das nächste Mal meldet. Bereits eingetretene Effekte werden nie rückgängig gemacht.",
  "A step has its own vocabulary, not the run's: STATUS is running, completed, waiting, failed, needs_attention, terminal, planned, unsupported, indeterminate, or canceled. A step completes where a run succeeds, and a dry run records planned steps. ATTEMPT counts re-runs of that one step and is 0 the first time.":
    "Ein Schritt hat ein eigenes Vokabular, nicht das des Laufs: STATUS ist running, completed, waiting, failed, needs_attention, terminal, planned, unsupported, indeterminate oder canceled. Wo ein Lauf erfolgreich ist, ist ein Schritt abgeschlossen, und ein Testlauf erfasst geplante Schritte. ATTEMPT zählt Wiederholungen genau dieses Schritts und ist beim ersten Mal 0.",
  "Acceptance does not mean processing has completed. The original retained event is used; retrying events cannot be replayed.":
    "Die Annahme bedeutet nicht, dass die Verarbeitung abgeschlossen ist. Es wird das ursprüngliche aufbewahrte Ereignis verwendet; Ereignisse, die noch wiederholt werden, können nicht erneut eingespielt werden.",
  "Action ID from runtime read": "Aktions-ID aus runtime read",
  "Action ID; omit for a scanner run": "Aktions-ID; bei einem Scanner-Lauf weglassen",
  "Activate the form": "Formular aktivieren",
  "Add a comment to a record": "Einen Kommentar zu einem Datensatz hinzufügen",
  "Allow live or deleted records": "Aktive oder gelöschte Datensätze zulassen",
  "Allowed sources: all, none, or direct,form,workflow": "Erlaubte Quellen: all, none oder direct,form,workflow",
  "Also show grants of resource-bound service accounts in text output.":
    "Freigaben ressourcengebundener Dienstkonten zusätzlich in der Textausgabe anzeigen.",
  "Already destroyed bytes cannot be recovered.": "Bereits vernichtete Bytes können nicht wiederhergestellt werden.",
  "Anyone with the link, including anonymous users": "Alle mit dem Link, auch anonyme Personen",
  "App name": "Name der App",
  "App page ID or exact title for page-context suggestions": "Seiten-ID oder exakter Titel einer App-Seite für Vorschläge im Seitenkontext",
  "App public id or exact name": "Öffentliche ID oder exakter Name der App",
  "App public id or exact name for page-context suggestions": "Öffentliche ID oder exakter Name der App für Vorschläge im Seitenkontext",
  "Approve a different person's request and finalize the Record":
    "Die Anfrage einer anderen Person genehmigen und den Datensatz finalisieren",
  "Approve and permanently finalize the Record": "Genehmigen und den Datensatz dauerhaft finalisieren",
  "Artifact key from documents get": "Artefaktschlüssel aus documents get",
  "Audit answers as JSON keyed by audit-question id": "Audit-Antworten als JSON, geschlüsselt nach Audit-Fragen-ID",
  "Base description": "Beschreibung der Basis",
  "Base name": "Name der Basis",
  "Base public ID": "Öffentliche ID der Basis",
  "Base public id": "Öffentliche ID der Basis",
  "Base public id or exact name": "Öffentliche ID oder exakter Name der Basis",
  "Browse a Combined table's published audit trail": "Den veröffentlichten Änderungsverlauf einer kombinierten Tabelle durchsuchen",
  "Browse generated documents as list rows or year/month folders":
    "Erzeugte Dokumente als Listenzeilen oder in Jahr/Monat-Ordnern durchsuchen",
  "Browse mode": "Modus zum Durchsuchen",
  "CSV delimiter: comma, semicolon, tab, pipe, or the literal delimiter":
    "CSV-Trennzeichen: comma, semicolon, tab, pipe oder das Trennzeichen selbst",
  "Cancel a queued, running, or waiting workflow run": "Einen eingereihten, laufenden oder wartenden Workflow-Lauf abbrechen",
  "Cancel remaining controlled destruction work": "Ausstehende kontrollierte Vernichtung abbrechen",
  "Cancel remaining work in one controlled destruction run": "Ausstehende Arbeit in einem Lauf der kontrollierten Vernichtung abbrechen",
  "Cancel this workflow run": "Diesen Workflow-Lauf abbrechen",
  "Change the table Finalization policy": "Finalisierungsrichtlinie der Tabelle ändern",
  "Checks Forms, Actions, and Workflows that would stop changing this table before you tighten its policy.":
    "Prüft Formulare, Aktionen und Workflows, die diese Tabelle nicht mehr ändern könnten, bevor du ihre Richtlinie verschärfst.",
  "Cloud group UUID whose members may approve Four-eyes requests":
    "UUID der Cloud-Gruppe, deren Mitglieder Vier-Augen-Anfragen genehmigen dürfen",
  "Comma-separated field ids in desired order": "Kommagetrennte Feld-IDs in gewünschter Reihenfolge",
  "Comma-separated kinds: user, group, service_account": "Kommagetrennte Arten: user, group, service_account",
  "Comment Markdown": "Kommentar als Markdown",
  "Comment public ID for update/delete": "Öffentliche ID des Kommentars für update/delete",
  "Compile and canonicalize a GQL source for a saved view": "Eine GQL-Quelle für eine gespeicherte Ansicht kompilieren und kanonisieren",
  "Compile, preview, and run Grids queries": "Grids-Abfragen kompilieren, in der Vorschau anzeigen und ausführen",
  "Configure and publish Combined tables": "Kombinierte Tabellen konfigurieren und veröffentlichen",
  "Confirm access revocation": "Entzug des Zugriffs bestätigen",
  "Confirm the exact inspected financial export and resume its workflow":
    "Den exakt geprüften Finanzexport bestätigen und seinen Workflow fortsetzen",
  "Confirm this financial export": "Diesen Finanzexport bestätigen",
  "Create a Grids base": "Eine Grids-Basis erstellen",
  "Create a base from a built-in template": "Eine Basis aus einer integrierten Vorlage erstellen",
  "Create a blank App draft": "Einen leeren App-Entwurf erstellen",
  "Create a custom form": "Ein eigenes Formular erstellen",
  "Create a direct Grids resource grant": "Eine direkte Freigabe für eine Grids-Ressource erstellen",
  "Create a document template": "Eine Dokumentvorlage erstellen",
  "Create a field": "Ein Feld erstellen",
  "Create a manual recursive record snapshot": "Einen manuellen rekursiven Snapshot eines Datensatzes erstellen",
  "Create a preservation hold": "Eine Erhaltungssperre erstellen",
  "Create a record": "Einen Datensatz erstellen",
  "Create a shared view": "Eine geteilte Ansicht erstellen",
  "Create a table": "Eine Tabelle erstellen",
  "Create a view": "Eine Ansicht erstellen",
  "Create a workflow": "Einen Workflow erstellen",
  "Create a workflow email template": "Eine E-Mail-Vorlage für Workflows erstellen",
  "Create an evidence package": "Ein Nachweispaket erstellen",
  "Create an expiring public link for a generated document": "Einen ablaufenden öffentlichen Link für ein erzeugtes Dokument erstellen",
  "Create and inspect recursive record snapshots": "Rekursive Snapshots von Datensätzen erstellen und prüfen",
  "Create and manage workflow email templates": "E-Mail-Vorlagen für Workflows erstellen und verwalten",
  "Create and validate a workflow launcher": "Eine Workflow-Ausführungsoption erstellen und validieren",
  "Create or conditionally update a record by external identity":
    "Einen Datensatz anhand einer externen Identität erstellen oder bedingt aktualisieren",
  "Create or update a direct Grids resource grant": "Eine direkte Freigabe für eine Grids-Ressource erstellen oder aktualisieren",
  "Create or update an App draft from its definition": "Einen App-Entwurf aus seiner Definition erstellen oder aktualisieren",
  "Create the template disabled": "Vorlage deaktiviert erstellen",
  "Create the template without sample records": "Vorlage ohne Beispieldatensätze erstellen",
  "Create the workflow disabled": "Workflow deaktiviert erstellen",
  "Create with a public submit token": "Mit öffentlichem Übermittlungstoken erstellen",
  "Create without a public submit token": "Ohne öffentliches Übermittlungstoken erstellen",
  "Create, inspect, and invoke workflow launchers": "Workflow-Ausführungsoptionen erstellen, prüfen und aufrufen",
  "Create, inspect, and manage Grids bases": "Grids-Basen erstellen, prüfen und verwalten",
  "Create, inspect, and manage saved views": "Gespeicherte Ansichten erstellen, prüfen und verwalten",
  "Create, inspect, and manage table fields": "Tabellenfelder erstellen, prüfen und verwalten",
  "Create, inspect, and manage tables": "Tabellen erstellen, prüfen und verwalten",
  "Create, inspect, and revoke public document links": "Öffentliche Dokumentlinks erstellen, prüfen und widerrufen",
  "Create, inspect, and submit forms": "Formulare erstellen, prüfen und absenden",
  "Create, preview, and manage document templates": "Dokumentvorlagen erstellen, in der Vorschau anzeigen und verwalten",
  "Create, query, import, and manage records": "Datensätze erstellen, abfragen, importieren und verwalten",
  "Create, validate, and publish Grids Apps": "Grids Apps erstellen, validieren und veröffentlichen",
  "Create, validate, invoke, and manage workflows": "Workflows erstellen, validieren, aufrufen und verwalten",
  "Current file public id": "Öffentliche ID der aktuellen Datei",
  "Current formula field public id or exact name": "Öffentliche ID oder exakter Name des aktuellen Formelfelds",
  "Deactivate the form": "Formular deaktivieren",
  "Delete a Grids base": "Eine Grids-Basis löschen",
  "Delete a document template": "Eine Dokumentvorlage löschen",
  "Delete a field": "Ein Feld löschen",
  "Delete a form": "Ein Formular löschen",
  "Delete a record comment as its author or a Base moderator": "Einen Datensatzkommentar als Autor oder Moderator der Basis löschen",
  "Delete a table": "Eine Tabelle löschen",
  "Delete a view": "Eine Ansicht löschen",
  "Delete a workflow": "Einen Workflow löschen",
  "Delete a workflow email template": "Eine E-Mail-Vorlage für Workflows löschen",
  "Delete a workflow launcher": "Eine Workflow-Ausführungsoption löschen",
  "Delete an App and remove its live route": "Eine App löschen und ihre Live-Route entfernen",
  "Delete the comment": "Den Kommentar löschen",
  "Delete this App": "Diese App löschen",
  "Delete this Grids base": "Diese Grids-Basis löschen",
  "Delete this comment": "Diesen Kommentar löschen",
  "Delete this document template": "Diese Dokumentvorlage löschen",
  "Delete this email template": "Diese E-Mail-Vorlage löschen",
  "Delete this field": "Dieses Feld löschen",
  "Delete this form": "Dieses Formular löschen",
  "Delete this table": "Diese Tabelle löschen",
  "Delete this view": "Diese Ansicht löschen",
  "Delete this workflow": "Diesen Workflow löschen",
  "Delete this workflow launcher": "Diese Workflow-Ausführungsoption löschen",
  "Destination TAR path": "Zielpfad der TAR-Datei",
  "Direct access entry id from access list": "ID des direkten Zugriffseintrags aus access list",
  "Disable direct record insertion": "Direktes Einfügen von Datensätzen deaktivieren",
  "Disable record finalization": "Finalisierung von Datensätzen deaktivieren",
  "Disable record finalization before the first record is finalized":
    "Finalisierung von Datensätzen deaktivieren, bevor der erste Datensatz finalisiert ist",
  "Disable the template": "Vorlage deaktivieren",
  "Disable the workflow": "Workflow deaktivieren",
  "Discover an authorized published page, its data, forms and available actions":
    "Eine berechtigte veröffentlichte Seite, ihre Daten, Formulare und verfügbaren Aktionen ermitteln",
  "Do not use field as record label": "Feld nicht als Datensatzbezeichnung verwenden",
  "Document link public id": "Öffentliche ID des Dokumentlinks",
  "Document offset": "Dokument-Offset",
  "Document public ID from runtime read": "Öffentliche ID des Dokuments aus runtime read",
  "Document public id": "Öffentliche ID des Dokuments",
  "Document template public id": "Öffentliche ID der Dokumentvorlage",
  "Document template public id or exact name": "Öffentliche ID oder exakter Name der Dokumentvorlage",
  "Download a card image using its signed token from a records result":
    "Ein Kartenbild mit seinem signierten Token aus einem Datensatzergebnis herunterladen",
  "Download a document visible in a published record block":
    "Ein Dokument herunterladen, das in einem veröffentlichten Datensatzblock sichtbar ist",
  "Download a file retained by a durable record version":
    "Eine Datei herunterladen, die von einer dauerhaften Datensatzversion aufbewahrt wird",
  "Download a generated document's stored primary file": "Die gespeicherte Hauptdatei eines erzeugten Dokuments herunterladen",
  "Download all documents of a workflow run: one PDF if all are PDFs, otherwise one ZIP":
    "Alle Dokumente eines Workflow-Laufs herunterladen: ein PDF, wenn alle PDFs sind, sonst ein ZIP",
  "Download one file-field blob": "Einen Blob eines Dateifelds herunterladen",
  "Download one stored Document artifact": "Ein gespeichertes Dokumentartefakt herunterladen",
  "Download one unreferenced retained File": "Eine nicht referenzierte, aufbewahrte Datei herunterladen",
  "Download output path": "Ausgabepfad für den Download",
  "Download permission-safe GQL schema context.md": "Berechtigungssicheres GQL-Schema context.md herunterladen",
  "Download the Grids GQL assistant SKILL.md": "SKILL.md des Grids-GQL-Assistenten herunterladen",
  "Download the exact completed evidence TAR without rendering again":
    "Das exakte fertige Nachweis-TAR herunterladen, ohne es erneut zu rendern",
  "Downloaded Grids evidence TAR": "Heruntergeladenes Grids-Nachweis-TAR",
  "Edit a record comment as its author or a Base moderator": "Einen Datensatzkommentar als Autor oder Moderator der Basis bearbeiten",
  "Email HTML Liquid template": "Liquid-Vorlage für den HTML-Inhalt der E-Mail",
  "Email subject Liquid template": "Liquid-Vorlage für den E-Mail-Betreff",
  "Email template public id or exact name": "Öffentliche ID oder exakter Name der E-Mail-Vorlage",
  "Enable direct record insertion": "Direktes Einfügen von Datensätzen aktivieren",
  "Enable irreversible record finalization": "Unumkehrbare Finalisierung von Datensätzen aktivieren",
  "Enable record finalization for a table": "Finalisierung von Datensätzen für eine Tabelle aktivieren",
  "Enable the template": "Vorlage aktivieren",
  "Enable the workflow": "Workflow aktivieren",
  "Enables append-only record versions permanently. The command continues the initial baseline in bounded server-side batches until it is complete.":
    "Aktiviert dauerhaft nur anfügbare Datensatzversionen. Der Befehl setzt die anfängliche Ausgangsbasis in begrenzten serverseitigen Stapeln fort, bis sie vollständig ist.",
  "Ensure the form has a public submit token": "Sicherstellen, dass das Formular ein öffentliches Übermittlungstoken hat",
  "Events in one page (default: 50)": "Ereignisse auf einer Seite (Standard: 50)",
  "Events per page (default: 50)": "Ereignisse pro Seite (Standard: 50)",
  "Evidence export public ID": "Öffentliche ID des Nachweisexports",
  "Exact Base name": "Exakter Name der Basis",
  "Exact operational failure UUID returned by record-events failures": "Exakte UUID des Betriebsfehlers aus record-events failures",
  "Exclusive ISO timestamp": "ISO-Zeitstempel (exklusiv)",
  "Execute a GQL query": "Eine GQL-Abfrage ausführen",
  "Existing Record public ID to edit instead of creating; requires --yes and a versioned body":
    "Öffentliche ID eines bestehenden Datensatzes, der bearbeitet statt neu erstellt wird; erfordert --yes und einen versionierten Body",
  "Existing file public ID": "Öffentliche ID der bestehenden Datei",
  "Expected SHA-256 of manifest.json": "Erwarteter SHA-256 von manifest.json",
  "Expected SHA-256 of the complete TAR": "Erwarteter SHA-256 des vollständigen TAR",
  "Export an App definition as deterministic YAML": "Eine App-Definition als deterministisches YAML exportieren",
  "Export format (default: csv)": "Exportformat (Standard: csv)",
  "Export records to CSV or JSON": "Datensätze als CSV oder JSON exportieren",
  "Export the current live definition instead of the draft": "Die aktuelle Live-Definition statt des Entwurfs exportieren",
  "Exports through the backend export endpoint. Pass --body/--body-file for full ExportBody control, or use --format with the default table query.":
    "Exportiert über den Export-Endpunkt des Backends. Übergib --body/--body-file für volle Kontrolle über ExportBody oder nutze --format mit der Standardabfrage der Tabelle.",
  "External resource kind": "Art der externen Ressource",
  "External system or connector name": "Name des externen Systems oder Connectors",
  "Field config JSON object": "JSON-Objekt mit der Feldkonfiguration",
  "Field description": "Beschreibung des Felds",
  "Field name": "Name des Felds",
  "Field public id": "Öffentliche ID des Felds",
  "Field public id or exact name": "Öffentliche ID oder exakter Name des Felds",
  "Field type": "Feldtyp",
  "Field type, for example text, number, relation, formula": "Feldtyp, zum Beispiel text, number, relation, formula",
  "File field public ID from runtime read": "Öffentliche ID des Dateifelds aus runtime read",
  "File field public id or exact name": "Öffentliche ID oder exakter Name des Dateifelds",
  "File public id": "Öffentliche ID der Datei",
  "File public id from the version": "Öffentliche ID der Datei aus der Version",
  "Filter by Table public id or exact name; requires --scope table":
    "Nach öffentlicher ID oder exaktem Namen der Tabelle filtern; erfordert --scope table",
  "Filter by lifecycle action": "Nach Lebenszyklusaktion filtern",
  "Filter by record public id": "Nach öffentlicher ID des Datensatzes filtern",
  "Filter by relation Field public ID": "Nach öffentlicher ID des Relationsfelds filtern",
  "Filter by source reference from a previous page": "Nach Quellreferenz von einer vorherigen Seite filtern",
  "Filters combine. --workflow matches every Document of its runs; --table matches only Documents bound directly to one of its records, not source records or ZIP contents. Keep --sort when passing a cursor.":
    "Filter werden kombiniert. --workflow trifft jedes Dokument seiner Läufe; --table trifft nur Dokumente, die direkt an einen ihrer Datensätze gebunden sind, nicht Quelldatensätze oder ZIP-Inhalte. Behalte --sort bei, wenn du einen Cursor übergibst.",
  "Finalization mode: direct or four-eyes": "Finalisierungsmodus: direct oder four-eyes",
  "Finalization request public id": "Öffentliche ID der Finalisierungsanfrage",
  "Finalize a record and make it permanently read-only": "Einen Datensatz finalisieren und dauerhaft schreibschützen",
  "Folder path such as 2026/07": "Ordnerpfad wie 2026/07",
  "Follow cursors until the feed ends or --max-events is reached": "Cursorn folgen, bis der Feed endet oder --max-events erreicht ist",
  "Follow result cursors until the query ends or --max-rows is reached":
    "Ergebnis-Cursorn folgen, bis die Abfrage endet oder --max-rows erreicht ist",
  "Form config JSON object": "JSON-Objekt mit der Formularkonfiguration",
  "Form config fields use field public ids. Run `cld grids fields list <base>:<table>` and `cld grids records shape <base>:<table>` first.":
    "Felder der Formularkonfiguration verwenden öffentliche Feld-IDs. Führe zuerst `cld grids fields list <base>:<table>` und `cld grids records shape <base>:<table>` aus.",
  "Form name": "Name des Formulars",
  "Form position": "Position des Formulars",
  "Form public id": "Öffentliche ID des Formulars",
  "Form public id or exact name": "Öffentliche ID oder exakter Name des Formulars",
  "Formula fields, GQL predicates, computed columns, and parts of document/workflow authoring use this expression model.":
    "Formelfelder, GQL-Prädikate, berechnete Spalten und Teile der Dokument- und Workflow-Erstellung verwenden dieses Ausdrucksmodell.",
  "Free-text record search": "Freitextsuche in Datensätzen",
  "Freeze all record changes when --allow none is used": "Alle Datensatzänderungen einfrieren, wenn --allow none verwendet wird",
  "Frozen provenance: each packaged path, its size, and the Document artifact it came from.":
    "Eingefrorene Herkunft: jeder verpackte Pfad, seine Größe und das Dokumentartefakt, aus dem er stammt.",
  "GQL source": "GQL-Quelle",
  "GQL source for the table query": "GQL-Quelle für die Tabellenabfrage",
  "Generate and store an immutable Document": "Ein unveränderliches Dokument erzeugen und speichern",
  "Generate, browse, and manage stored documents": "Gespeicherte Dokumente erzeugen, durchsuchen und verwalten",
  "Generated document tag. Repeatable.": "Tag des erzeugten Dokuments. Wiederholbar.",
  "Grids App YAML or JSON definition": "YAML- oder JSON-Definition der Grids App",
  "Grids base public id or exact name": "Öffentliche ID oder exakter Name der Grids-Basis",
  "Grids' view of the run: which workflow and revision, what asked for it, and how it ended. `cld admin workflows show <run-id>` adds the kernel's side — the event that caused it, its effect budget, and any child runs.":
    "Die Sicht von Grids auf den Lauf: welcher Workflow und welche Revision, was ihn angefordert hat und wie er endete. `cld admin workflows show <run-id>` ergänzt die Seite des Kernels – das auslösende Ereignis, sein Effektbudget und etwaige Kindläufe.",
  "Group id or exact name": "Gruppen-ID oder exakter Name",
  "Hide field in table views": "Feld in Tabellenansichten ausblenden",
  "Hold scope": "Bereich der Sperre",
  "Hold status": "Status der Sperre",
  "Import records atomically from JSON": "Datensätze atomar aus JSON importieren",
  "Include deleted records": "Gelöschte Datensätze einbeziehen",
  "Inclusive ISO timestamp": "ISO-Zeitstempel (inklusiv)",
  "Independently upsert a bounded batch by external identity":
    "Einen begrenzten Stapel unabhängig anhand externer Identität anlegen oder aktualisieren",
  "Inspect and control workflow runs": "Workflow-Läufe prüfen und steuern",
  "Inspect and instantiate built-in base templates": "Integrierte Basisvorlagen prüfen und instanziieren",
  "Inspect and replay delivery failures as platform administrator": "Zustellfehler als Plattformadministrator prüfen und erneut einspielen",
  "Inspect available evidence and estimate an export without creating it":
    "Verfügbare Nachweise prüfen und einen Export abschätzen, ohne ihn zu erstellen",
  "Inspect email deliveries from workflow runs": "E-Mail-Zustellungen aus Workflow-Läufen prüfen",
  "Inspect the complete normalized financial export waiting for confirmation":
    "Den vollständigen normalisierten Finanzexport prüfen, der auf Bestätigung wartet",
  "Invoke a scanner, bulk, record, or customApp launcher": "Eine Ausführungsoption vom Typ scanner, bulk, record oder customApp aufrufen",
  "Invoke a workflow directly through the API": "Einen Workflow direkt über die API aufrufen",
  "Irreversible. Pass the exact Base name through --confirm. Eligibility and holds are rechecked before every File.":
    "Unumkehrbar. Übergib den exakten Namen der Basis mit --confirm. Eignung und Sperren werden vor jeder Datei erneut geprüft.",
  "Irreversibly enable durable history and capture its baseline":
    "Dauerhaften Verlauf unumkehrbar aktivieren und seine Ausgangsbasis erfassen",
  "Items per page": "Einträge pro Seite",
  "JSON object of page parameter names to Record public IDs":
    "JSON-Objekt, das Seitenparameternamen auf öffentliche Datensatz-IDs abbildet",
  "Launcher public id or exact name": "Öffentliche ID oder exakter Name der Ausführungsoption",
  "Liquid HTML body": "Liquid-HTML-Inhalt",
  "Liquid document number pattern": "Liquid-Muster für die Dokumentnummer",
  "Liquid filename pattern": "Liquid-Muster für den Dateinamen",
  "Liquid footer HTML": "Liquid-HTML für die Fußzeile",
  "Liquid header HTML": "Liquid-HTML für die Kopfzeile",
  "List 100 retained delivery failures as a platform administrator": "100 aufbewahrte Zustellfehler als Plattformadministrator auflisten",
  "List Apps in a base": "Apps einer Basis auflisten",
  "List Combined tables that publish a stored source table":
    "Kombinierte Tabellen auflisten, die eine gespeicherte Quelltabelle veröffentlichen",
  "List Grids bases": "Grids-Basen auflisten",
  "List all Grids field types and their record payload shape": "Alle Grids-Feldtypen und die Form ihrer Datensatz-Payload auflisten",
  "List and download unreferenced Files under a retention floor":
    "Nicht referenzierte Dateien unter einer Mindestaufbewahrung auflisten und herunterladen",
  "List built-in Grids base templates": "Integrierte Grids-Basisvorlagen auflisten",
  "List custom forms for a table": "Eigene Formulare einer Tabelle auflisten",
  "List deleted resources that can be restored in a base":
    "Gelöschte Ressourcen einer Basis auflisten, die wiederhergestellt werden können",
  "List direct grants for a Grids resource": "Direkte Freigaben einer Grids-Ressource auflisten",
  "List document templates for a table": "Dokumentvorlagen einer Tabelle auflisten",
  "List documents generated by a workflow run": "Von einem Workflow-Lauf erzeugte Dokumente auflisten",
  "List durable versions of one record": "Dauerhafte Versionen eines Datensatzes auflisten",
  "List fields in a table": "Felder einer Tabelle auflisten",
  "List files stored in one record file field": "In einem Dateifeld eines Datensatzes gespeicherte Dateien auflisten",
  "List generated documents for a document template": "Erzeugte Dokumente einer Dokumentvorlage auflisten",
  "List generated documents for one record": "Erzeugte Dokumente eines Datensatzes auflisten",
  "List immutable revisions of a workflow": "Unveränderliche Revisionen eines Workflows auflisten",
  "List installed Document renderers": "Installierte Dokument-Renderer auflisten",
  "List launchers attached to a workflow": "An einen Workflow angehängte Ausführungsoptionen auflisten",
  "List manual recursive snapshots for one record": "Manuelle rekursive Snapshots eines Datensatzes auflisten",
  "List preservation holds": "Erhaltungssperren auflisten",
  "List public links for a generated document": "Öffentliche Links eines erzeugten Dokuments auflisten",
  "List readable live records referencing one record": "Lesbare aktive Datensätze auflisten, die auf einen Datensatz verweisen",
  "List records in a table": "Datensätze einer Tabelle auflisten",
  "List retained evidence export requests in a Base": "Aufbewahrte Anfragen für Nachweisexporte einer Basis auflisten",
  "List revisions older than this revision": "Revisionen auflisten, die älter als diese Revision sind",
  "List source tables you may publish into a Combined table":
    "Quelltabellen auflisten, die du in eine kombinierte Tabelle veröffentlichen darfst",
  "List tables in a base": "Tabellen einer Basis auflisten",
  "List the files packaged in a ZIP Document": "Die in einem ZIP-Dokument verpackten Dateien auflisten",
  "List the frozen record associations of a Document": "Die eingefrorenen Datensatzzuordnungen eines Dokuments auflisten",
  "List trashed Records under a retention floor": "Datensätze im Papierkorb unter einer Mindestaufbewahrung auflisten",
  "List unreferenced Files under a retention floor": "Nicht referenzierte Dateien unter einer Mindestaufbewahrung auflisten",
  "List views for a table": "Ansichten einer Tabelle auflisten",
  "List workflow email deliveries visible on a base": "In einer Basis sichtbare E-Mail-Zustellungen von Workflows auflisten",
  "List workflow email templates for a base": "E-Mail-Vorlagen für Workflows einer Basis auflisten",
  "List workflow run steps": "Schritte eines Workflow-Laufs auflisten",
  "List workflow runs visible on a base": "In einer Basis sichtbare Workflow-Läufe auflisten",
  "List workflows visible on a base": "In einer Basis sichtbare Workflows auflisten",
  "List, create, and release preservation holds": "Erhaltungssperren auflisten, erstellen und aufheben",
  "List, search, filter and sort all Documents of a Base": "Alle Dokumente einer Basis auflisten, durchsuchen, filtern und sortieren",
  "Lists lifecycle events from the active Combined publication. Only canonical fields, declared audit answers, and safe source labels are returned.":
    "Listet Lebenszyklusereignisse aus der aktiven Veröffentlichung der kombinierten Tabelle auf. Zurückgegeben werden nur kanonische Felder, deklarierte Audit-Antworten und sichere Quellbezeichnungen.",
  "Local PDF output path": "Lokaler Ausgabepfad für das PDF",
  "Local file path": "Lokaler Dateipfad",
  "Local image output path": "Lokaler Ausgabepfad für das Bild",
  "Local upload path": "Lokaler Pfad der hochzuladenden Datei",
  "MIME type override": "MIME-Typ überschreiben",
  "Make the view personal": "Ansicht persönlich machen",
  "Make the view shared": "Ansicht teilen",
  "Manage Grids bases, schema, records, forms, Apps, views, GQL, documents, templates, and workflows through the Grids HTTP API.":
    "Grids-Basen, Schema, Datensätze, Formulare, Apps, Ansichten, GQL, Dokumente, Vorlagen und Workflows über die Grids-HTTP-API verwalten.",
  "Manage direct access to Grids resources": "Direkten Zugriff auf Grids-Ressourcen verwalten",
  "Mark field optional": "Feld als optional markieren",
  "Mark field required": "Feld als Pflichtfeld markieren",
  "Markdown export mode for long text fields": "Markdown-Exportmodus für lange Textfelder",
  "Maximum Documents": "Maximale Anzahl Dokumente",
  "Maximum deliveries": "Maximale Anzahl Zustellungen",
  "Maximum documents": "Maximale Anzahl an Dokumenten",
  "Maximum documents or folders": "Maximale Anzahl Dokumente oder Ordner",
  "Maximum exported rows": "Maximale Anzahl exportierter Zeilen",
  "Maximum preview rows": "Maximale Anzahl Vorschauzeilen",
  "Maximum results on this page": "Maximale Anzahl Ergebnisse auf dieser Seite",
  "Maximum revisions": "Maximale Anzahl Revisionen",
  "Maximum runs": "Maximale Anzahl Läufe",
  "Minimum effective permission": "Minimale effektive Berechtigung",
  "Minimum retention days": "Mindestaufbewahrung in Tagen",
  "Move a record to trash": "Einen Datensatz in den Papierkorb verschieben",
  "Move this record to trash": "Diesen Datensatz in den Papierkorb verschieben",
  "Name for the new base": "Name der neuen Basis",
  "Only Records in this Finalization state": "Nur Datensätze in diesem Finalisierungsstatus",
  "Only deleted records": "Nur gelöschte Datensätze",
  "Opaque nextCursor": "Opaker nextCursor",
  "Opaque nextCursor from the previous page": "Opaker nextCursor der vorherigen Seite",
  "Opaque token from the returned /files/<token> image URL": "Opakes Token aus der zurückgegebenen Bild-URL /files/<token>",
  "Optimistic version guard": "Optimistische Versionsprüfung",
  "Optional context for the approver": "Optionaler Kontext für die genehmigende Person",
  "Optional decision comment": "Optionaler Kommentar zur Entscheidung",
  "Optional generated filename override": "Optionaler Ersatz für den erzeugten Dateinamen",
  "Optional leading base followed by command arguments.": "Optionale vorangestellte Basis, gefolgt von Befehlsargumenten.",
  "Optional link comment": "Optionaler Kommentar zum Link",
  "Output PDF path": "Ausgabepfad für das PDF",
  "Output file path": "Ausgabedateipfad",
  "Output path": "Ausgabepfad",
  "Output path (.pdf when every document is a PDF, otherwise .zip)": "Ausgabepfad (.pdf, wenn alle Dokumente PDFs sind, sonst .zip)",
  "Page CSS": "Seiten-CSS",
  "Page ID from apps runtime read": "Seiten-ID aus apps runtime read",
  "Page ID; defaults to the published home page": "Seiten-ID; standardmäßig die veröffentlichte Startseite",
  "Page number": "Seitennummer",
  "Page offset": "Seiten-Offset",
  "Page size, maximum 100": "Seitengröße, höchstens 100",
  "Pagination cursor": "Cursor für die Seitennavigation",
  'Pass a JSON array, or {"items":[...]}, where each item is a record payload keyed by field public id. The backend creates all records in one transaction.':
    'Übergib ein JSON-Array oder {"items":[...]}, wobei jedes Element eine nach öffentlicher Feld-ID geschlüsselte Datensatz-Payload ist. Das Backend erstellt alle Datensätze in einer Transaktion.',
  "Pass a JSON object keyed by field public id. Run `cld grids records shape <base>:<table>` first for the exact writable keys.":
    "Übergib ein nach öffentlicher Feld-ID geschlüsseltes JSON-Objekt. Führe zuerst `cld grids records shape <base>:<table>` aus, um die exakten beschreibbaren Schlüssel zu erhalten.",
  'Pass a partial create JSON object, for example {"name":"New label"}, {"enabled":false}, or {"config":{"kind":"bulk","input":"items"}}. Run `cld grids workflows reference` for config shapes.':
    'Übergib ein teilweises Create-JSON-Objekt, zum Beispiel {"name":"New label"}, {"enabled":false} oder {"config":{"kind":"bulk","input":"items"}}. Führe `cld grids workflows reference` aus, um die Formen von config zu sehen.',
  "Pass a table and draft body, or also pass a saved template to use its source/html/header/footer/page CSS defaults before applying overrides.":
    "Übergib eine Tabelle und einen Entwurfs-Body oder zusätzlich eine gespeicherte Vorlage, um deren Standardwerte für source/html/header/footer/Seiten-CSS zu verwenden, bevor Überschreibungen angewendet werden.",
  "Pass field public IDs or {data,inlineCreates?,idempotencyKey?}. Reuse the exact body and key after an uncertain result. --record edits an existing record through the Form and requires --yes, version and idempotencyKey in the body; inlineUpdates use each child's recordId, version and data.":
    "Übergib öffentliche Feld-IDs oder {data,inlineCreates?,idempotencyKey?}. Verwende nach einem unsicheren Ergebnis exakt denselben Body und Schlüssel erneut. --record bearbeitet einen bestehenden Datensatz über das Formular und erfordert --yes sowie version und idempotencyKey im Body; inlineUpdates verwenden recordId, version und data des jeweiligen Kinddatensatzes.",
  'Pass one JSON object: scanner {"name":"Scan","config":{"kind":"scanner","inputSources":{"item":{"kind":"scan","value":"record","resolve":{"by":"scanCode"}}}},"enabled":true}; bulk {"name":"Bulk","config":{"kind":"bulk","input":"items"}}; correction {"name":"Create correction","config":{"kind":"record","input":"original","profile":"correctionDraft","intent":"correction"}}; cancellation uses the same Record profile with "intent":"cancellation"; fixed customApp {"name":"Refresh","config":{"kind":"customApp","inputMode":"fixed","inputBindings":{"range":"30d"}}}; prompt customApp {"name":"Run","config":{"kind":"customApp","inputMode":"prompt"}}. Run `cld grids workflows reference` for all shapes.':
    'Übergib ein JSON-Objekt: scanner {"name":"Scan","config":{"kind":"scanner","inputSources":{"item":{"kind":"scan","value":"record","resolve":{"by":"scanCode"}}}},"enabled":true}; bulk {"name":"Bulk","config":{"kind":"bulk","input":"items"}}; correction {"name":"Create correction","config":{"kind":"record","input":"original","profile":"correctionDraft","intent":"correction"}}; cancellation verwendet dasselbe Record-Profil mit "intent":"cancellation"; fixed customApp {"name":"Refresh","config":{"kind":"customApp","inputMode":"fixed","inputBindings":{"range":"30d"}}}; prompt customApp {"name":"Run","config":{"kind":"customApp","inputMode":"prompt"}}. Führe `cld grids workflows reference` aus, um alle Formen zu sehen.',
  'Pass {"items":[...]} with at most 100 items. Each item has its own idempotencyKey, externalRef, values, optional ifVersion, and optional audit. Items commit independently and run in order.':
    'Übergib {"items":[...]} mit höchstens 100 Elementen. Jedes Element hat einen eigenen idempotencyKey, externalRef, values, optional ifVersion und optional audit. Elemente werden unabhängig festgeschrieben und der Reihe nach ausgeführt.',
  "Pending Document receipt public id": "Öffentliche ID des ausstehenden Dokumentbelegs",
  "Permanently enable durable history for this table": "Dauerhaften Verlauf für diese Tabelle unwiderruflich aktivieren",
  "Permanently finalize this record": "Diesen Datensatz dauerhaft finalisieren",
  "Permission to grant": "Zu gewährende Berechtigung",
  "Permission to set": "Zu setzende Berechtigung",
  "Preview a GQL query with a smaller row cap": "Eine GQL-Abfrage mit kleinerer Zeilenobergrenze in der Vorschau anzeigen",
  "Preview a retention floor for a Grids base": "Vorschau einer Mindestaufbewahrung für eine Grids-Basis anzeigen",
  "Preview active entry points affected by a record change policy":
    "Vorschau der aktiven Einstiegspunkte anzeigen, die von einer Änderungsrichtlinie für Datensätze betroffen sind",
  "Preview bounded controlled File destruction": "Vorschau einer begrenzten kontrollierten Vernichtung von Dateien anzeigen",
  "Preview record public id": "Öffentliche ID des Datensatzes für die Vorschau",
  "Preview, run, and control bounded controlled File destruction":
    "Begrenzte kontrollierte Vernichtung von Dateien in der Vorschau anzeigen, ausführen und steuern",
  "Primary file media type, for example application/pdf": "Medientyp der Hauptdatei, zum Beispiel application/pdf",
  "Provider account or tenant identity": "Konto oder Mandantenidentität beim Anbieter",
  "Public link lifetime": "Gültigkeitsdauer des öffentlichen Links",
  "Publish a valid Combined table draft": "Einen gültigen Entwurf einer kombinierten Tabelle veröffentlichen",
  "Publish the current validated App draft": "Den aktuellen validierten App-Entwurf veröffentlichen",
  "Publish this App": "Diese App veröffentlichen",
  "Published App public ID from its URL; no Base access required":
    "Öffentliche ID der veröffentlichten App aus ihrer URL; kein Zugriff auf die Basis erforderlich",
  "Published Combined table public id": "Öffentliche ID der veröffentlichten kombinierten Tabelle",
  "Raw Grids access is granted on a base. Published Grids Apps have their own read access.":
    "Direkter Grids-Zugriff wird auf einer Basis gewährt. Veröffentlichte Grids Apps haben einen eigenen Lesezugriff.",
  "Read an evidence export status, hashes and coverage": "Status, Hashes und Abdeckung eines Nachweisexports lesen",
  "Read and interact with published Grids Apps": "Veröffentlichte Grids Apps lesen und mit ihnen interagieren",
  "Read and manage comments in published Apps": "Kommentare in veröffentlichten Apps lesen und verwalten",
  "Read and manage record discussion": "Diskussion zu Datensätzen lesen und verwalten",
  "Read and replace shared base navigation groups": "Geteilte Navigationsgruppen einer Basis lesen und ersetzen",
  "Read one bounded page of record comments and current permissions":
    "Eine begrenzte Seite mit Datensatzkommentaren und aktuellen Berechtigungen lesen",
  "Read one bounded records block page within its published scope":
    "Eine begrenzte Seite eines Datensatzblocks innerhalb seines veröffentlichten Bereichs lesen",
  "Read run status in the exact original published page/action scope":
    "Laufstatus im exakten ursprünglichen veröffentlichten Seiten- oder Aktionsbereich lesen",
  "Read shared navigation groups and their revision (base admin)": "Geteilte Navigationsgruppen und ihre Revision lesen (Basis-Admin)",
  "Reads the TAR locally without extracting or uploading it. Matching hashes prove byte agreement and declared coverage, not compliance, authorship, custody, or legal validity.":
    "Liest das TAR lokal, ohne es zu entpacken oder hochzuladen. Übereinstimmende Hashes belegen Byte-Gleichheit und die deklarierte Abdeckung, nicht Compliance, Urheberschaft, Verwahrung oder Rechtsgültigkeit.",
  "Record as <base>:<table>/<record id> or a record ID, or [base] <table> <record>; then command arguments.":
    "Datensatz als <basis>:<tabelle>/<datensatz-id> oder Datensatz-ID oder [basis] <tabelle> <datensatz>; danach Befehlsargumente.",
  "Record as <base>:<table>/<record id>, a record ID, or <table> <record>, then the comment public ID.":
    "Datensatz als <basis>:<tabelle>/<datensatz-id>, Datensatz-ID oder <tabelle> <datensatz>, danach die öffentliche ID des Kommentars.",
  "Record public id": "Öffentliche ID des Datensatzes",
  "Record revision public id": "Öffentliche ID der Datensatzrevision",
  "Records a grids.invoked event, which the workflow is always listening for. Inputs must be a JSON object. The idempotency key is scoped to this workflow: repeating it answers with the run it already started, and reusing it for a different mode, actor, or inputs is rejected as a conflict. A dry run is created against the workflow's newest version instead and plans its effects rather than performing them.":
    "Erfasst ein grids.invoked-Ereignis, auf das der Workflow immer hört. Die Eingaben müssen ein JSON-Objekt sein. Der Idempotenzschlüssel gilt für diesen Workflow: Eine Wiederholung liefert den bereits gestarteten Lauf, und die Wiederverwendung für einen anderen Modus, Akteur oder andere Eingaben wird als Konflikt abgelehnt. Ein Testlauf wird stattdessen gegen die neueste Version des Workflows erstellt und plant seine Effekte, statt sie auszuführen.",
  "Reject a Four-eyes Finalization request": "Eine Anfrage zur Vier-Augen-Finalisierung ablehnen",
  "Reject the pending Finalization request": "Die ausstehende Finalisierungsanfrage ablehnen",
  "Reject unless this workflow revision is active": "Ablehnen, wenn diese Workflow-Revision nicht aktiv ist",
  "Release one preservation hold": "Eine Erhaltungssperre aufheben",
  "Release this preservation hold": "Diese Erhaltungssperre aufheben",
  "Releasing one hold does not release any other active hold and does not delete data.":
    "Das Aufheben einer Sperre hebt keine andere aktive Sperre auf und löscht keine Daten.",
  "Remove one file attachment from the current record": "Einen Dateianhang aus dem aktuellen Datensatz entfernen",
  "Remove the live App snapshot while keeping its draft": "Den Live-Snapshot der App entfernen und ihren Entwurf behalten",
  "Remove the public submit token": "Öffentliches Übermittlungstoken entfernen",
  "Remove the retention floor": "Mindestaufbewahrung entfernen",
  "Remove the retention floor from a Grids base": "Mindestaufbewahrung einer Grids-Basis entfernen",
  "Remove this attachment from the current record": "Diesen Anhang aus dem aktuellen Datensatz entfernen",
  "Removing the floor may allow future controlled destruction earlier. It does not delete anything now.":
    "Das Entfernen der Mindestaufbewahrung kann künftige kontrollierte Vernichtung früher erlauben. Es löscht jetzt nichts.",
  "Render an unsaved document template draft PDF for one record":
    "Einen ungespeicherten Entwurf einer Dokumentvorlage für einen Datensatz als PDF rendern",
  "Render document template PDF preview for one record": "PDF-Vorschau einer Dokumentvorlage für einen Datensatz rendern",
  "Render document template preview data for one record": "Vorschaudaten einer Dokumentvorlage für einen Datensatz rendern",
  "Render unsaved document template draft data for one record":
    "Daten eines ungespeicherten Dokumentvorlagen-Entwurfs für einen Datensatz rendern",
  "Reorder fields in a table": "Felder einer Tabelle neu anordnen",
  "Replace and save a Combined table draft": "Einen Entwurf einer kombinierten Tabelle ersetzen und speichern",
  "Replace one record file attachment atomically": "Einen Dateianhang eines Datensatzes atomar ersetzen",
  "Replace or delete this file": "Diese Datei ersetzen oder löschen",
  "Replace ordered shared groups with revision conflict protection; removing references never deletes resources":
    "Geordnete geteilte Gruppen mit Schutz vor Revisionskonflikten ersetzen; das Entfernen von Verweisen löscht nie Ressourcen",
  "Replace this App draft with its live version": "Diesen App-Entwurf durch seine Live-Version ersetzen",
  "Replacement local file path": "Lokaler Pfad der Ersatzdatei",
  "Replay one retained stopped delivery as a platform administrator":
    "Eine aufbewahrte, gestoppte Zustellung als Plattformadministrator erneut einspielen",
  "Replay the retained event": "Das aufbewahrte Ereignis erneut einspielen",
  "Request Four-eyes Finalization for one exact Record version": "Vier-Augen-Finalisierung für eine exakte Datensatzversion anfordern",
  "Request an evidence export using the Base administrator permission":
    "Einen Nachweisexport mit der Administratorberechtigung der Basis anfordern",
  "Request cancellation of an evidence export": "Abbruch eines Nachweisexports anfordern",
  "Request inline disposition": "Inline-Disposition anfordern",
  "Request, approve, and reject Four-eyes record Finalization":
    "Vier-Augen-Finalisierung von Datensätzen anfordern, genehmigen und ablehnen",
  "Require Direct or Four-eyes Finalization for a table": "Direkte oder Vier-Augen-Finalisierung für eine Tabelle vorschreiben",
  "Require a deleted record": "Gelöschten Datensatz voraussetzen",
  "Required current Record version when the binding exists": "Erforderliche aktuelle Datensatzversion, wenn die Bindung existiert",
  "Required stable key for this logical invocation": "Erforderlicher stabiler Schlüssel für diesen logischen Aufruf",
  "Required stable retry key": "Erforderlicher stabiler Wiederholungsschlüssel",
  "Requires --yes only when shortening an existing floor. Saving never deletes Records or Files or starts cleanup.":
    "Erfordert --yes nur beim Verkürzen einer bestehenden Mindestaufbewahrung. Speichern löscht nie Datensätze oder Dateien und startet keine Bereinigung.",
  "Requires Base admin access and a File public id from `bases retention files list`.":
    "Erfordert Admin-Zugriff auf die Basis und eine öffentliche Datei-ID aus `bases retention files list`.",
  "Requires Base admin access. Preview never deletes data and returns at most 100 exact eligible File candidates.":
    "Erfordert Admin-Zugriff auf die Basis. Die Vorschau löscht nie Daten und liefert höchstens 100 exakte zulässige Dateikandidaten.",
  "Requires Base admin access. Search, status filtering, and pagination run on the server.":
    "Erfordert Admin-Zugriff auf die Basis. Suche, Statusfilter und Seitennavigation laufen auf dem Server.",
  "Requires Base admin access. Search, status, scope, table filtering, and pagination run on the server.":
    "Erfordert Admin-Zugriff auf die Basis. Suche, Filter nach Status, Bereich und Tabelle sowie Seitennavigation laufen auf dem Server.",
  "Requires Base admin access. The hold blocks future controlled destruction only in its selected scope.":
    "Erfordert Admin-Zugriff auf die Basis. Die Sperre blockiert künftige kontrollierte Vernichtung nur in ihrem gewählten Bereich.",
  "Requires admin access to the source base. The result includes the exact mapped field scope and revocation status.":
    "Erfordert Admin-Zugriff auf die Quellbasis. Das Ergebnis enthält den exakten zugeordneten Feldumfang und den Widerrufsstatus.",
  "Requires base admin access. Parent tables contain their own deleted fields and forms, so nested items are not duplicated.":
    "Erfordert Admin-Zugriff auf die Basis. Übergeordnete Tabellen enthalten ihre eigenen gelöschten Felder und Formulare, daher werden verschachtelte Elemente nicht doppelt aufgeführt.",
  "Requires base admin access. The floor preserves trashed Records and newly unreferenced Files without deleting data.":
    "Erfordert Admin-Zugriff auf die Basis. Die Mindestaufbewahrung bewahrt Datensätze im Papierkorb und neu nicht referenzierte Dateien auf, ohne Daten zu löschen.",
  "Requires only admin access to the source base; target-table is the Combined table public id shown by the publications command.":
    "Erfordert nur Admin-Zugriff auf die Quellbasis; target-table ist die öffentliche ID der kombinierten Tabelle, die der Befehl publications anzeigt.",
  "Requires the hash returned by preview-export and --yes. Never fetches a new preview hash implicitly. An explicit query limit is part of the confirmed selection.":
    "Erfordert den von preview-export gelieferten Hash und --yes. Holt nie implizit einen neuen Vorschau-Hash. Ein ausdrückliches Abfragelimit ist Teil der bestätigten Auswahl.",
  "Resource type followed by refs, e.g. base Bookshop or app Bookshop Catalog.":
    "Ressourcentyp, gefolgt von Referenzen, z. B. base Bookshop oder app Bookshop Catalog.",
  "Resource type followed by resource refs.": "Ressourcentyp, gefolgt von Ressourcenreferenzen.",
  "Restore a deleted Grids base": "Eine gelöschte Grids-Basis wiederherstellen",
  "Restore a deleted field by public id": "Ein gelöschtes Feld anhand der öffentlichen ID wiederherstellen",
  "Restore a deleted form by public id": "Ein gelöschtes Formular anhand der öffentlichen ID wiederherstellen",
  "Restore a deleted table by public id": "Eine gelöschte Tabelle anhand der öffentlichen ID wiederherstellen",
  "Restore a deleted view by public id": "Eine gelöschte Ansicht anhand der öffentlichen ID wiederherstellen",
  "Restore a record from trash": "Einen Datensatz aus dem Papierkorb wiederherstellen",
  "Restore an earlier workflow revision as a new revision": "Eine frühere Workflow-Revision als neue Revision wiederherstellen",
  "Restore the live App definition as the current draft": "Die Live-Definition der App als aktuellen Entwurf wiederherstellen",
  "Restore this workflow revision": "Diese Workflow-Revision wiederherstellen",
  "Resume cursor from the previous page": "Fortsetzungs-Cursor der vorherigen Seite",
  "Resume recent Record changes in a Base": "Jüngste Datensatzänderungen einer Basis fortsetzen",
  "Retention floor status": "Status der Mindestaufbewahrung",
  "Retry a failed evidence export": "Einen fehlgeschlagenen Nachweisexport erneut versuchen",
  "Return full templates; requires table admin access": "Vollständige Vorlagen zurückgeben; erfordert Admin-Zugriff auf die Tabelle",
  "Return permission-safe GQL autocomplete items": "Berechtigungssichere GQL-Autovervollständigungen zurückgeben",
  "Return permission-safe workflow YAML autocomplete items": "Berechtigungssichere Autovervollständigungen für Workflow-YAML zurückgeben",
  "Returns a bounded impact at one observation time. Reaching the floor never deletes a Record or File.":
    "Liefert eine begrenzte Auswirkung zu einem Beobachtungszeitpunkt. Das Erreichen der Mindestaufbewahrung löscht nie einen Datensatz oder eine Datei.",
  "Returns public Record identities and versions from the last 30 days. Save the cursor and read current Record values separately.":
    "Liefert öffentliche Datensatzidentitäten und -versionen der letzten 30 Tage. Speichere den Cursor und lies aktuelle Datensatzwerte separat.",
  "Revision to restore": "Wiederherzustellende Revision",
  "Revoke a direct Grids resource grant": "Eine direkte Freigabe für eine Grids-Ressource widerrufen",
  "Revoke a public document link": "Einen öffentlichen Dokumentlink widerrufen",
  "Revoke a stored source from a published Combined table":
    "Eine gespeicherte Quelle aus einer veröffentlichten kombinierten Tabelle widerrufen",
  "Revoke this source publication": "Diese Quellveröffentlichung widerrufen",
  "Row limit (default: 100)": "Zeilenlimit (Standard: 100)",
  "Rows in one result page": "Zeilen pro Ergebnisseite",
  "Run `cld grids document-templates reference` for Liquid variables, GQL source shape, and filename/number patterns.":
    "Führe `cld grids document-templates reference` aus, um Liquid-Variablen, die Form der GQL-Quelle und Muster für Dateinamen und Nummern zu sehen.",
  "Run `cld grids email-templates reference` for available fields, Liquid data, and a sendEmail workflow example.":
    "Führe `cld grids email-templates reference` aus, um verfügbare Felder, Liquid-Daten und ein sendEmail-Workflow-Beispiel zu sehen.",
  "Run `cld grids fields types` or `cld grids fields type <type>` to inspect valid field types and config JSON.":
    "Führe `cld grids fields types` oder `cld grids fields type <type>` aus, um gültige Feldtypen und Konfigurations-JSON zu prüfen.",
  "Run `cld grids workflows reference` for YAML structure, triggers, steps, and examples.":
    "Führe `cld grids workflows reference` aus, um YAML-Struktur, Auslöser, Schritte und Beispiele zu sehen.",
  "Run a structured table query": "Eine strukturierte Tabellenabfrage ausführen",
  "Run an available published action; reuse operationId when retrying":
    "Eine verfügbare veröffentlichte Aktion ausführen; bei Wiederholung operationId erneut verwenden",
  "Run public ID returned by the operation": "Öffentliche ID des Laufs, die die Operation zurückgibt",
  "Run state": "Laufstatus",
  "Run this action": "Diese Aktion ausführen",
  "Runs of this base's workflows, newest first. --status takes run states only — a run succeeds where a step completes, so see `workflow-runs steps` for the step vocabulary. Use `cld admin workflows` for the kernel-wide view across every app, the event that caused a run, and its effect budget.":
    "Läufe der Workflows dieser Basis, neueste zuerst. --status akzeptiert nur Laufstatus – ein Lauf ist erfolgreich, wo ein Schritt abgeschlossen ist; das Vokabular der Schritte zeigt `workflow-runs steps`. Nutze `cld admin workflows` für die Kernel-weite Sicht über alle Apps, das Ereignis, das einen Lauf ausgelöst hat, und sein Effektbudget.",
  "SHA-256 returned by the reviewed preview": "SHA-256 aus der geprüften Vorschau",
  "Safety cap for --all (default: 10000)": "Sicherheitsobergrenze für --all (Standard: 10000)",
  "Sample records are included by default. Pass --empty to create the complete template without sample records.":
    "Beispieldatensätze sind standardmäßig enthalten. Übergib --empty, um die vollständige Vorlage ohne Beispieldatensätze zu erstellen.",
  "Save the existing record through this form": "Den bestehenden Datensatz über dieses Formular speichern",
  "Scan using operationId, expectedRevision, scannedText and prompt inputs":
    "Mit operationId, expectedRevision, scannedText und Prompt-Eingaben scannen",
  "Search Record id, Table id, or Table name": "Datensatz-ID, Tabellen-ID oder Tabellenname durchsuchen",
  "Search bases": "Basen durchsuchen",
  "Search displayed fields": "Angezeigte Felder durchsuchen",
  "Search filename or File public id": "Dateiname oder öffentliche Datei-ID durchsuchen",
  "Search filename, document number, or tags": "Dateiname, Dokumentnummer oder Tags durchsuchen",
  "Search generated document filename, number, or tags": "Dateiname, Nummer oder Tags erzeugter Dokumente durchsuchen",
  "Search reason, Table name, creator, or hold ID": "Grund, Tabellenname, Ersteller oder Sperren-ID durchsuchen",
  "Search source bases and tables": "Quellbasen und -tabellen durchsuchen",
  "Search text; exact names are safest for grant/set commands.": "Suchtext; für die Befehle grant/set sind exakte Namen am sichersten.",
  "Search users, groups, and service accounts for grants": "Personen, Gruppen und Dienstkonten für Freigaben suchen",
  "Service account id or exact name": "Dienstkonto-ID oder exakter Name",
  "Service account id or exact name; Base grants only": "Dienstkonto-ID oder exakter Name; nur für Freigaben auf Basen",
  "Set the default Grids base": "Standard-Grids-Basis festlegen",
  "Set the retention floor for a Grids base": "Mindestaufbewahrung für eine Grids-Basis festlegen",
  "Set where a table's record changes may start": "Festlegen, wo Datensatzänderungen einer Tabelle beginnen dürfen",
  "Shorten the existing retention floor": "Bestehende Mindestaufbewahrung verkürzen",
  "Show Grids Query Language syntax, refs, and examples": "Syntax, Referenzen und Beispiele der Grids Query Language anzeigen",
  "Show Grids formula syntax and function reference": "Syntax und Funktionsreferenz der Grids-Formeln anzeigen",
  "Show Grids resource access levels": "Zugriffsstufen für Grids-Ressourcen anzeigen",
  "Show a Document and its artifacts": "Ein Dokument und seine Artefakte anzeigen",
  "Show a Grids base": "Eine Grids-Basis anzeigen",
  "Show a document template": "Eine Dokumentvorlage anzeigen",
  "Show a field": "Ein Feld anzeigen",
  "Show a form": "Ein Formular anzeigen",
  "Show a record": "Einen Datensatz anzeigen",
  "Show a table": "Eine Tabelle anzeigen",
  "Show a table's durable history status": "Status des dauerhaften Verlaufs einer Tabelle anzeigen",
  "Show a table's record finalization status": "Finalisierungsstatus der Datensätze einer Tabelle anzeigen",
  "Show a view": "Eine Ansicht anzeigen",
  "Show a workflow": "Einen Workflow anzeigen",
  "Show a workflow email template": "Eine E-Mail-Vorlage für Workflows anzeigen",
  "Show a workflow run": "Einen Workflow-Lauf anzeigen",
  "Show an App": "Eine App anzeigen",
  "Show document template fields, Liquid data, and examples": "Felder, Liquid-Daten und Beispiele für Dokumentvorlagen anzeigen",
  "Show field dependents": "Abhängige Elemente eines Felds anzeigen",
  "Show field in table views": "Feld in Tabellenansichten anzeigen",
  "Show one controlled destruction run": "Einen Lauf der kontrollierten Vernichtung anzeigen",
  "Show one field type reference": "Referenz für einen Feldtyp anzeigen",
  "Show one record snapshot": "Einen Datensatz-Snapshot anzeigen",
  "Show record audit entries": "Audit-Einträge eines Datensatzes anzeigen",
  "Show the JSON payload shape for records in a table": "Die JSON-Payload-Form für Datensätze einer Tabelle anzeigen",
  "Show the default Grids base": "Standard-Grids-Basis anzeigen",
  "Show the deterministic changes for a Grids App definition": "Die deterministischen Änderungen einer Grids-App-Definition anzeigen",
  "Show the draft and published revision of a Combined table": "Entwurf und veröffentlichte Revision einer kombinierten Tabelle anzeigen",
  "Show the plan without changing the draft": "Plan anzeigen, ohne den Entwurf zu ändern",
  "Show the retention floor for a Grids base": "Mindestaufbewahrung einer Grids-Basis anzeigen",
  "Show the strict Grids App definition reference": "Die strikte Referenz für Grids-App-Definitionen anzeigen",
  "Show the virtual default form for a table": "Das virtuelle Standardformular einer Tabelle anzeigen",
  "Show where a table's record changes may start": "Anzeigen, wo Datensatzänderungen einer Tabelle beginnen dürfen",
  "Show workflow YAML, invocation, and launcher JSON reference":
    "Referenz für Workflow-YAML, Aufrufe und JSON der Ausführungsoptionen anzeigen",
  "Show workflow email template fields, Liquid data, and examples":
    "Felder, Liquid-Daten und Beispiele für E-Mail-Vorlagen von Workflows anzeigen",
  "Shows the frozen destination, mapped rows, data timestamp and confirmation hash. Does not create or submit a file. Use --json for structured data.":
    "Zeigt das eingefrorene Ziel, zugeordnete Zeilen, den Datenzeitstempel und den Bestätigungs-Hash. Erstellt oder übermittelt keine Datei. Nutze --json für strukturierte Daten.",
  "Sidebar action ID from runtime read": "Aktions-ID der Seitenleiste aus runtime read",
  "Signed-in users": "Angemeldete Personen",
  "Snapshot public id": "Öffentliche ID des Snapshots",
  "Sort order": "Sortierreihenfolge",
  "Stable id in the external system": "Stabile ID im externen System",
  "Stable key for this logical create or update request": "Stabiler Schlüssel für diese logische Erstellungs- oder Aktualisierungsanfrage",
  "Start the currently previewed controlled File destruction batch":
    "Den aktuell in der Vorschau angezeigten Stapel der kontrollierten Dateivernichtung starten",
  "Stored filename override": "Gespeicherten Dateinamen überschreiben",
  "Submit a form": "Ein Formular absenden",
  "Submit an available sidebar form": "Ein verfügbares Seitenleistenformular absenden",
  "Submit the discovered form values": "Die ermittelten Formularwerte absenden",
  "Submit this form": "Dieses Formular absenden",
  "Table as <base>:<table>, or an optional leading base and the table ID or name; then command arguments.":
    "Tabelle als <basis>:<tabelle> oder eine optionale vorangestellte Basis und die Tabellen-ID oder den Tabellennamen; danach Befehlsargumente.",
  "Table description": "Beschreibung der Tabelle",
  "Table icon class": "Icon-Klasse der Tabelle",
  "Table kind: stored or federated (Combined table)": "Tabellenart: stored oder federated (kombinierte Tabelle)",
  "Table name": "Name der Tabelle",
  "Table name or public id of the directly bound record": "Tabellenname oder öffentliche ID des direkt gebundenen Datensatzes",
  "Table public id": "Öffentliche ID der Tabelle",
  "Table public id or exact name": "Öffentliche ID oder exakter Name der Tabelle",
  "Table public id or exact name; required for --scope table":
    "Öffentliche ID oder exakter Name der Tabelle; erforderlich für --scope table",
  "Tag filter. Repeatable.": "Tag-Filter. Wiederholbar.",
  "Template description": "Beschreibung der Vorlage",
  "Template id or exact name": "Vorlagen-ID oder exakter Name",
  "Template name": "Name der Vorlage",
  "Template position": "Position der Vorlage",
  'The body uses exact names or public ids: {"sources":[{"base":"East","table":"Items","mappings":[{"target":"Name","source":"Title"}]}]}.':
    'Der Body verwendet exakte Namen oder öffentliche IDs: {"sources":[{"base":"East","table":"Items","mappings":[{"target":"Name","source":"Title"}]}]}.',
  "The create/update payload is a plain JSON object keyed by field public id. This command resolves the table and lists writable fields with examples.":
    "Die Payload für create/update ist ein einfaches, nach öffentlicher Feld-ID geschlüsseltes JSON-Objekt. Dieser Befehl löst die Tabelle auf und listet beschreibbare Felder mit Beispielen auf.",
  "The policy is enforced by the server for direct changes, Forms, Actions, Workflows, API, and CLI. Use the impact command before removing a source.":
    "Der Server setzt die Richtlinie für direkte Änderungen, Formulare, Aktionen, Workflows, API und CLI durch. Nutze den Befehl impact, bevor du eine Quelle entfernst.",
  "The provider, provider account, resource kind, and external id form one durable identity. Reuse the idempotency key for an uncertain retry. Updating an existing binding requires --if-version.":
    "Anbieter, Anbieterkonto, Ressourcenart und externe ID bilden eine dauerhafte Identität. Verwende den Idempotenzschlüssel bei einer unsicheren Wiederholung erneut. Das Aktualisieren einer bestehenden Bindung erfordert --if-version.",
  'The saved launcher kind selects the endpoint. Pass the exact JSON body: scanner {"operationId":"scan-42","mode":"execute","expectedRevision":3,"scannedText":"gsc_opaque","inputs":{}}; bulk uses either "recordIds":[public-id,...] or "query":{...}; record uses {"operationId":"record-42","mode":"execute","expectedRevision":3,"recordId":"Rec001","inputs":{}}; customApp uses {"operationId":"customApp-42","mode":"execute","expectedRevision":3,"inputs":{...}}. Run `cld grids workflows reference` for complete shapes.':
    'Die gespeicherte Art der Ausführungsoption bestimmt den Endpunkt. Übergib den exakten JSON-Body: scanner {"operationId":"scan-42","mode":"execute","expectedRevision":3,"scannedText":"gsc_opaque","inputs":{}}; bulk verwendet entweder "recordIds":[public-id,...] oder "query":{...}; record verwendet {"operationId":"record-42","mode":"execute","expectedRevision":3,"recordId":"Rec001","inputs":{}}; customApp verwendet {"operationId":"customApp-42","mode":"execute","expectedRevision":3,"inputs":{...}}. Führe `cld grids workflows reference` aus, um vollständige Formen zu sehen.',
  "This is the compact CLI reference. For a permission-safe base-specific assistant bundle, use `cld grids gql skill` and `cld grids gql context`.":
    "Dies ist die kompakte CLI-Referenz. Für ein berechtigungssicheres, basisspezifisches Assistenten-Paket nutze `cld grids gql skill` und `cld grids gql context`.",
  "UTF-16 caret offset": "UTF-16-Offset der Einfügemarke",
  "Unpublish this App": "Veröffentlichung dieser App aufheben",
  "Update a Grids base": "Eine Grids-Basis aktualisieren",
  "Update a document template": "Eine Dokumentvorlage aktualisieren",
  "Update a field": "Ein Feld aktualisieren",
  "Update a form": "Ein Formular aktualisieren",
  "Update a record": "Einen Datensatz aktualisieren",
  "Update a table": "Eine Tabelle aktualisieren",
  "Update a view": "Eine Ansicht aktualisieren",
  "Update a workflow": "Einen Workflow aktualisieren",
  "Update a workflow email template": "Eine E-Mail-Vorlage für Workflows aktualisieren",
  "Update and revalidate a workflow launcher": "Eine Workflow-Ausführungsoption aktualisieren und erneut validieren",
  "Update the published editable fields with values and optional audit answers":
    "Die veröffentlichten bearbeitbaren Felder mit Werten und optionalen Audit-Antworten aktualisieren",
  "Upload a local file into one record file field": "Eine lokale Datei in ein Dateifeld eines Datensatzes hochladen",
  "Upload, download, and manage files in published Apps": "Dateien in veröffentlichten Apps hochladen, herunterladen und verwalten",
  "Upload, download, and manage record files": "Datensatzdateien hochladen, herunterladen und verwalten",
  'Use exact names or public ids: {"sources":[{"base":"East","table":"Items","mappings":[{"target":"Name","source":"Title"},{"target":"Status","source":"State","options":{"In stock":"Available"}}]}]}.':
    'Verwende exakte Namen oder öffentliche IDs: {"sources":[{"base":"East","table":"Items","mappings":[{"target":"Name","source":"Title"},{"target":"Status","source":"State","options":{"In stock":"Available"}}]}]}.',
  "Use field as record label": "Feld als Datensatzbezeichnung verwenden",
  "Use the new base as default": "Neue Basis als Standard verwenden",
  "Use the new base as the default Grids base": "Neue Basis als Standard-Grids-Basis verwenden",
  "Use this before creating fields or writing record JSON. Machine-readable output is available with --json.":
    "Nutze dies, bevor du Felder erstellst oder Datensatz-JSON schreibst. Maschinenlesbare Ausgabe gibt es mit --json.",
  "Use this before creating or updating document templates from an agent.":
    "Nutze dies, bevor du aus einem Agenten Dokumentvorlagen erstellst oder aktualisierst.",
  "Use this before creating workflow email templates from an agent.":
    "Nutze dies, bevor du aus einem Agenten E-Mail-Vorlagen für Workflows erstellst.",
  "Use this before creating, invoking, or attaching launchers to workflows from an agent.":
    "Nutze dies, bevor du aus einem Agenten Ausführungsoptionen erstellst, aufrufst oder an Workflows anhängst.",
  "User id, uid, email, or exact display name": "Benutzer-ID, uid, E-Mail oder exakter Anzeigename",
  "Validate a Combined table configuration without saving it":
    "Die Konfiguration einer kombinierten Tabelle validieren, ohne sie zu speichern",
  "Validate a formula and preview latest table records":
    "Eine Formel validieren und die neuesten Datensätze der Tabelle in der Vorschau anzeigen",
  "Validate and compile a Grids App definition without saving it":
    "Eine Grids-App-Definition validieren und kompilieren, ohne sie zu speichern",
  "Validate formulas and inspect the formula reference": "Formeln validieren und die Formelreferenz prüfen",
  "Validate workflow YAML": "Workflow-YAML validieren",
  "Verify a downloaded Grids evidence package offline": "Ein heruntergeladenes Grids-Nachweispaket offline prüfen",
  "Verify downloaded evidence packages": "Heruntergeladene Nachweispakete prüfen",
  "Versions per page (default: 20)": "Versionen pro Seite (Standard: 20)",
  "View description": "Beschreibung der Ansicht",
  "View icon class": "Icon-Klasse der Ansicht",
  "View name": "Name der Ansicht",
  "View public id": "Öffentliche ID der Ansicht",
  "View public id or exact name": "Öffentliche ID oder exakter Name der Ansicht",
  "Visible block ID from apps runtime read": "ID eines sichtbaren Blocks aus apps runtime read",
  "What asked for the run": "Was den Lauf angefordert hat",
  "Why this hold is being released": "Warum diese Sperre aufgehoben wird",
  "Why this scope must be preserved": "Warum dieser Bereich erhalten werden muss",
  "With --access-id this patches that grant. Otherwise the CLI resolves the principal and updates or creates its direct grant.":
    "Mit --access-id wird diese Freigabe geändert. Andernfalls löst die CLI den Principal auf und aktualisiert oder erstellt seine direkte Freigabe.",
  "Workflow description": "Beschreibung des Workflows",
  "Workflow name": "Name des Workflows",
  "Workflow position": "Position des Workflows",
  "Workflow public id": "Öffentliche ID des Workflows",
  "Workflow public id or exact name": "Öffentliche ID oder exakter Name des Workflows",
  "Workflow run public id": "Öffentliche ID des Workflow-Laufs",
  "Write YAML to this file": "YAML in diese Datei schreiben",
  "Write to file instead of stdout": "In eine Datei statt nach stdout schreiben",
  "cancel the evidence export": "den Nachweisexport abbrechen",
  "create comments in a published comments block": "Kommentare in einem veröffentlichten Kommentarblock erstellen",
  "delete comments in a published comments block": "Kommentare in einem veröffentlichten Kommentarblock löschen",
  "delete files in a published record block": "Dateien in einem veröffentlichten Datensatzblock löschen",
  "download files in a published record block": "Dateien in einem veröffentlichten Datensatzblock herunterladen",
  "execute performs the run; dryRun plans it": "execute führt den Lauf aus; dryRun plant ihn",
  "list comments in a published comments block": "Kommentare in einem veröffentlichten Kommentarblock auflisten",
  "list files in a published record block": "Dateien in einem veröffentlichten Datensatzblock auflisten",
  "nextOffset returned by the previous page": "nextOffset der vorherigen Seite",
  "replace files in a published record block": "Dateien in einem veröffentlichten Datensatzblock ersetzen",
  "retry the evidence export": "den Nachweisexport erneut versuchen",
  "update comments in a published comments block": "Kommentare in einem veröffentlichten Kommentarblock aktualisieren",
  "upload files in a published record block": "Dateien in einem veröffentlichten Datensatzblock hochladen",
};
