import { i18n } from "@k2b/stdlib";

export const capabilityRuntimeMessages = i18n.define({ baseLocale: "en", messages: {
  en: {
    complexShape: "This schema uses a complex shape. Enter the request as JSON.", complexField: "This schema uses a complex field. Enter the request as JSON.",
    minCharacters: ({ label, count }: { label: string; count: number }) => `${label} must contain at least ${count} ${i18n.plural(count, "en", { one: "character", other: "characters" })}.`, maxCharacters: ({ label, count }: { label: string; count: number }) => `${label} must contain at most ${count} ${i18n.plural(count, "en", { one: "character", other: "characters" })}.`,
    invalidFormat: ({ label }: { label: string }) => `${label} has an invalid format.`, cannotValidate: ({ label }: { label: string }) => `${label} cannot be validated in this form. Use JSON input instead.`, email: ({ label }: { label: string }) => `${label} must be an email address.`, uuid: ({ label }: { label: string }) => `${label} must be a UUID.`, url: ({ label }: { label: string }) => `${label} must be a URL.`,
    minValues: ({ label, count }: { label: string; count: number }) => `${label} needs at least ${count} values.`, maxValues: ({ label, count }: { label: string; count: number }) => `${label} accepts at most ${count} values.`, booleans: ({ label }: { label: string }) => `${label} accepts only true or false.`, numbers: ({ label }: { label: string }) => `${label} accepts only numbers.`, integers: ({ label }: { label: string }) => `${label} accepts only integers.`,
    jsonObject: "The request must be a JSON object.", validJson: "Enter valid JSON before running the capability.", required: ({ label }: { label: string }) => `${label} is required.`, integer: ({ label }: { label: string }) => `${label} must be an integer.`, minimum: ({ label, value }: { label: string; value: number }) => `${label} must be at least ${value}.`, maximum: ({ label, value }: { label: string; value: number }) => `${label} must be at most ${value}.`,
    reviewCancelled: "Action review was cancelled.", reviewUnavailable: "Could not load the action review.", outcomeUnknown: "The Action response was lost and its outcome is unknown; do not retry automatically.", responseTooLarge: "The capability response exceeded the shared size limit.", invalidResult: "The app returned an invalid capability result.", requestFailed: ({ status }: { status: number }) => `The capability request failed with HTTP ${status}.`,
  },
  de: {
    complexShape: "Dieses Schema ist zu komplex für das Formular. Gib die Anfrage als JSON ein.", complexField: "Dieses Schema enthält ein komplexes Feld. Gib die Anfrage als JSON ein.",
    minCharacters: ({ label, count }) => `${label} muss mindestens ${count} ${i18n.plural(count, "de", { one: "Zeichen", other: "Zeichen" })} enthalten.`, maxCharacters: ({ label, count }) => `${label} darf höchstens ${count} ${i18n.plural(count, "de", { one: "Zeichen", other: "Zeichen" })} enthalten.`,
    invalidFormat: ({ label }) => `${label} hat ein ungültiges Format.`, cannotValidate: ({ label }) => `${label} kann in diesem Formular nicht validiert werden. Verwende stattdessen die JSON-Eingabe.`, email: ({ label }) => `${label} muss eine E-Mail-Adresse sein.`, uuid: ({ label }) => `${label} muss eine UUID sein.`, url: ({ label }) => `${label} muss eine URL sein.`,
    minValues: ({ label, count }) => `${label} benötigt mindestens ${count} Werte.`, maxValues: ({ label, count }) => `${label} akzeptiert höchstens ${count} Werte.`, booleans: ({ label }) => `${label} akzeptiert nur true oder false.`, numbers: ({ label }) => `${label} akzeptiert nur Zahlen.`, integers: ({ label }) => `${label} akzeptiert nur ganze Zahlen.`,
    jsonObject: "Die Anfrage muss ein JSON-Objekt sein.", validJson: "Gib gültiges JSON ein, bevor du die Capability ausführst.", required: ({ label }) => `${label} ist erforderlich.`, integer: ({ label }) => `${label} muss eine ganze Zahl sein.`, minimum: ({ label, value }) => `${label} muss mindestens ${value} betragen.`, maximum: ({ label, value }) => `${label} darf höchstens ${value} betragen.`,
    reviewCancelled: "Die Prüfung der Action wurde abgebrochen.", reviewUnavailable: "Die Prüfung der Action konnte nicht geladen werden.", outcomeUnknown: "Die Antwort der Action ging verloren und ihr Ergebnis ist unbekannt. Führe sie nicht automatisch erneut aus.", responseTooLarge: "Die Antwort der Capability überschreitet die gemeinsame Größenbegrenzung.", invalidResult: "Die App hat ein ungültiges Capability-Ergebnis zurückgegeben.", requestFailed: ({ status }) => `Die Capability-Anfrage ist mit HTTP ${status} fehlgeschlagen.`,
  },
} });
